### ISSUE TITLE
Normal maps don't play nice

### ISSUE THREAD

**Issue by emackey** [donmccurdy/three-gltf-viewer#10]
I have a test model called [Normal-Tangent Test](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest), where I try rotating the UVs of a normal map around.  The reflected vectors are not supposed to be swayed by such shenanigans.

In particular, the light source is not supposed to "spin around", and in this screenshot I'm using the "Bridge" environment and you can clearly see the bridge spinning around.

![threejs_normaltangent_notright](https://cloud.githubusercontent.com/assets/1235080/25786975/026e7880-336b-11e7-84bf-462a2fe2b111.png)

Here's [sbtron's viewer](https://emackey.github.io/BabylonJS-glTFLoader/?model=NormalTangentTest&environment=wobblyBridge) with correct reflections.

And here are some [notes I made when creating this model](https://emackey.github.io/testing-pbr/normal-tangent-readme.html) showing it [working correctly in ThreeJS](https://emackey.github.io/testing-pbr/normal-tangent-test.html).

**Comment by emackey** [comment]
(And, off-topic, but once this issue is resolved, you may wonder to yourself what's the most ridiculously expensive PBR textures that have ever been placed on a COLLADA duck?  Well probably you weren't going to ever wonder that but in case you did I [have it covered](https://github.com/emackey/BabylonJS-glTFLoader/tree/material-ducks/src/models/2.0/png/MaterialDucks/glTF).)

**Comment by donmccurdy** [comment]
@emackey Thanks for filing this! I'm having a difficult time understanding it, though. It doesn't seem like any parameters we pass to MeshStandardMaterial should have an effect like this.. For the OBJ demo you have working with three.js, is the glTF file generated from that OBJ? They seem to have different numbers of vertices, anyway. Or perhaps GLTFLoader is parsing the UVs differently than OBJLoader.

And, the COLLADA duck models are wonderful 😁

**Comment by emackey** [comment]
The GLTF came through a work-in-progress update to the COLLADA converter.  I haven't dug into the details of what's different between it and the OBJ yet, I'll try to carve out some time for that.  The OBJ and the COLLADA came from their respective export plugins in Blender, which may have differences.  Also I should try loading the COLLADA into ThreeJS as well, to see what that does.

**Comment by emackey** [comment]
I became suspicious that the normal map problems are the result of mis-interpreting the green channel, as described here:  KhronosGroup/glTF#952

However, when I tried this with a "DirectX" normal map (as described in that issue), I got a consistent result, but a consistently 180-degree wrong result.  Strange.  Still I think we should wait for more input on the Khronos issue before we proceed here.

![nowwithdirectxnormals](https://cloud.githubusercontent.com/assets/1235080/25922305/afcef2e2-35a6-11e7-94d3-c8f1d993e196.png)

**Comment by emackey** [comment]
It's been [confirmed](https://github.com/KhronosGroup/glTF/issues/952#issuecomment-300628690) that the OpenGL (right-handed, +Y up) form of the normal map texture is the form that should officially be used.  This means the BabylonJS viewer is doing it correctly, and there may be an issue with the ThreeJS glTF loader.

**Comment by donmccurdy** [comment]
Great, thanks for looking into this. We can fix the loader for this model trivially, by adding:

```js
materialParams.normalScale = new THREE.Vector2(-1, 1);
```

Result:
![screen shot 2017-05-10 at 10 23 45 pm](https://cloud.githubusercontent.com/assets/1848368/25933885/5af7e6d8-35cf-11e7-9a22-930f82325c53.png)

... but I'm a bit confused by this. We do not otherwise touch the `normalScale` property. I don't know three.js's default (it doesn't seem to be documented). On the other hand, the BabylonJS default [is documented](https://doc.babylonjs.com/tutorials/advanced_texturing) and matches neither DirectX nor OpenGL:

> BabylonJS: x-axis = left, y-axis = down
> OpenGL: x-axis = right, y-axis = up
> DirectX: x-axis = right, y-axis = down

So if flipping `x` gives the right result for a model assumed to have OpenGL normals, that implies the three.js default to be `x=left,y=up`, which would be surprising.. I will try to check on the three.js default.

**Comment by donmccurdy** [comment]
Fixed: https://github.com/mrdoob/three.js/pull/11825
