### ISSUE TITLE
Footprint Court HDR background doesn't display properly

### ISSUE THREAD

**Issue by dakom** [donmccurdy/three-gltf-viewer#100]
<img width="1434" alt="screen shot 2018-06-18 at 7 28 01" src="https://user-images.githubusercontent.com/6406986/41533564-35561bb0-72c9-11e8-9bda-13d590d26e83.png">

**Comment by donmccurdy** [comment]
Three.js doesn't support HDR cubemaps as scene backgrounds yet — see https://github.com/mrdoob/three.js/pull/13504
