### ISSUE TITLE
When you display the LittlestTokyo.glb model in the DRACO format, many validation errors occur.

### ISSUE THREAD

**Issue by cx20** [donmccurdy/three-gltf-viewer#103]
I tried to display the DRACO format LittlestTokyo.glb model in three.js repository with three-gltf-viewer.
https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/LittlestTokyo.glb

However, it seems that a validation error has occurred. Is it a model problem?
![image](https://user-images.githubusercontent.com/1833979/43926694-11767ea8-9c66-11e8-841c-ffab90eadca3.png)

![image](https://user-images.githubusercontent.com/1833979/43926711-26674a36-9c66-11e8-8d3c-354fcd01d022.png)

**Comment by donmccurdy** [comment]
The model has some validation issues, yeah — some are a result of the validator not understanding the Draco extension. Others are actual issues.

**Comment by cx20** [comment]
I have reported validation errors to the Sketchfab Forum.
https://forum.sketchfab.com/t/many-validation-errors-occur-in-littlesttokyo-gltf-model/22923

**Comment by donmccurdy** [comment]
Seems like the right place to report it, thanks!
