### ISSUE TITLE
Update desktop applications to match latest code

### ISSUE THREAD

**Issue by naikrovek** [donmccurdy/three-gltf-viewer#104]
I'd send a PR if I knew how to do this myself.

Optionally, maybe providing instructions on how to do this would be just as good, if it's easier to document this than to do it yourself.

**Comment by donmccurdy** [comment]
Yeah I should probably both update it and write instructions. 😅

It _should_ be a simple as `npm run build && npm run package`, but I haven't run the build in a while so thinks may have broken since the last update, too.

**Comment by naikrovek** [comment]
That did work, after I downgraded Node from v10.something (current dev release) to v8.something (current LTS release) because the scripts in `npm package` thought they were working under the very old node v0.10.

The resulting gltf-viewer.exe didn't work for me on Windows, though.  Not sure what that's about.  I just get a white screen.

Hope that helps a little.

**Comment by donmccurdy** [comment]
Updated the releases (https://github.com/donmccurdy/three-gltf-viewer/releases) and added docs in the README. :)
