### ISSUE TITLE
Skinned model appears deformed

### ISSUE THREAD

**Issue by DannyRocks08** [donmccurdy/three-gltf-viewer#113]
![image](https://user-images.githubusercontent.com/33907552/47589736-9ddd0c80-d92f-11e8-9b1e-eefbed412ee1.png)

I do not understand why he does this ... Can someone help me? (in English or Spanish)

**Comment by donmccurdy** [comment]
Hi, you'll need to provide more details to get help. Can you share the model? You can drag ZIP files into GitHub comments.

If you get the same (broken) result on http://sandbox.babylonjs.com/ and http://gltf-viewer.donmccurdy.com/, I would suggest filing a bug with whatever tool was used to create your model.

**Comment by donmccurdy** [comment]
The problem you're seeing is that the model contains too many bone vertex influences. Each vertex can be affected by only 4 bones in most realtime engines. Select each mesh in Blender and use "Limit Total" in Weight Paint mode: https://blender.stackexchange.com/questions/29166/change-the-number-of-bones-in-limit-weights-in-2-7

**Comment by DannyRocks08** [comment]
Thank you very much, I'm still trying that Blender option. Thanks for the quickness of the response.

**Comment by donmccurdy** [comment]
Closing, please let me know if there's still an issue. :)

**Comment by DannyRocks08** [comment]
Sorry, XD... Thank you very much
