### ISSUE TITLE
Models show dark since update

### ISSUE THREAD

**Issue by ELanooij** [donmccurdy/three-gltf-viewer#115]
Since the change from 30/10 of setting renderer.physicallyCorrectLights = true, models look a lot darker in the viewer than before. Creating a big difference in how the model looks in this viewer versus other viewers and software like Substance Painter.

[https://imgur.com/a/VmZ5d7N](url)

Is it possible to compensate for this using different exposure and direct intensity values?

Thanks!

**Comment by ELanooij** [comment]
After testing I found that changing exposure to 1.3 and direct intensity to 2.0, the view is almost the same as it was before

**Comment by donmccurdy** [comment]
Thanks! This should be back to normal now. Per https://github.com/donmccurdy/three-gltf-viewer/issues/116, I'm surprised it was necessary to compensate, and will look into that further.

**Comment by ELanooij** [comment]
Thank you!
