### ISSUE TITLE
Show validation severity

### ISSUE THREAD

**Issue by emackey** [donmccurdy/three-gltf-viewer#117]
I've seen some users reporting validation errors they received from this viewer as if they were critical messages.  Not all of them are.  So, I suggest adding the validation severity to the front of the message.

The severity is available as `issues.messages[n].severity` in the validator's output.  The available values are:

| Value | Message Prefix | Optional Icon |
| - | -- | - |
| 0 | Error | Red circle with "X" |
| 1 | Warning | Yellow triangle with "!" |
| 2 | Information | Blue circle with "i" |
| 3 | Hint | none |

**Comment by donmccurdy** [comment]
added a hopefully-clearer report style:

![screen shot 2018-12-10 at 1 38 46 pm](https://user-images.githubusercontent.com/1848368/49763237-f0288180-fc80-11e8-8eeb-7ba1dd6a2fb8.png)
