### ISSUE TITLE
[Animation] Unexpected token < in JSON

### ISSUE THREAD

**Issue by EtagiBI** [donmccurdy/three-gltf-viewer#119]
Hello,

Animated model CesiumMan doesn't load:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMan/glTF

Error message: "Unexpected token < in JSON at position 6".

**Comment by donmccurdy** [comment]
Works for me: https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/CesiumMan/glTF/CesiumMan.gltf

The error you're seeing sounds like  a 404 error on the model, perhaps? Any network errors in the JS console?

**Comment by EtagiBI** [comment]
Hmmm. 
GLB version of the model loads flawlessly, but I still have problems with all GLTF versions. There's only one error in the console:
![image](https://user-images.githubusercontent.com/20855725/49272049-f012cf80-f491-11e8-944c-8039bd685227.png)

**Comment by EtagiBI** [comment]
Wow, that's odd. 
I used Chrome context menu to save each file from GitHub. It worked fine with BIN files and images, but not with GLTF files (although extension is correct). 

I'll definetely try your browser extension. Thanks!
