### ISSUE TITLE
doubleSided not respected

### ISSUE THREAD

**Issue by emackey** [donmccurdy/three-gltf-viewer#12]
It appears the viewer is rendering all glTF materials with back-face culling enabled.  A flag was added in the past few months to address this:

`materials[n].doubleSided`    ([schema](https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/material.schema.json#L69-L74))

You can test this with the same model used for testing in #10.

Note that the discussion surrounding this flag resulted in a decision that the rear-facing polygons should have flipped normal vectors (typically using `gl_FrontFace` to test).  The schema description field mentions the normal vectors specifically.

**Comment by donmccurdy** [comment]
To be fixed soon: https://github.com/mrdoob/three.js/pull/11296

Although I haven't looked into flipping normal vectors yet.

**Comment by emackey** [comment]
This appears to be fixed, thanks!
