### ISSUE TITLE
rotations for lights and camera's are not being imported properly.

### ISSUE THREAD

**Issue by spiraloid** [donmccurdy/three-gltf-viewer#120]
Non-Animated Lights and Camera rotations are not being imported properly.

(Note the blue light from the directional light on the side of the cube.) 

here are  example files exported from blender 2.8 with gltf 2.0:  

![screen shot 2018-11-28 at 11 27 51 pm](https://user-images.githubusercontent.com/36362743/49207260-489a7d80-f369-11e8-90a3-00e9fdd81d99.png)

if you choose the camera, it aim's the wrong way ( it should be aiming the direction in the screen shot.  I've included the .blend file if it helps)

[simple_test_b3d_2.8.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2628121/simple_test_b3d_2.8.zip)

I suspect the lighting issue is due to the warning  Unsupported extension encountered: 'KHR_lights_punctual' . but the camera not being oriented seems related.

Any chance that non-animated lights (or KHR_lights_punctual) and cameras will get supported?  it looks like the data is in the file...

It looks like the position of the lights is being interpreted as a vector rotation and the quaternion rotations are being ignored for non-animated lights and cameras.

**Comment by donmccurdy** [comment]
Hm, both are supposed to be supported. The "unsupported extension" warning just means that the validation suite can't validate that extension, which I should clear up.

What do you mean by "non-animated"? Have you tested animated cameras/lights and got different results? No need to do that if not, I'm just wondering.

**Comment by spiraloid** [comment]
I'm not certain, but I suspect that the rotations being acurate on the wiggling skinned mesh but being incorrect on the lights and camera made me wonder what the lights and camera have in common, and where they could be getting their incorrect rotations from since they do not look zero.  They are both without animation channels which likely take a different code path then the scene population code.  all this is conjecture, but I suspect there is a bug in the scene population code that is interpreting rotation from the position vector and not the rotation quaternion.

**Comment by spiraloid** [comment]
this is from blender 2.8 beta with khronos gltf 2.0

https://github.com/KhronosGroup/glTF-Blender-IO

**Comment by bghgary** [comment]
> @bghgary does https://sandbox.babylonjs.com/ support cameras?

Sure does. You can use the new inspector to select the camera that was loaded.

![image](https://user-images.githubusercontent.com/19158740/49251258-e88df080-f3d5-11e8-8a38-18c6b7bc19d8.png)

**Comment by spiraloid** [comment]
Hmm...

I'm seeing a camera node, but I'm not seeing it rotated correctly. 
I also note that the HDR sky didn't export.

![image](https://user-images.githubusercontent.com/36362743/49259062-ac19bf00-f3ec-11e8-9ddc-0dee30279206.png)

blender.2.8 beta is today so here's a fresh runthrough scene made from scratch an exported to verify the camera and lights are working.  

here's an archive with the 2.8 .blend file, textures and both exports for testing.

**Comment by donmccurdy** [comment]
Ok, I'm pretty confident this is an exporter issue. See replies on https://github.com/KhronosGroup/glTF-Blender-IO/issues/114.

**Comment by donmccurdy** [comment]
https://github.com/KhronosGroup/glTF-Blender-IO/issues/114 has been fixed in the exporter — please comment there if the issue is not resolved after updating Blender to latest 2.8 beta.
