### ISSUE TITLE
make it clearer that "unsupported extensions" refer to the validator

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-gltf-viewer#122]
or better yet, do a table of which extensions are supported, ignored, and/or validated.

**Comment by donmccurdy** [comment]
could still be clearer, per https://github.com/donmccurdy/three-gltf-viewer/issues/127#event-2040569924.

**Comment by samsuniya** [comment]
xtensions above are present in the model, but may or may not be recognized by this viewer. Any "UNSUPPORTED_EXTENSION" warnings below refer only to extensions that could not be scanned by the validation suite, and may still have rendered correctly. See: [three-gltf-viewer#122](https://github.com/donmccurdy/three-gltf-viewer/issues/122).
