### ISSUE TITLE
Adding new HDRI's 

### ISSUE THREAD

**Issue by bloomhub** [donmccurdy/three-gltf-viewer#124]
Hi Guys, 

Question from a non-developer - how can we add different HDRI's to this viewer? 

We are using this viewer for our kids furniture line bloombaby.com and the current environments don't match our products (some of our products have shiny reflective plastic components) 

Any help would be greatly appreciated.

**Comment by donmccurdy** [comment]
Hi! Adding HDRIs isn't supported now, although you could of course run the code locally ([quickstart](https://github.com/donmccurdy/three-gltf-viewer#quickstart)) and swap out the existing environments. I like the idea of letting you drag-and-drop an environment along with your model, but the environment would probably need to be prepared in a supported format, e.g. as a cubemap. Example here: https://github.com/donmccurdy/three-gltf-viewer/tree/master/assets/environment/FootprintCourt.

Is that roughly what you were thinking?

**Comment by bloomhub** [comment]
Thanks Don. We're really new to this so please bare with us. I appreciate the help! 

Our issue lies in not having more flexibility to the environment choices and lighting settings. 

We are building all models in blender but when exporting and importing the your viewer, we're super limited to changing the lighting preferences. We've not used quickstart or cubemap before (learning now). If there was a way to import other pre existing environments from a library, we'd be happy to test any available ones to see if it works with our line. 

See attachment with the two different views. Your viewer image on the left, ours on the right. We're close but need some tweaking. 

Thanks again. 

![gold v gold](https://user-images.githubusercontent.com/45695829/49749574-a76bcb00-fc76-11e8-8d5e-94d9aa99b994.png)

**Comment by donmccurdy** [comment]
> If there was a way to import other pre existing environments from a library...

Do you have a library of environments yourselves, or are you looking for more options to be added to this viewer directly? If the former, do you know what format(s) those environments are in? 

I have access to a few environments but can't guarantee it's enough to match the image above, for example.

**Comment by bloomhub** [comment]
Looking for more options to be added. I've setup the files in Blender for rendering or 3D animations and I use the lamps in the scene to obviously light the scene. But as we can't export the lighting setup then we have to use the "preset" options available in the viewer. I can try to source some environments but i'm not sure what format they need to be. Are they cubemaps?

**Comment by bloomhub** [comment]
Thanks Don, emailed you :)

**Comment by Tamal3d** [comment]
Is it be possible to add a option in the Lighting menu environment dropdown that user can change the HDRI background image from there desktop folder.

**Comment by donmccurdy** [comment]
@Tamal3d I like the idea, but no, it isn't possible today.

**Comment by donmccurdy** [comment]
Still no plans on this feature — going to close out the issue.
