### ISSUE TITLE
Draco support

### ISSUE THREAD

**Issue by dmarcos** [donmccurdy/three-gltf-viewer#127]
Is there support or plans to support Draco in the viewer? In the deployed one?

**Comment by donmccurdy** [comment]
It’s supported! Are you seeing errors? I don’t think the validation library can check it yet, so you’ll see UNSUPPORTED_EXTENSION warnings in the report window.

**Comment by dmarcos** [comment]
Yep I used to see UNSUPPORTED_EXTENSION now I get `THREE.DRACOLoader: Decoding failed: Failed to decode geometry data.` on console. There something wrong with my model. Thanks for helping. Closing this.
