### ISSUE TITLE
"object is undefined" error for glTF files with no scenes

### ISSUE THREAD

**Issue by scurest** [donmccurdy/three-gltf-viewer#132]

**Comment by donmccurdy** [comment]
The error could be clearer, but I'm not sure this viewer should show anything given a file with no scenes. Are you just expecting the validation suite to run? Or to see any nodes in the file placed at the origin?

**Comment by scurest** [comment]
I think the obvious thing to do is to show everything. The spec, of course, does not mandate you show anything. Whatever you do, it shouldn't be an error.

**Comment by donmccurdy** [comment]
I'm not aware of any precedent for a displaying a glTF file without any scenes, and I'd prefer not to invent my own. In particular, if the author's intention were for everything to appear, putting everything into a default scene is the typical way to accomplish that. 

Using a glTF file as a library (of meshes, materials, animations, etc.) is valid, but until some consensus or common practice emerges I think I'd prefer to simply show a message along the lines of:

```
This model contains no scenes, but may have other resources included in it.
```
