### ISSUE TITLE
Failure to load glb file (texture missing or crossorigin issue?)

### ISSUE THREAD

**Issue by emnh** [donmccurdy/three-gltf-viewer#135]
I can load this file http://emh.lart.no/publish/three-gltf-viewer-issue/Marine.glb in the built-in viewer in Windows 10, but I can't load it with three-gltf-viewer. It's generated using the Facebook FBX to GLTF tool. Did I fail to include textures or is there something wrong with crossorigin blob? Getting the following errors on the viewer in console:

THREE.WebGLRenderer 101
bundle.js?v=r101:68057 Missing texture: a9b62aa6-d5bc-455f-bc16-a44dc60c65c8
onError @ bundle.js?v=r101:68057
viewer.load.catch @ bundle.js?v=r101:68035
Promise.catch (async)
view @ bundle.js?v=r101:68035
load @ bundle.js?v=r101:68009
dropCtrl.on @ bundle.js?v=r101:67973
listeners.(anonymous function).forEach @ bundle.js?v=r101:11714
_emit @ bundle.js?v=r101:11714
_loadNextEntry @ bundle.js?v=r101:11799
entry.file @ bundle.js?v=r101:11806

**Comment by donmccurdy** [comment]
The textures in this model are in the DDS compressed texture format, which isn't allowed by the glTF 2.0. There are glTF extensions (`MSFT_texture_dds`) that can add the DDS feature, but (1) this model isn't using those, and (2) depending on the device they may not work at all – most smartphones can't use DDS textures, if I'm remembering correctly. If you want this model to work outside of Microsoft programs, it would be better to use JPEG or PNG textures. I'm not sure if that's something the FBX2glTF converter should handle differently, or if you have access to the original textures.

![screen shot 2019-02-24 at 9 00 28 pm](https://user-images.githubusercontent.com/1848368/53315467-2b961d80-3878-11e9-9cb8-12a76dab337e.png)

**Comment by zellski** [comment]
Decompressing whatever is in those DDS files, almost certainty a lossy format, and re-encoding is pretty dubious... no, I don’t think the FBX2glTF tool should do that.

However, it might make sense for the tool to  detect the DDS file format and tag the glTF with the extension.

But as Don says, this is not a general purpose FBX file; it’s a delivery file that will likely only work on some machines (with desktop GPUs).

**Comment by emnh** [comment]
I am not planning to distribute the files (actually I am not allowed to). It's just some testing for a personal project. So I will try to use JPG first.

**Comment by emnh** [comment]
Yes works fine with JPG :)

Closing the issue.
