### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thekid87** [donmccurdy/three-gltf-viewer#136]
Getting this error when I upload

Validation could not run: TypeError: Cannot read property 'parser' of undefined.
or
Something went wrong: TypeError: Cannot read property 'length' of undefined

with just the gtlf and bin I get [Object Event]

**Comment by donmccurdy** [comment]
Could you share a ZIP of the files? You can drag zips into github comments.

**Comment by donmccurdy** [comment]
May also be worth trying to use the whole ZIP in the viewer.

**Comment by thekid87** [comment]
Thanks for the response Don. It worked after a bit. Not sure why I was having issues.
