### ISSUE TITLE
new default Light like model-viewer

### ISSUE THREAD

**Issue by arpu** [donmccurdy/three-gltf-viewer#144]
@donmccurdy  what do you think to use like this

https://github.com/GoogleWebComponents/model-viewer/pull/472

**Comment by donmccurdy** [comment]
For now I don't plan to change anything. The model-viewer default lights have been evolving and may continue to change for a while. threejs is working on Spherical Harmonics-based lighting, and glTF is working on an environment map extension, so all of that may eventually affect the defaults here at some point later on.

**Comment by arpu** [comment]
thx for clarification
