### ISSUE TITLE
Option to not automatically centre the model

### ISSUE THREAD

**Issue by funwithtriangles** [donmccurdy/three-gltf-viewer#145]
It's sometimes useful to see the model in the position it was exported rather than it be automatically centred. Especially when viewing the grid. For example you may want to check if your model of a table is lined up with the "ground".

A simple checkbox to "automatically centre the model" is all that is needed here.

**Comment by donmccurdy** [comment]
I'm open to this yes – not sure how soon I can make the change, PRs welcome.

**Comment by jeymichael** [comment]
This is probably not a best candidate for UI option, imo.  
1) Leaving the objects in its actual position, and then 
2) Providing a mechanism for displaying the view axis (independent of the grid position at origin) would address the real issue, without any new UI option.

This is a pretty standard behavior of the 3D software packages.  

Don, I have added a PR for this change, for your review.  
https://github.com/donmccurdy/three-gltf-viewer/pull/163

**Comment by jeymichael** [comment]
@donmccurdy You have any feedback on this change?

**Comment by donmccurdy** [comment]
Sorry for the delay; I've left some comments on https://github.com/donmccurdy/three-gltf-viewer/pull/163. I like the idea of adding a view axis, but I don't think it sufficiently solves the reason that I'm recentering the objects to begin with – many models are far from the origin, and I'd like to minimize the number times that a user will drag a model into the viewer and see nothing at all on screen. 

There are probably other ways to address it, but I'd prefer that users not have to dig through the settings to get that first glimpse of their model.

**Comment by donmccurdy** [comment]
No further plans on this issue, I think it's best and simplest if the viewer continues to center the content.
