### ISSUE TITLE
Consider making emissive textures not affected by exposure

### ISSUE THREAD

**Issue by j-conrad** [donmccurdy/three-gltf-viewer#148]
Lowering the Exposure setting currently lowers all channels' brightness. Please consider making emissive textures not be affected by lowering the exposure. This would more accurately reflect the way emissive textures are treated in most renderers. Substance Painter is a good example of this:
![ExposureSubsPainter](https://user-images.githubusercontent.com/31968496/57762965-59d80c00-76b5-11e9-91fb-2111af7b982c.png)

**Comment by zellski** [comment]
How interesting. Is there a physics-based justification for this? Is the idea that emissive lighting is meant to be a property of pixels more than of a surface? But you'd still want e.g. fog to affect it, right?

**Comment by j-conrad** [comment]
I’m not totally sure from a physics standpoint. From a content-creation point of view, emissive textures are most commonly associated with light sources (a car’s headlights, an LED on some gadget, or perhaps a glow-in-the-dark decal). If you were to shine a light on a lit lightbulb, unless that light was much brighter than the bulb, it would have little to no visual change on the bulb’s surface. By that logic, turning off all lights in a room except for the bulb would also have no effect on the bulb. Lowering a camera’s exposure might eventually have an effect but the bulb would still be the last thing to disappear from the image.
https://d1w9csuen3k837.cloudfront.net/Pictures/480xany/1/0/3/135103_shutterstock_658317529.jpg

**Comment by donmccurdy** [comment]
This setting controls three.js's [`renderer.toneMappingExposure`](https://threejs.org/docs/#api/en/renderers/WebGLRenderer.toneMappingExposure) setting, so any change here would require a change in three.js.

> Lowering a camera’s exposure might eventually have an effect but the bulb would still be the last thing to disappear from the image.

This doesn't really make sense to me. You're assuming the emissive surface is much brighter than the surrounding surfaces, but there's no reason that should necessarily be true. I could just as easily have a dim emissive surface that doesn't reflect any light, next to a non-emissive surface that happens to be reflecting a lot of light toward the camera.

I think you _could_ make an argument that unlit/shadeless materials shouldn't be affected by tonemapping, in which case `toneMappingExposure` would also have no effect, and that's functionally very similar to an emissive. But in any case the change would be outside of this viewer.
