### ISSUE TITLE
GLTF2 missing opacity with KHR_material_common

### ISSUE THREAD

**Issue by Arcnor** [donmccurdy/three-gltf-viewer#15]
`diffuseFactor` values with alpha != 1.0 are not respected on KHR_material_common, although they are working with PBR SpecularGlossiness. The fix seems just adding the alpha value to the `opacity` on `materialParams`, but I'm not sure if something else is required, hence the bug report :)

**Comment by donmccurdy** [comment]
Thanks @Arcnor — can you share a model that shows this issue? You may be right, but there should also be an `alphaMode` property in the model, and if that's (a) not there, or (b) set to opaque, then it's correct that we're ignoring the diffuseFactor alpha value. So, just want to check on whether it is a viewer or an exporter problem here.

**Comment by Arcnor** [comment]
There is also an `alphaMode` property (set to `BLEND`) which is being ignored (I can't find references to `alphaMode` anywhere on the source, but there a few million branches, and I'm not sure which one is the right one xDD)

I'll try creating a sample that I can share, but after applying the mentioned patch, it works for my models (although I ignore that `alphaMode` as well for those...)

**Comment by Arcnor** [comment]
Here you go. Same example as last time, but there is a box inside the outer box, which you cannot see :).

Exported with Blender.

[boxTransparency.gltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1096771/boxTransparency.gltf.zip)

**Comment by donmccurdy** [comment]
Great, thanks! Yeah, the bug was in GLTF2Loader :) https://github.com/mrdoob/three.js/pull/11592

**Comment by Arcnor** [comment]
Awesome, that's exactly what I did with my fix. But you're also ignoring `alphaMode` there, I see?

Anyway, thanks a lot :)

**Comment by donmccurdy** [comment]
> But you're also ignoring alphaMode there, I see?

That should be fixed now too; we were only checking it for PBR materials.

**Comment by donmccurdy** [comment]
Fixed!

**Comment by Arcnor** [comment]
Thanks!
