### ISSUE TITLE
Three.gltf Viewer Animation Error

### ISSUE THREAD

**Issue by kraway** [donmccurdy/three-gltf-viewer#151]
Hi,
I've followed this [tutorial](https://www.donmccurdy.com/2017/11/06/creating-animated-gltf-characters-with-mixamo-and-blender/) to create a multi-animated character using Mixamo and Blender (using 2.8). I've exported as .glb file and it seems to be truncating the animation when I drop it into the three-gltf-viewer (it's also wrong in the web program we're using). It does work fine in the BabylonJS viewer.

Here's the .glb file I'm working with:
[MIB-2.0-export.glb.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3204460/MIB-2.0-export.glb.zip)

I've also attached a screenshot of the errors I'm getting in the three-gltf-viewer if that helps any.
![Screen Shot 2019-05-21 at 4 53 06 PM](https://user-images.githubusercontent.com/50887939/58130007-14519c80-7be9-11e9-9f0a-6f06bf57a552.png)

**Comment by donmccurdy** [comment]
Hm this looks like a bug, yep. Thanks!

**Comment by donmccurdy** [comment]
Merging with https://github.com/donmccurdy/three-gltf-viewer/issues/150.
