### ISSUE TITLE
Viewer not showing animations

### ISSUE THREAD

**Issue by elbobo** [donmccurdy/three-gltf-viewer#153]
Hi,

This may well be related to a couple of other issues here but I am exporting models with animations (glb) from Blender and while the animation shows in the sidebar, the viewer does not actually play the animation. I think the model is fine as;

a) there are no errors 

b) it plays fine in the babylon viewer 

c) it runs fine in aframe using the aframe-extras and the `animation-mixer` component.

So my guess would be there is some issue with this viewer? It seems to be true of lots of different types of animations (from simple object translations to armature driven ones).

Its a really helpful tool - thank you and I hope you can fix it!

**Comment by donmccurdy** [comment]
Could you share an example of a model that doesn't work in this viewer? You can drag ZIP files into comments on GitHub.

**Comment by elbobo** [comment]
Thanks for getting back, here is a zip with a minimal example (original .blend file & 2 glb exports).
As you'll see I have a cube whose position is animated. If I export with the default settings (`simpleslide.glb`) there is some animation but it is incorrect (in the case including some rotation on the cube that I have not added. So I tried again and checked 'Always sample animations' (`simpleslide_alwayssampleanimations.glb`) as this has fixed irregularities for me in the past but in this case you can see that there is no visible animation at all despite the fact that the animation is listed in the right hand panel.

I'd be grateful if you could have a look - perhaps I'm doing something wrong? As I say, I have stripped my example down to the bare minimum so not sure what I could be missing.

[simpleslide.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3224007/simpleslide.zip)

**Comment by donmccurdy** [comment]
Merging this issue with https://github.com/donmccurdy/three-gltf-viewer/issues/150.
