### ISSUE TITLE
How to load gltf files from ajax request?

### ISSUE THREAD

**Issue by mytherf** [donmccurdy/three-gltf-viewer#154]
The URL of my gltf file  is encrypted, eg: #model=sshdiah93842hd JSDiewj2423. 
I need decryption it and  request some API to validate. 
how to load url from ajax request and load gltf file?

**Comment by mytherf** [comment]
done

**Comment by tvxqljw** [comment]
would you like to show some demo source code for learning?

**Comment by tvxqljw** [comment]
> done

would you like to show some demo source code for learning?
