### ISSUE TITLE
How webpack Build 

### ISSUE THREAD

**Issue by MachiBarton** [donmccurdy/three-gltf-viewer#155]
I want to build the program into the web online version, but I didn't find a way. Please give me some advice on how to do it.
i can`t find some script webpack Build  like vue (npm run build)

**Comment by donmccurdy** [comment]
The steps to run this locally are:

```
npm install
npm run dev
```

The project uses Browserify rather than Webpack.

**Comment by donmccurdy** [comment]
The script `npm run build` creates a `bundle.js` file that can be used if you want to host the app, as static files, on the web.
