### ISSUE TITLE
 viewer has the "Y/green channel is flipped" issue in normal maps

### ISSUE THREAD

**Issue by Ybalrid** [donmccurdy/three-gltf-viewer#156]
Hi there, I don't know if it's a three.js thing, or specifically this program (I'm not a JS dev, but I cannot find the shader used in the resources here directly, so I asum it probably is a three.js issue...) but seems that when testing the "NormalTangent Test File" in it, it renders like this

![image](https://user-images.githubusercontent.com/1816251/60209594-3dee8b00-985b-11e9-9f2b-2702433e96dd.png)

It seems, according to the README.md for that test that it is miss interpreting the Y vector of the normal map.

This is documented here : https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest#problem-flipped-y-axis-or-flipped-green-channel

If that's the case, the fix is rather simple in the vertex shader, just flip the value of the green channel and/or the Y vector interpreted from it

I had to fix this issue on a project I'm working today. I'm testing a few other viewer to see if they react in the same way. (https://twitter.com/i/status/1143887356367384578)

**Comment by donmccurdy** [comment]
See https://github.com/mrdoob/three.js/issues/11438.

**Comment by Ybalrid** [comment]
Looks like the underlying issue is a bit more complex then 🤔
