### ISSUE TITLE
iframe options

### ISSUE THREAD

**Issue by tolchai** [donmccurdy/three-gltf-viewer#157]
hey!

love this project and especially how easy is to use via iframe. I just have one question here - I wanted to use the iframe within a full-width element, which is currently not possible, since the user can't scroll over the iframe (the scroll functionality is used for zooming-in & out the model). 

Is there currently a way around it?

Thanks!

**Comment by donmccurdy** [comment]
You may find https://github.com/GoogleWebComponents/model-viewer/ to be even better for that sort of use case – it's definitely more efficient if you'll have multiple models embedded on the same page.

That said, I'd be OK with having a URL option that disables zooming. I don't have time to do that right now, but PRs would be welcome.
