### ISSUE TITLE
Center not reset when loading a new model

### ISSUE THREAD

**Issue by Arcnor** [donmccurdy/three-gltf-viewer#16]
Sorry if this is nitpicking, I'm not really sure what is your goal with this viewer and this is something I think is not "right behavior" for a viewer, but again, it depends on what your goal with the viewer is.

1. Load a model
2. Use right click to move the model
3. Load the same model again
4. Try to rotate

The rotation will be around the previous point of rotation. I think this should be reset every time a new model is loaded, as going back to the center is impossible (because there are no buttons or references). For now, the obvious workaround is reloading the whole page, but that should not be necessary in my opinion.

Again, sorry if this is nitpicking, and thanks for reading :).

**Comment by donmccurdy** [comment]
This seems very reasonable :)

Will be fixed on next release: https://github.com/donmccurdy/three-gltf-viewer/commit/58dadd1ed54c2f6ca0eabf3253c48c3b5fee2b5a

**Comment by Arcnor** [comment]
Thanks a lot!
