### ISSUE TITLE
Suggested improvement

### ISSUE THREAD

**Issue by biomorphica** [donmccurdy/three-gltf-viewer#161]
It would be so fantastic if this viewer could also have an inspector, that showed the scene graph and material details for selected 3d objects. Exposing materials so that params can be adjusted so that a look can be dialed in would be immensely useful and time saving.

**Comment by donmccurdy** [comment]
Unfortunately all that is beyond the scope that I have time to build or maintain here. Alternatives might be:

- https://threejs.org/editor/
- https://sandbox.babylonjs.com/
- upcoming [UX3D glTF editor](https://twitter.com/UX3DGpuSoftware/status/1156623640533897219)

**Comment by donmccurdy** [comment]
Or Blender, for that matter. :)

**Comment by biomorphica** [comment]
Thanks for responding Don. these links are great.
I didn't know about the threejs editor. Yes this is exactly what I was
looking for. Awesome!
The babylon sandbox is truly amazing. I use that a lot (but not perfectly
compatible with THREEjs).
And the upcoming gltf editor is probably exactly what I'm requesting, so
thanks again for being such a badass.
I have huge respect for what you have already given the community, and
really appreciate you taking time for a newb like me.
btw, my threejs skills are improving a lot, and looks like I'll be able to
deal with making my own light map materials.
When I get it sorted out, I'll share it with the community via slack.
thanks for all that you do.
Thomas
