### ISSUE TITLE
Textures showing up darker

### ISSUE THREAD

**Issue by MuffyMaria** [donmccurdy/three-gltf-viewer#165]
Hey there! I have noticed that 3D models' materials have been showing up darker compared to when they were being prepared in Substance Painter. For example, a model that is exported with a full white material/texture shows up lightly grey in the gltf viewer.

![image](https://user-images.githubusercontent.com/55873189/65758739-e2fa5780-e119-11e9-8c19-9efe8a24a00e.png)

Has there been any color display changes to the viewer lately? Thank you!

**Comment by donmccurdy** [comment]
There are changes to the PBR lighting equations in threejs periodically, things like energy conservation would affect overall brightness. But If you're just comparing the brightness of a fully-white material, the dominant factor is almost certainly going to be scene lighting, and I haven't made any attempt to match the default lighting from any particular program like Substance Painter.

The effect above looks OK to me, mostly just that SP has brighter lighting from one direction.

**Comment by MuffyMaria** [comment]
Aah alright, understood. Thank you for the quick reply!
