### ISSUE TITLE
Transparency render order issue

### ISSUE THREAD

**Issue by samyH** [donmccurdy/three-gltf-viewer#169]
Hi,

I have run into a problem whilst trying to correctly render the glass for a car.  I have tried exporting as 4 separate objects and also as 1 object containing ass the glass.

From what I can see in the [gltf viewer](https://gltf-viewer.donmccurdy.com/) it seems to be splitting the 4 pieces of glass and rendering them in a particular order.  Is there a way to disable this behavior whilst retaining the alpha & reflective properties.

Attached is the model & a screenshot of the material inside Blender.

Many Thanks

![Screenshot-(159)](https://user-images.githubusercontent.com/9335155/69961450-cefd1880-1503-11ea-817e-1fc48d0c28a6.jpg)

[glass.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3911354/glass.zip)

**Comment by donmccurdy** [comment]
Should be fixed by https://github.com/mrdoob/three.js/pull/18235. If you're using this model in your own threejs application in the meantime, you can set `depthWrite=false` on transparent materials to avoid the issue.

**Comment by donmccurdy** [comment]
Fixed in the latest viewer release; I'm not sure when/if the change will land in threejs.

Also note that the model doesn't appear to have UVs, which you'd need for that texture to work correctly.

**Comment by samyH** [comment]
Thanks for the heads up @donmccurdy - really appreciate all your hard work in this area. Cheers Sam

**Comment by donmccurdy** [comment]
Fixed in three.js — https://github.com/mrdoob/three.js/pull/18235. Thanks for the report!
