### ISSUE TITLE
Problems with skinned model

### ISSUE THREAD

**Issue by Arcnor** [donmccurdy/three-gltf-viewer#17]
Sorry for opening so many issues, but I'm using your viewer as the way to check a exporter I'm writing, and I'm going feature by feature :).

In this case, I took a model you uploaded to the Blender glTF exporter repository for an issue with skinning. I've converted the "Dog.blend" file, but the model doesn't play in the viewer. Maybe it's an issue with the exporter, but I can't see anything wrong with the converted file.

I'm getting lots of errors on the console with the viewer, which I'm guessing they should not happen even if the model is somehow broken.

[Dog.gltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1096869/Dog.gltf.zip)

**Comment by Arcnor** [comment]
It seems `morphTargets.updateMorphTargets()` is called to create the `morphTargetInfluences` array if there are `morphTargets` on the object, but then that array is used when `weights` are defined (without checking for `morphTargets`), so the array is undefined.

I'm not knowledgeable enough on skinning yet to fix this, but I hope that helps.

**Comment by donmccurdy** [comment]
This was a bug in three.js I think, but it was already fixed with r86. I updated the viewer from r85 to r86 and:

![010310ad-8287-4a71-b922-d1877b63901c-50355-0000959550586fbc](https://user-images.githubusercontent.com/1848368/27505216-4104cfdc-584f-11e7-8401-f0d49225ef3f.gif)

**Comment by Arcnor** [comment]
Awesome! Thanks 😄
