### ISSUE TITLE
cannot upload folder from file picker

### ISSUE THREAD

**Issue by Alloyed** [donmccurdy/three-gltf-viewer#170]
on latest firefox, linux+gnome.
From the native file picker, I can open folders, and I can select files to upload, but there doesn't seem to be an option to upload a folder.

dragging and dropping does seem to work, so I'll just do that for the time being~

**Comment by donmccurdy** [comment]
I believe that's a limitation of the file picker itself, or the Web APIs for using it. I've never found any way to let you select a folder through the picker, unfortunately.
