### ISSUE TITLE
Keyframe issue with not showing linear

### ISSUE THREAD

**Issue by Geegrafix** [donmccurdy/three-gltf-viewer#172]
It appears that linear keyframes are NOT linear in the viewer. Is this actually the case? To illustrate, make a plane and scale it from 100% to 0% in 1 frame, then from 0% to 100% in 1 frame.

Make all the keyframes are linear and when dragging the gltf into the viewer, you can see it does not happen in one frame. To see this easier, slow down the animation speed to something like .1

Is there a way around this? This does not seem like a desirable intention.

*Not sure how to upload a gltf or I would (I'm new to github)

**Comment by Geegrafix** [comment]
Noticed somebody used drive to share a file so here is a link to a simple animation showing the problem:

https://drive.google.com/file/d/14aSAzdYCFWSO9cm04-L9C9CV_9Nzj-HD/view?usp=sharing

**Comment by donmccurdy** [comment]
Welcome to github! :)

The animation is linear, but there are ~15 keyframes in it:

![Screen Shot 2019-12-21 at 4 35 50 PM](https://user-images.githubusercontent.com/1848368/71315373-134b4c80-2410-11ea-8b87-ddcd124e0179.png)

^Screenshot from [gltf-vscode](https://github.com/AnalyticalGraphicsInc/gltf-vscode).

As you can see above, the scale for most of those keyframes is 1, which explains the long pauses between animation. That might have to do with your playback range or sampling options when you export from Blender?

Here's another version, with only three keyframes at 0, 15, and 30, with scales 1, 0, 1. I disabled the "Always sample animations" option to create that with exactly three keyframes, but generally you probably want to keep that on (it will give better results with more complex animations like skinning).

[scalePlaneClipped.gltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3991998/scalePlaneClipped.gltf.zip)

^You can also drag ZIP files into GitHub comments.

**Comment by Geegrafix** [comment]
Thanks Don! Sorry about the confusion. As I thought about it, I think I have misspoke about the keys not showing linear. It might actually be linear. What appears to be happening is that it is not respecting the keys present.

For example, the gltf I sent did have sampling every frame just to see if I could stop the behavior which didn't happen. I will attach one with the 3 key frames to show the problem still present.

Drag this one to the viewer (or even the last one I did with all the keys) to the viewer and set the speed to .1 and you will see that it ignores the keys. It does it's own set of keying (or something).

The animation should have the scale humming along at 100% and then in 1 frame go to 0 and the next frame to 100 again so an instant snap down and back.

The way the viewer presents it currently is not that. I should not see the plane at 50% or any other size other than 0 or 100 if that makes sense.

[scalePlaneClipped.gltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/3992043/scalePlaneClipped.gltf.zip)

Thanks for the tip of zipping it! Don't know why I didn't notice that was an option :(
Thanks again for the help.

**Comment by Geegrafix** [comment]
Wait a minute. I'm starting to think something else is happening. Being an animator, I think in terms of frames. So I don't want to see the in between frames, but the viewer must be showing sub frames or something?

**Comment by Geegrafix** [comment]
I think it needs to be viewed with the sampled animation to avoid confusion. It does something weird. Also the 3 keys one was not correct. It appears I had 5 keys on the scale dang it. Sorry

**Comment by donmccurdy** [comment]
> Being an animator, I think in terms of frames. So I don't want to see the in between frames, but the viewer must be showing sub frames or something?

Although you animate in frames (usually 24-30 fps), most viewers will render at 60-120 fps. A two-keyframe animation with scale=0% at frame=1 and scale=100% at frame=2, where the authoring tool used 30fps, will render at 0%, 50%, and 100% in a 60fps viewer, assuming linear interpolation. Slowing time down (as the slider in my viewer does) will continue rendering at 60fps but with new intermediate frames interpolated from the source frames. This is the same interpolation you'd get in Blender if you'd created keyframes at frame=1 and frame=3, instead of using adjacent frames.

So, some interpolation (linear, in this case) must be used even if you've only set two keyframes. glTF offers three choices for that interpolation:

- cubic spline
- linear
- step

To get the effect you're describing, try "step" animation. In Blender that would be called "constant" or "discrete" I think, under the animation curve options.

**Comment by Geegrafix** [comment]
Ah hah! You helped me find the solution!

I had done stepped or "constant" in my testing previously in hopes it would work but it didn't. It turns out by turning on "Always Sample Animations" it was causing it not to work. I'm assuming this option essentially "bakes" the animation by putting a keyframe on everyframe, probably with linear.

Once I used "constant" in blender and turned off "Always Sample Animations", it solved my problem!

Thanks for all your patience and help Don!

ps. I'm now wondering should "Always Sample Animations" not be stepped? I may not be thinking of use cases it shouldn't be, but being an animator it seems like it should. Or maybe an option allowing it?

**Comment by donmccurdy** [comment]
> ps. I'm now wondering should "Always Sample Animations" not be stepped? I may not be thinking of use cases it shouldn't be, but being an animator it seems like it should. Or maybe an option allowing it?

Yeah, sounds like it should really be stepped if the input animation was stepped. Otherwise the current linear sampling is best. I'd recommend filing an issue on https://github.com/KhronosGroup/glTF-Blender-IO about that. 👍

**Comment by Geegrafix** [comment]
Thanks Don for all your help! I'll file an issue over there when I have second. Thanks!

**Comment by donmccurdy** [comment]
Fixed by https://github.com/KhronosGroup/glTF-Blender-IO/pull/844. :)
