### ISSUE TITLE
Some questions about loading

### ISSUE THREAD

**Issue by Neplight** [donmccurdy/three-gltf-viewer#176]
When I uploader my model in your viewer, it is fine. But when I use gltfLoader.js in my own .html, the model is darker than the original one. I could not find out why, can you help me a little?

**Comment by donmccurdy** [comment]
Are you using three.js, or something else?

Most likely causes would be:

(a) different lighting. I use directional lights and IBL. Metallic materials will always need IBL (also called an environment map or `.envMap` in three.js.
(b) renderer gamma / sRGB settings are incorrect. See the instructions in the 'textures' section of the GLTFLoader docs: https://threejs.org/docs/#examples/en/loaders/GLTFLoader

Assuming you're using three.js, I'd recommend discourse.threejs.org/ for more detailed help. :)
