### ISSUE TITLE
mixamo FBX and Blender 2.81 exported scale is wrong

### ISSUE THREAD

**Issue by arpu** [donmccurdy/three-gltf-viewer#178]
three-gltf-viewer
![Bildschirmfoto von 2020-01-06 21-54-42](https://user-images.githubusercontent.com/14173/71851675-5fb4ae80-30d7-11ea-970a-5cd215b8e09f.png)

babylon:
![Bildschirmfoto von 2020-01-06 21-54-18](https://user-images.githubusercontent.com/14173/71851717-70652480-30d7-11ea-992e-0d64df802991.png)

glb file:
https://khronosdevs.slack.com/files/UED06CLP2/FRY788UV9/man.glb

threejs master editor bounding box
![Bildschirmfoto von 2020-01-06 21-58-42](https://user-images.githubusercontent.com/14173/71851959-fd0fe280-30d7-11ea-9666-55a0b1f3b6f1.png)

**Comment by donmccurdy** [comment]
I think this is the same issue as https://github.com/donmccurdy/three-gltf-viewer/issues/147 — the model's scale is actually correct, but the default camera position is quite bad because the skinning deformation isn't considered.
