### ISSUE TITLE
Update to new glTF-Validator

### ISSUE THREAD

**Issue by zeux** [donmccurdy/three-gltf-viewer#179]
Would be great to bump validator version to incorporate all recent improvements.

**Comment by donmccurdy** [comment]
Done!

**Comment by zeux** [comment]
Thanks! gltfpack'ed assets (without compression) now render and validate fine :D

![image](https://user-images.githubusercontent.com/1106629/72179414-adf8d480-3399-11ea-9eb4-aea683cf7b13.png)
