### ISSUE TITLE
Cannot find module electron-serve

### ISSUE THREAD

**Issue by Tompote** [donmccurdy/three-gltf-viewer#182]
After `npm run package`, openning gltf-viewer.exe from windows triggers `Cannot find module electron-serve` error. Fixed when moving electron-serve to dependencies instead of devDependencies.

Everything works fine with `npm run dev:electron`.

PS: Don't know if it's related yet but, after moving electron-serve to dependencies, the app launch by running the exe with only a blank screen.

**Comment by donmccurdy** [comment]
Is there a reason you need to package it without installing dev dependencies? I put it there because I consider that a development environment action; running `npm install` locally should get you both.

**Comment by Tompote** [comment]
I might be wrong because I'm really new to Electron but the point of packaging isn't that the final executable can be fully portable ?

**Comment by donmccurdy** [comment]
The final executable should be portable, yes. But building that executable does require the dev dependencies. Note that I create the release builds myself, periodically, and host them here: https://github.com/donmccurdy/three-gltf-viewer/releases

**Comment by Tompote** [comment]
Your latest release works fine but it's on version 1.4.1. I have no problem building version 1.4.1 myself.
But if I try to execute a release build from current master I run into the `Cannot find module electron-serve` error.
I'm not sure that electron-serve should really belong to devDependencies (other modules seems placed right).

As I said moving it to classic dependencies removes the error. But I still have a blank screen after that so there maybe is an other error.

Maybe a clue for the blank screen:
When I run `npm run dev:electron` the app works fine but when I close the window I have 2 errors:
`Could not load existing sourcemap of "node_modules/gltf-validator/gltf_validator.dart.js".`
`node_modules\handlebars\lib\index.js:18:39: Cannot statically evaluate fs argument`

Don't know if that can help you. Thanks for your previous replies :).

**Comment by donmccurdy** [comment]
Building release packages requires dev dependencies, by design — I’m not planning to change this part. If you’ve installed all dev dependencies and packaging still fails with a blank screen I can look into that.

**Comment by Tompote** [comment]
Of course I ran `npm install` before trying to package and I have no error during the packaging, just error during execution.
And I did exactly the same thing from a 1.4.1 branch and I have no error at all with building a release package and executing it.

**Comment by donmccurdy** [comment]
Ah, got it. Ok let me look into that.

**Comment by donmccurdy** [comment]
Moved the dependency over, and fixed another issue in the latest packaging script. Thanks!
