### ISSUE TITLE
model not loaded in localhost server

### ISSUE THREAD

**Issue by prabhupravan** [donmccurdy/three-gltf-viewer#183]
i am trying to view in wampserver but it showing the error,
Uncaught SyntaxError: Cannot use import statement outside a module  app.js.1

**Comment by donmccurdy** [comment]
@prabhupravan instructions for running the viewer locally are provided here: https://github.com/donmccurdy/three-gltf-viewer#web.

**Comment by prabhupravan** [comment]
thanks for the help its working fine in local,but i have an doubt on how to run the viewer from web, one of your comment (The script npm run build creates a bundle.js file that can be used if you want to host the app, as static files, on the web. That is only needed for deployment, as npm run dev does this automatically when files change.) i tried this but its not working well please help me out in this.
Thank you

**Comment by donmccurdy** [comment]
Which comment are you referring to, and what specific errors or problems do you see when it's "not working"? I will not be able to help you much without enough detail to reproduce the problem.

My deploy script is here:

https://github.com/donmccurdy/three-gltf-viewer/blob/9ef59abc24fbff84a5f0ce4413ca54a31ef11957/package.json#L19

That is doing `npm run build` and then uploading the contents of the `dist/` folder to my server. The other files are not needed for deployment.

**Comment by prabhupravan** [comment]
Thank you.. its working fine....
