### ISSUE TITLE
Stats do not show primitive count

### ISSUE THREAD

**Issue by lexaknyazev** [donmccurdy/three-gltf-viewer#185]
The template seems to be broken somehow:

![image](https://user-images.githubusercontent.com/3479527/73362378-24fdfa80-42c0-11ea-9fb0-d2e99dcda22e.png)

**Comment by donmccurdy** [comment]
@lexaknyazev it looks like `primitivesCount` [used to be in the report](https://github.com/KhronosGroup/glTF-Validator/issues/73#issuecomment-371662010), but isn't now. Was that intentionally removed? If there's a similar/newer property to use I can switch that over.

**Comment by donmccurdy** [comment]
`drawCallCount` looks as good or better, for my purposes, actually.
