### ISSUE TITLE
Morphing with Zophrac model from sketchfab is borked

### ISSUE THREAD

**Issue by danielmaciel** [donmccurdy/three-gltf-viewer#186]
Morphing with Zophrac model from sketchfab is borked.
The morphing animation is jumping in a weird way.
Check out the model at
https://sketchfab.com/3d-models/zophrac-9fea6ffd67b840cb970f5b4570794709
Kind regards,
Daniel

**Comment by donmccurdy** [comment]
The issue here is that the model has many morph targets (also called shape keys), and uses 30+ of them at the same time. Realtime engines typically support, at most, [4-8 active morph targets](https://gist.github.com/donmccurdy/4cad2039360fbd7cd55d18b3f0428581) at a time. The unsupported morph targets prevent the animation from playing smoothly.

**Comment by danielmaciel** [comment]
Aren't those about bone weights? Aren't morph target weights different?
If you watch this section of an Unreal Engine training, you will see they use 4 weights for the mouth movement alone. 
https://youtu.be/5wWGaJL_Q_8?t=2032
Even if that is the case and you don't want to support more morph target weights, it would help to avoid future bug reports if you add some kind of warning on the screen or on the logs explaining that there are too many morph target influences at once, right?

**Comment by donmccurdy** [comment]
Ah you're correct, sorry about that. I don't have a list of how many morph target weights the major engines support, but threejs supports 4-8, depending on whether the morph targets also have normals.

The underlying WebGL limits are the same for both morph targets and bone weights.... most devices [support only 16 vertex attributes](https://webglstats.com/webgl/parameter/MAX_VERTEX_ATTRIBS). Those 16 attributes are also allocated for other vertex data (positions, normals, tangents, UVs, colors...).

This tool shares any issues reported by glTF-Validator in the lower left hand corner — I've suggested the addition here: https://github.com/KhronosGroup/glTF-Validator/issues/135.
