### ISSUE TITLE
Group `ACCESSOR_VECTOR3_NON_UNIT` errors.

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-gltf-viewer#187]
For example:

Error | Message | Pointer
-- | -- | --
ACCESSOR_VECTOR3_NON_UNIT | Vector3 at accessor indices 192..194 is not of unit length: 0. | /meshes/0/primitives/0/attributes/TANGENT

https://sketchfab.com/3d-models/red-city-356c773c4b9a45d8b9d4aa04c60ecb27 results in 125,000 errors, which could be grouped for display.

**Comment by SeanLFL** [comment]
Out of curiosity, have you found a solution for this?

**Comment by SeanLFL** [comment]
Actually, try giving your mesh a basic auto unwrap. It fixed that issue for me

**Comment by dahuigeniu** [comment]
thankyou

**Comment by donmccurdy** [comment]
I originally filed the issue thinking of just rolling the errors into a smaller number of rows, versus showing what the glTF Validator itself reports. At this point I would probably point people to https://gltf.report/ instead, where I think i can do a better job of supporting those features.

If your model looks OK, I wouldn't necessarily worry about these errors in the model. If you *need* to fix them, then you could regenerate and/or normalize whichever vertex attribute causes the error. If it's tangents then glTF Transform can do that for you. This validation error is probably more helpful to people building a glTF exporter themselves.
