### ISSUE TITLE
THREE.GLTFLoader: Failed to load buffer bin file

### ISSUE THREAD

**Issue by bluce** [donmccurdy/three-gltf-viewer#190]
THREE.GLTFLoader: Failed to load buffer "BSL.bin".
Mac Version

**Comment by donmccurdy** [comment]
If you have a `BSL.bin` file, you will need to drag it into the viewer along with your `.gltf` file, or else put them both into a ZIP and load that. The `.gltf` file may contain references to `.bin` files or textures, and without those files this viewer cannot load it.

If you don`t have a `BSL.bin` file, then it seems that this model is missing a piece.

**Comment by bluce** [comment]
I put .bin and .gltf both files into zip,and Drag it into viewer, but viewer always loading!

<img width="620" alt="gltf" src="https://user-images.githubusercontent.com/1116610/77838773-6ff59a80-71a9-11ea-87b8-4569521abb15.png">

**Comment by donmccurdy** [comment]
That seems to be a bug, I'll have a look. In the meantime, dragging in a folder may also work — but unfortunately support for non-zip folders depends on the browser and operating system.

**Comment by bluce** [comment]
Thanks @donmccurdy

**Comment by bluce** [comment]
I drag the folder into viewer and it work

**Comment by raihanputerap** [comment]
is there a tutorial video that i can try? because i need to rename almost 200-250 gltf+bin files for my work haha, i export it to random name like "a,b,c, etc" to make yg progress faster when exporting and want to rename it after all finish exported.. but it cant so sad

**Comment by donmccurdy** [comment]
Seems like there are a few different questions that the earlier commenters might not be interested in -- could you open a question on https://github.com/donmccurdy/glTF-Transform/discussions?

Converting the glTF to GLB (glTF with all binary and texture resources embedded) might be the best option I think.

**Comment by Aarbel** [comment]
@donmccurdy did you found a way to give a gltf file solo without a bin file ?

**Comment by donmccurdy** [comment]
@Aarbel if the .gltf file contains a reference to a .bin file, then you must bring both into the viewer, there's no way around that. If the .gltf file doesn't reference a .bin file, then it should work just fine.

In general though, embedding binary data into a `.gltf` file is really awful. I strongly recommend using `.glb` instead if you want to have a self-contained file, it's far more efficient. If you want to have external resource files and human-readable JSON then `.gltf` is good for that.

**Comment by Aarbel** [comment]
thanks a lot @donmccurdy .

Do you know a tool to remove .bin references inside a gltf file ?

**Comment by donmccurdy** [comment]
You could open the file on https://gltf.report/ and then export from the right-hand panel. Or use a CLI:

```bash
npm install --global @gltf-transform/cli

gltf-transform cp in.gltf out.glb
```

**Comment by Aarbel** [comment]
it just need to remove bin references inside a gltf file, something like:
`gltf-transform cp in.gltf out.gltf --remove-bin-references`

**Comment by donmccurdy** [comment]
I'll emphasize again that I think it's a bad idea, the file size will go up and loading speed will go down. It's much better to use .glb if you don't want .bin references. But if needed, [gltf-pipeline](https://github.com/CesiumGS/gltf-pipeline) can do that:

```shell
npm install --global gltf-pipeline

gltf-pipeline -i in.gltf -o out.gltf
```
