### ISSUE TITLE
Manual see glb file

### ISSUE THREAD

**Issue by systemgvp2** [donmccurdy/three-gltf-viewer#193]
Hi,
I would like to add a button in the GUI that opens a glb file already present on the site, without having to use the "upload" button.

What function should I associate with the new button to open the "/file.glb" file?

**Comment by donmccurdy** [comment]
I'm not sure what you mean by "already present on the site." How would this button be different than the upload button that is already there? This site does not store any files.

**Comment by systemgvp2** [comment]
The button should load a file already present on the site, not manually entered by the user

**Comment by donmccurdy** [comment]
There are no files stored on the viewer site.

**Comment by systemgvp2** [comment]
I have add glb file when I've upload three-gltf-viewer on my web site

**Comment by donmccurdy** [comment]
The viewer will automatically load a model from a URL, if the server hosting the model is on the same origin or has CORS enabled, like this:

https://gltf-viewer.donmccurdy.com/#model=https://rawcdn.githack.com/KhronosGroup/glTF-Sample-Models/0c1ffd876136b824a50e584b9158a3199fead935/2.0/Avocado/glTF/Avocado.gltf

If you'd like to customize the code of this viewer you'll need to refer to the three.js documentation or use the three.js forums for help: https://discourse.threejs.org/

**Comment by systemgvp2** [comment]
thanks @donmccurdy
