### ISSUE TITLE
Objects with shared NLA tracks from Blender are strangely linked

### ISSUE THREAD

**Issue by j-conrad** [donmccurdy/three-gltf-viewer#194]
When two objects in a glTF have NLA tracks on them that are shared between them, the viewer exhibits strange behavior when attempting to toggle the various animations.

In the provided example file, Torus and Cube share an animation track in common called **TorusAction**.
If I check or uncheck either **TorusAction**, it automatically toggles the other **TorusAction**. But this does not always match up with what animations are actually playing in the 3d view. Sometimes both animations play, neither play, or only one or the other plays.

I'm not sure if there's a way for the viewer's UI to indicate which actions are on which objects, but that could be a start to understanding what's going on.

**I've included both the .blend and the .glb**

[AnimationExportTEST.zip](https://github.com/donmccurdy/three-gltf-viewer/files/4554731/AnimationExportTEST.zip)

**Comment by donmccurdy** [comment]
Looks like I've made some incorrect assumptions about `clip.name` being unique:

https://github.com/donmccurdy/three-gltf-viewer/blob/9ef59abc24fbff84a5f0ce4413ca54a31ef11957/src/viewer.js#L679-L688

... that said, using unique names is really a good idea across the board. Object3Ds/Meshes are also expected to have unique names for animation in three.js. I'm wondering if the exporter should be doing something to deduplicate these. 😕

**Comment by looeee** [comment]
Continuing the [discussion from discourse](https://discourse.threejs.org/t/fbx-model-scaling-bone-alignment-issue/18078/11). Here's the original FBX discussed there.

[ShineGreymon.zip](https://github.com/donmccurdy/three-gltf-viewer/files/5115936/ShineGreymon.zip)

Converted to glb with FBX2GLTF. There are multiple animation tracks with the same name. 

[chr776.glb.zip](https://github.com/donmccurdy/three-gltf-viewer/files/5115939/chr776.glb.zip)

>  I'm wondering if the exporter should be doing something to deduplicate these. 😕

In this case, we don't know the original exporter (something called Unity Studio, possibly). However, maybe FBX2GLTF should be de-duplicating names. That said, there's nothing I could find in the glTF spec that says duplicate names are forbidden, so maybe it's the responsibility of the loader/viewer to handle this? 

I've opened an issue on FBX2GLTF so let's see what they have to say: [FBX2glTF#273](https://github.com/facebookincubator/FBX2glTF/issues/273)

**Comment by donmccurdy** [comment]
Fixed in most recent release. ✅
