### ISSUE TITLE
Linux Desktop Documentation clarity

### ISSUE THREAD

**Issue by cgvirus** [donmccurdy/three-gltf-viewer#195]
Hello, thanks for this awesome app. Just to inform you in LInux:
We need to do:
```
    sudo chown root chrome-sandbox
    chmod 4755 chrome-sandbox
```
Before we can init the app. Which I believe would help Linux users for documentation purpose.

Thanks.

O/S:  Debian 10 Sid.

**Comment by donmccurdy** [comment]
I don't know Linux well, but that sounds kind of scary. :/ 
Do you happen to know if that's true of all Electron apps, or just this one?

**Comment by cgvirus** [comment]
Yes, the sandbox need 4755 access. Some discussion here:
https://unix.stackexchange.com/questions/543946/why-does-signal-desktop-require-4755-with-rootroot-on-chrome-sandbox

**Comment by donmccurdy** [comment]
Ok, thank you! I've added a note to the project README.
