### ISSUE TITLE
Lighting like in your viewer.

### ISSUE THREAD

**Issue by sampleuserthreejs** [donmccurdy/three-gltf-viewer#196]
Hello. I want to do the same lighting like in your viewer with that parameters: 
![image](https://user-images.githubusercontent.com/65442752/82114799-8494ee80-9767-11ea-9c3d-403817dc5396.png)

I copied all: ambient light, directional light, their intensity, outputEncoding and I copied your envMap, but in my project models are very dark. And in your viewer with that lighting my models look great. What should I copy too?
Thank you.

**Comment by donmccurdy** [comment]
The environment map is important, especially if your model's material has a non-zero metalness value. See:

https://github.com/donmccurdy/three-gltf-viewer/blob/8951899342532b9de2f89ba1341c8a293e0893f2/src/viewer.js#L443-L480

**Comment by Skriptach** [comment]
Hi @donmccurdy  I turned off `updateEnvironment` and my model still looks great in your viewer. Only outside walls become black. And inside light, texture and glossiness are fine. But when I try with my code it just completely black. Although light is turned off by default in your example too.

**Comment by donmccurdy** [comment]
Hi @Skriptach! You can see all the code there is to see in this viewer.  I'd recommend sharing your code in https://discourse.threejs.org/ and asking for help there, there are many more people to respond.
