### ISSUE TITLE
How to control lights included in gltf

### ISSUE THREAD

**Issue by LorenzWieseke** [donmccurdy/three-gltf-viewer#198]
Hi Don,
I'm trying to add some point lights inside blender and export them to glb but I don't know how to set up the strength and the radius to get the same results in your viewer. (Custom Distance is recognized though)

Where do I find those lights inside the viewer ?

I saw you disable the addLights when light is found in the glb file, so there are no lights in the viewer :

 this.content.traverse((node) => {
            if (node.isLight) {
                this.state.addLights = false;

In the contents childern the light is a simple "Object3D", so where can I change the properties of the light ?

![image](https://user-images.githubusercontent.com/29607121/83126595-530e1280-a0d9-11ea-8782-840d422cdcb1.png)

Thanks in advance

**Comment by donmccurdy** [comment]
Blender has an "Include -> Punctual Lights" option, have you enabled that when exporting?

I'm not sure if you're saying the lights are missing in the viewer, incorrect in the viewer, or correct in the viewer but incorrect in some other code.

**Comment by LorenzWieseke** [comment]
Sorry if my description was unclear. 
In Blender I have a point light and that is included in the glb (I enabled Include -> Punctual Lights) but that light is not added in the viewer lights.

![image](https://user-images.githubusercontent.com/29607121/83182123-246a5900-a126-11ea-880e-ba0bc8f538a8.png)

I can see it in on the screen but I wanted to know where to access it in the viewer object to access its properties ?

The second thing is that it's hard to get the same results in blender and in three js :

![image](https://user-images.githubusercontent.com/29607121/83183205-bcb50d80-a127-11ea-998d-e3ec400f0a44.png)

![image](https://user-images.githubusercontent.com/29607121/83183374-fab23180-a127-11ea-8a0e-3ad428dccf7a.png)

**Comment by donmccurdy** [comment]
I would expect the code you shared previously...

```
this.content.traverse((node) => {
  if (node.isLight) console.log(node);
});
```

... to find any lights contained by the model. The `content` object does not include lights added by the viewer itself, whereas `viewer.lights` does not include lights present in the model, and the lighter settings in the GUI do not affect lights present in the model.

As for consistency, do your lights appear correctly in https://sandbox.babylonjs.com/? If something doesn't match, it seems likely to be an issue in either the Blender addon or the three.js loader. This viewer does not alter three.js settings except to enable `renderer.physicallyCorrectLights = true`.

**Comment by LorenzWieseke** [comment]
No, babylon.js gives me the same result, so it might be the blender exporter, thanks for your help !

**Comment by donmccurdy** [comment]
Note that the 'custom distance' property is exported, but the 'radius' property is not — it's really meant for controlling shadows, which glTF doesn't deal with, but may be affecting the result you see in Blender all the same. I think a very small radius in Blender should give results that most closely match what you'll see after export.
