### ISSUE TITLE
Rendering mismatch between three-gltf-viewer and Blender

### ISSUE THREAD

**Issue by YTN0** [donmccurdy/three-gltf-viewer#201]
@donmccurdy I am working on integrating my own gltf loader into an engine I am working on. I have been trying various samples, which thus far have been generally ok (comparing to three and other viewers).

I came across one model which was posted in one of the gltf specification bugs / issues (don't remember which one). The model in question is attached. 

Firstly, this model does not render in a lot of online viewers (fails with an error). It used to also fail to load into Blender, but the latest Blender 2.83 seems to work.

The issue is that the rendered output from Blender does not match the output from three-gltf-viewer. Specifically, on the face of the model, the makeup around the eyes is different.

My engine more closely matches the Blender output. Mine is probably not 100% accurate since I don't have support for PBR (currently only Phong).

I had initially assumed that my rendered output was incorrect, but after viewing the Blender output, it looks like the three-gltf-viewer might be incorrectly rendering this. Also, you can see that the eyes are missing in the three version of the render.

I have attached screenshots from my engine, blender and three (in that order).

Let me know your thoughts on this.
[VRoidTwo.zip](https://github.com/donmccurdy/three-gltf-viewer/files/4790606/VRoidTwo.zip)

 
![My-Engine](https://user-images.githubusercontent.com/5132310/84861599-0ada7400-b037-11ea-9484-85761d714406.png)
![Blender](https://user-images.githubusercontent.com/5132310/84861607-1168eb80-b037-11ea-9810-b2dade549180.png)
![Don](https://user-images.githubusercontent.com/5132310/84861613-15950900-b037-11ea-8297-64f385d9662d.png)

**Comment by donmccurdy** [comment]
There are quite a few errors in this model, it doesn't pass the glTF validation suite: 

https://github.khronos.org/glTF-Validator/

So, the file itself is not a valid glTF 2.0 file. I think that's why a lot of viewers can't load it. Most importantly, the file extension should be `.glb` and not `.gltf` — it's a binary file. If you fix that you'll be able to see it in the babylonjs sandbox, which gives the same result as threejs:

![Screen Shot 2020-06-17 at 10 25 38 AM](https://user-images.githubusercontent.com/1848368/84929635-ef965580-b084-11ea-8a15-1ae34614e617.png)

Beyond that, I can't tell why this model renders as it does in Blender. The texture in the eye's highlight seems to be mostly transparent, but the material is marked as opaque? That might not be what you want here...

**Comment by donmccurdy** [comment]
From Blender:

![Screen Shot 2020-06-17 at 10 29 14 AM](https://user-images.githubusercontent.com/1848368/84930294-e3f75e80-b085-11ea-86cc-8ae71eec769c.png)

**Comment by YTN0** [comment]
@donmccurdy thanks for looking into this. I can't comment too much on the actual source file, since I copied it verbatim from the issue.

With regards to the rendered output, if there's a discrepancy between the texture and the material, I'd expect that per the spec, the behavior for how this should be interpreted would be consistent, and we should see the same output on all renderers.

Per the spec, the material alphaMode currently says "OPAQUE - The rendered output is fully opaque and any alpha value is ignored."

So I believe that that should take precedence over any alpha values set in the texture... But perhaps three might be interpreting it differently.

I'll play around with the source file more in blender to see what I can uncover.

Thanks.

**Comment by donmccurdy** [comment]
> So I believe that that should take precedence over any alpha values set in the texture... But perhaps three might be interpreting it differently.

The question then is, whether those 100% transparent pixels are technically black or white. I'm not sure how to find the answer to that...  I think you're likely right that there is a correct answer here according to the glTF spec, but it is a tricky case for engines (which support multiple formats) to handle. See https://github.com/mrdoob/three.js/issues/15483 for some related discussion, although I'm still not sure whether three.js or Blender is 'right' here. 

If it's possible to remove the transparency from that "OPAQUE" texture it would certainly be likely to simplify things. 😇

**Comment by donmccurdy** [comment]
Closing — I believe this is either related to https://github.com/mrdoob/three.js/issues/15483 in the renderer, or an issue in the Blender exporter, but I don't think it is related to this viewer. Sorry I can't be more specific than that. 😕
