### ISSUE TITLE
Transparent Background?

### ISSUE THREAD

**Issue by ruliusuifeng** [donmccurdy/three-gltf-viewer#206]
I need this background to be transparent, but I don’t know how to set it

**Comment by donmccurdy** [comment]
I'm not sure what you're asking, sorry. Is this a feature request for the viewer? Are you building your own three.js application? If you're using three.js you'll need to use the WebGLRenderer "alpha" property: https://threejs.org/docs/#api/en/renderers/WebGLRenderer

**Comment by ruliusuifeng** [comment]
> I'm not sure what you're asking, sorry. Is this a feature request for the viewer? Are you building your own three.js application? If you're using three.js you'll need to use the WebGLRenderer "alpha" property: https://threejs.org/docs/#api/en/renderers/WebGLRenderer

It works, thank you！
