### ISSUE TITLE
Nice tool but would be useful to view the gltf in front view to check alignment

### ISSUE THREAD

**Issue by SunbeamRapier** [donmccurdy/three-gltf-viewer#207]
Working in Blender is a fiddly business.  Sometimes a model can be incorrectly aligned.  It would be great to see some options to view the gltf in top/front/left/right views :-)

Stephen

**Comment by donmccurdy** [comment]
I think I'd rather not add new options for this, but if you include one or more cameras in the file when you export it from Blender, they'll be shown in a dropdown by my viewer.

**Comment by SunbeamRapier** [comment]
Cool!  I will check it out :-)

Thanks mate
