### ISSUE TITLE
Dropping a folder in does nothing useful

### ISSUE THREAD

**Issue by madmadman** [donmccurdy/three-gltf-viewer#209]
I want to quickly sift through a folder of gltf files and dropping a folder in just shows one model. Completely USELESS!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by donmccurdy** [comment]
This tool is meant to view a single model at a time. You can drop in a folder containing one model and it will show that model, but it doesn't load and browse multiple models. The code is open source, please feel free to make your own version doing whatever you need.
