### ISSUE TITLE
Environment enhancements

### ISSUE THREAD

**Issue by emackey** [donmccurdy/three-gltf-viewer#21]
Some feature requests to think about...

- [x] The default environment is "None", and most new users don't know to change this default.  PBR models that make good use of metallic surfaces look particularly bad in this environment.  Perhaps another environment, such as Park (Day), would be a better default?

- [x] Allow The model to be shown against flat gray, but reflecting an environment that is otherwise unseen.  Several PBR viewers/editors including Substance Painter actually use this mode as the default, as it allows the model to be presented with high-quality reflections, without the distraction of rendering the environment directly behind the model.

- [ ] Offer an option to rotate the environment.

**Comment by donmccurdy** [comment]
Thanks, these all seem like good suggestions! Will work on some of this soon.

**Comment by donmccurdy** [comment]
First two done; I don't see a clean way to do the third without implementing https://github.com/mrdoob/three.js/issues/11103, or putting everything into a wrapping group.
