### ISSUE TITLE
Venice Sunset Setting

### ISSUE THREAD

**Issue by Rizzist** [donmccurdy/three-gltf-viewer#212]
Hey! I had a try at your gltf viwer and a uploaded a model and it was extremely beutiful with the venice sunset setting, may I ask for lightning settings for it? Thank you!

**Comment by donmccurdy** [comment]
Hi! The HDR environment maps are available in https://github.com/donmccurdy/three-gltf-viewer/tree/master/assets/environment, and the original source is https://hdrihaven.com/hdri/?h=venice_sunset. If you're not sure how to load an HDR environment map (for image based lighting / IBL) see https://threejs.org/examples/?q=gltf#webgl_loader_gltf.

**Comment by donmccurdy** [comment]
The viewer also uses a bit of ambient and punctual lighting, which you can find in `viewer.js`, but that's a smaller part of the overall lighting.

**Comment by Rizzist** [comment]
Thank you so much bro!
