### ISSUE TITLE
[Feature Request] Publish to Homebrew as a Cask 

### ISSUE THREAD

**Issue by davemurphy** [donmccurdy/three-gltf-viewer#214]
hi @donmccurdy would you consider submitting this to Homebrew-Cask ??

**Comment by donmccurdy** [comment]
I'm not sure how that works. I've never published to homebrew before, and everything I've installed with homebrew has been a CLI tool rather than a GUI... Do you know of any examples of GUI tools published to Homebrew? Note that this would need to run via Electron.
