### ISSUE TITLE
Can performance be improved?

### ISSUE THREAD

**Issue by ivnnv** [donmccurdy/three-gltf-viewer#215]
Hi, first of all thanks for sharing the viewer.

Im loading [this model](https://clara.io/view/dbffdbab-17a9-4d5c-96c8-55fbbbea87d7), exported from .obj to .gltf using [this conversor](https://www.creators3d.com/online-viewer) and when I zoom some closely the model my FPSs drops from 60 to ~35.
Im using a mid-range laptop with just integrated Intel graphics but I can load more complex models in other browser apps or even some games like quake 3 in the browser with solid 60 FPS. Do you why is this happening and if theres any way to improve it?

**Comment by donmccurdy** [comment]
>  I can load more complex models in other browser apps or even some games like quake 3 in the browser with solid 60 FPS.

There are several different ways that a model can be "complex", size and vertex count are just one.

> when I zoom some closely the model my FPSs drops from 60 to ~35.

This likely means your GPU is having trouble rendering pixels quickly enough with the given PBR shader. It can be improved by:

1. Use a cheaper material shader.
2. Reduce viewport resolution.
3. Buy a fancier GPU.

Are you trying to optimize the model, to build a viewer of your own, or just to understand what's going on? Option (1) requires that you make changes to the model or to the viewing application. Option (2) can be done with viewer changes too, by rendering to a lower resolution and scaling it up. This viewer doesn't do any of those things, but it's built with three.js and someone could certainly build a similar three.js viewer that does some of this.

To optimizing a particular model for particular hardware is not a one-size-fits-all problem: popular games and game engines invest enormous amounts of time and money in making things perform well.

**Comment by ivnnv** [comment]
Well my point wasn't to optimise this exact model or trying to get a custom solution, and no, the [q3 in the browser implementation](https://github.com/toji/webgl-quake3) im talking about is far for being something optimised or even adapted to modern browsers and/or hardware.

Anyway thanks for the quick response, Ill try to convert models with the cheaper material shader path.
I have a fancier computer for testing even more complex models but for what Im doing Im only trying to build something for as many uses cases as possible.

**Comment by donmccurdy** [comment]
>  Ill try to convert models with the cheaper material shader path.

glTF basically has two material types: PBR and unlit. The default is PBR, and 3D engines can create faster or slower versions of a PBR material depending on their goals. Unlit is much more efficient, and works well for [stylized models](https://sketchfab.com/3d-models/cat-ctus-3e61b59e00844dbc87830ad3ccb598db), or with baked lighting. Baked lighting often requires a technical artist to prepare, though.
