### ISSUE TITLE
⬆️  Architecture rewrite in ES6

### ISSUE THREAD

**Issue by WestFR** [donmccurdy/three-gltf-viewer#217]
Hello all,

First of all thank you for the creator of this repository and to the contributors.

I used this repository to create my own 3D website, it largely takes over the functionality of this repository (at around 60-70%). I only implemented what I needed. This is my website : www.westfrstudio.fr

However, the idea is to offer you a re-architecture of this project to ES6 standards in order to facilitate future development and contributions. But before you jump into it, what do you think ?

If you are interested, I can invite you to my repository to see my current work.
Or make a proposal for a pull-request directly on this repository.

@donmccurdy @jeymichael @zellski @fernandojsg @funwithtriangles @tobocop2 @treyenelson @takahirox @ignazkevenaar

**Comment by donmccurdy** [comment]
Hi! Thanks for the offer, but I'm not currently interested in a re-architecture of this project. Note that the project does already use ES6 syntax throughout, though.
