### ISSUE TITLE
Add option customization in url

### ISSUE THREAD

**Issue by liudonghua123** [donmccurdy/three-gltf-viewer#221]
Now I can parse the url of `model` in location hash, and other three option (`kiosk`, `preset` and `cameraPosition`). Why not provide as many option as it can support. That would be nice and easy for customize the initial environment.

**Comment by liudonghua123** [comment]
I made a pull request to support this feature, now you can pass almost all support option in location.hash, like `#wireframe=true&skeleton=true&grid=true&bgColor1=#070000&bgColor2=#1827a5&textureEncoding=Linear&exposure=0.6&ambientIntensity=1.21&ambientColor=#364899&directIntensity=2.5&directColor=#b59608`

![image](https://user-images.githubusercontent.com/2276718/96847090-54bfe480-1485-11eb-940c-68568920641b.png)

**Comment by donmccurdy** [comment]
Hi! Thanks for the pull request, it's quite a nice and clean solution to support these different settings for embedded use.

Unfortunately, I am not comfortable supporting this much customization within the embedding URLs, though. Adding the options requires also continuing to support those options indefinitely — it takes work to ensure that all of the options continue to work the same way, and I don't have any way to reach out to users who have embedded the viewer warning them that one of these options might have changed. 

Please feel free to keep a fork of the viewer and make any changes that you need there. Or alternatively, https://modelviewer.dev/ could give you more customization options out of the box.
