### ISSUE TITLE
embed gltf

### ISSUE THREAD

**Issue by vladosvetlik** [donmccurdy/three-gltf-viewer#223]
Hi, I have been wondering, how to ebed gltf-viewr on my web. Like this:
https://gltf-viewer.donmccurdy.com/#kiosk=1&model=https://www.khronos.org/assets/gltf/BusterDrone.glb
So that I can show my models there.

thank you

**Comment by donmccurdy** [comment]
You can embed an iframe in your site, like:

```html
<iframe src="https://gltf-viewer.donmccurdy.com#kiosk=1&amp;model=https://www.khronos.org/assets/gltf/BusterDrone.glb"
  style="width: 100%;" height="400px" frameborder="0"></iframe>
```

To host other models of your own, you would need to find a static file host such as Google Cloud Storage, AWS S3, Netlify, etc. This viewer provides very little customization options when embedded, so if you need more control I would recommend something like modelviewer.dev/.

**Comment by vladosvetlik** [comment]
Hi and thank you very much.
It works with the drone model, but if I punch in different URL with glb model, it writes: 
"Unable to retrieve this file. Check JS console and browser network tab.Unable to retrieve this file. Check JS console and browser network tab." No idea whats wrong with it :(

**Comment by donmccurdy** [comment]
The most common reason for this is CORS errors, but you'd need to look in the browser's Developer Tools to confirm that. Websites like Dropbox and Google Drive host files in a way that people can download from, but other websites cannot. You'll need a hosting service that allows CORS. You can learn more about this at [Cross-Domain Requests with CORS](https://www.staticapps.org/articles/cross-domain-requests-with-cors/). The most common static hosting options for files like this are probably Amazon S3 or Google Cloud Storage; but I'm only familiar with the latter. Or things like Netlify or Vercel might be easier to learn.
