### ISSUE TITLE
About the display of the transparent map model

### ISSUE THREAD

**Issue by githubmzgg** [donmccurdy/three-gltf-viewer#227]
The transparent texture gltf model exported from 3dmax cannot be displayed normally. Does it support transparent texture?
![image](https://user-images.githubusercontent.com/38745620/100576823-d83ce300-3319-11eb-8f3b-5e14d5dd1c7f.png)

**Comment by donmccurdy** [comment]
This viewer does support transparent textures — do you get a different result on other viewers like https://sandbox.babylonjs.com/? And can you share the model you're having issues with? GitHub comments allow you to attach .ZIP  files.

**Comment by githubmzgg** [comment]
OK, It's same result on other viewers like https://sandbox.babylonjs.com.
[a tree.zip](https://github.com/donmccurdy/three-gltf-viewer/files/5614236/a.tree.zip)

**Comment by githubmzgg** [comment]
![image](https://user-images.githubusercontent.com/38745620/100579338-01ac3d80-331f-11eb-8ea9-dd5da9b96d70.png)
Add two lines of code and it's ok
![image](https://user-images.githubusercontent.com/38745620/100579417-30c2af00-331f-11eb-9fd6-0f77f16989f7.png)

**Comment by donmccurdy** [comment]
Hm, if the material needs `alphaTest` it should contain data that indicates this — three.js (the engine used here) would handle it automatically, if it did. This sounds like an issue with the 3DS Max exporter, so you may need to report an issue there.

In Blender, the name of this setting is "Alpha Clip", but I don't know the 3DS Max term for it...
