### ISSUE TITLE
Please update glTF-Validator to 2.0.0-dev.3.3

### ISSUE THREAD

**Issue by cx20** [donmccurdy/three-gltf-viewer#229]
This `glTF Viewer` currently uses `glTF-Validator` `2.0.0-dev.3.2`.
Since some glTF extension specifications have already been ratified, it is desirable to update the `glTF-Validator` as well.

**Comment by donmccurdy** [comment]
Updated!

**Comment by cx20** [comment]
Thank you for updating glTF-Validator.

BTW, the extension using `KHR_materials_variants` gives an `UNSUPPORTED_EXTENSION` warning. Is this because it is not yet supported?

For example, if you try to view the following model in glTF Viewer, you will get an `UNSUPPORTED_EXTENSION` warning.
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SheenChair/glTF-Binary
![image](https://user-images.githubusercontent.com/1833979/102091507-42996b80-3e62-11eb-8e4a-170a6269a4a8.png)

**Comment by lexaknyazev** [comment]
Yeah, that extension will be added in the next validator release.

**Comment by cx20** [comment]
@lexaknyazev Thank you for telling me. I would like to try again when the next version is released.
