### ISSUE TITLE
support for "KHR_materials_clearcoat", "KHR_materials_transmission", "KHR_materials_sheen"

### ISSUE THREAD

**Issue by rawwerks** [donmccurdy/three-gltf-viewer#233]
i love this resource. it would fantastic if it were updated to support the 3 new PBR extensions (https://gfxspeak.com/2020/12/03/physically-rendering-extensions/)

![image](https://user-images.githubusercontent.com/19483938/102730076-2ffeb680-42e8-11eb-96e4-77026d7648f1.png)

Left is is https://gltf-viewer.donmccurdy.com/ , right is https://sandbox.babylonjs.com/. 

Thank you!

**Comment by donmccurdy** [comment]
Hi! I believe `KHR_materials_clearcoat` is already supported (let me know if you have trouble with it!), but you're correct that the others are not yet. This viewer depends on three.js for rendering, and so three.js would need to add support for these extensions first. If you'd be interested in leaving an upvote there, I believe that https://github.com/mrdoob/three.js/issues/16977 is the relevant issue.

**Comment by cx20** [comment]
BTW, I think three.js `r131` supports `KHR_materials_transmission`.

**Comment by donmccurdy** [comment]
Just updated to r131 – should include transmission, volume, and IOR if I'm not mistaken. Sheen is still not really supported, but I'll close out this issue for now since there hasn't been movement on that in three.js for a while.

<img width="1306" alt="Screen Shot 2021-08-07 at 9 35 51 AM" src="https://user-images.githubusercontent.com/1848368/128603753-879a78b2-4ef7-4481-8424-efc385710e2c.png">

**Comment by cx20** [comment]
Thank you for updating to the latest version.
However, when I tried it, it seems that there is an error in the console.
https://gltf-viewer.donmccurdy.com/

```
app.js:1 
Uncaught SyntaxError: Cannot use import statement outside a module
```

Is it a problem with my environment?
Environment: Windows 10 + Chrome 92

**Comment by donmccurdy** [comment]
Ah, thanks! Should be fixed now.

**Comment by cx20** [comment]
Thank you for the quick fix. I think it's okay now.
[glTF Viewer + Duck.gltf(use Transmission extension) result:](https://gltf-viewer.donmccurdy.com/#model=https://rawcdn.githack.com/cx20/jsdo-static-contents/525dacce76429f469762e746a7d4c002d33ea2a2/models/gltf/2.0/Duck/glTF_TransmissionTest/Duck.gltf)
![image](https://user-images.githubusercontent.com/1833979/128608765-78205398-46d9-48cd-9603-2f8b77939346.png)
