### ISSUE TITLE
Electron packager does not work???

### ISSUE THREAD

**Issue by prenex** [donmccurdy/three-gltf-viewer#234]
I follow README.md for creating packages, but only some of them gets created and really rarely - not always generates executable packages! I tried troubleshooting what is going on and tried on both arch linux and win10.

On arch(64) linux this is what I get:

```
[prenex@magosit-laptop three-gltf-viewer]$ DEBUG=electron-packager electron-packager . gltf-viewer --overwrite --asar --platform=linux --arch=x64 --icon=assets/icons/glTF-Viewer.png --out=package
  electron-packager Electron Packager 15.2.0
  electron-packager Node v15.4.0
  electron-packager Host Operating system: linux 5.9.14-arch1-1 (x64) +0ms
  electron-packager Packager Options: {"_":[".","gltf-viewer"],"overwrite":true,"asar":true,"platform":"linux","arch":"x64","icon":"assets/icons/glTF-Viewer.png","out":"package","deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":".","name":"gltf-viewer","protocols":[]} +1ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /home/prenex/munka/asynth/three-gltf-viewer/package.json +0ms
  electron-packager Inferring target Electron version from electron in /home/prenex/munka/asynth/three-gltf-viewer/package.json +2ms
  electron-packager Application name: gltf-viewer +7ms
  electron-packager Target Electron version: 7.3.3 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"linux","arch":"x64","version":"7.3.3","artifactName":"electron"} +0ms
Packaging app for platform linux x64 using electron v7.3.3
  electron-packager Creating /tmp/electron-packager/linux-x64-template +87ms
  electron-packager Extracting /home/prenex/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv7.3.3electron-v7.3.3-linux-x64.zip/electron-v7.3.3-linux-x64.zip to /tmp/electron-packager/linux-x64-template +1ms
  electron-packager Initializing app in /tmp/electron-packager/linux-x64/gltf-viewer-linux-x64 from /tmp/electron-packager/linux-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/home/prenex/munka/asynth/three-gltf-viewer/package' ] +3s
  electron-packager Running asar with the options {} +962ms
[prenex@magosit-laptop three-gltf-viewer]$ ls -lat ./package
összesen 12
drwxr-xr-x  3 prenex prenex 4096 dec   21 09.32 'glTF Viewer-darwin-x64'
drwxr-xr-x  3 prenex prenex 4096 dec   21 09.32  .
drwxr-xr-x 12 prenex prenex 4096 dec   21 09.29  ..
-rw-r--r--  1 prenex prenex    0 dec   21 09.09  .gitkeep
[prenex@magosit-laptop three-gltf-viewer]$
```

I only run manually because I just installed electron-packager globally and ran what is in the package.json to try troubleshooting the situation better. When I run `npm run package` all I get is very minor logging  (even less than here) and on linux ther darwin executable is usually created but none of the others.

When I try **on windows, it randomly creates packages for win and linux** but most of the time packaging silently fails just like the above.

Is there anything I can do for better troubleshooting? How does this work at all?

PS.: My goal is to change your app to be able to show models when provided by command line parameters and such. Will be run not as a web page. For this I have hard times developing my code as 9/10 times packaging does not work and even then I can package only on my windows box. I would happily use something else, like electron-builder (plan to use it anyways, because I need "portable" executables by putting everything into one file and I have succesfully made one such previously in that way here, that I used eletron-packager, then on its result I configured electron-builder. My huge problem that this only works 1/10 of the times, because the electron-packager used to fail which makes testing command line arg parsing an extremely hugely time-wasting task. I tried to use "only electron builder" without using what you already do with the packager, but I cannot set it up properly. Then I disabled asar to be able to compare what should be in package and was never yet able to get it to work.... I am sure this can be packaged and have no idea why it is so complex... I am new to node.js btw so likely I do something bad, but tried to follow all the docs available.

**Remark: The above commandline result is when I run from latest git version (6cab5cf4) without any of my changes so it is not my argument handling code that fails packaging!**

**Remark: npm run dev:electron always work on both machines - just problem with packaging...**

**EDIT: If I leave out "--asar" on my linux box chances are much more higher that it works through the process. [maybe always?]**

Might do the process in that way that I develop on linux and use wine for packaging there if it will work, but still seems like there is some issue. Can I add something to "DEBUG" env var to get more information about asar-related errors?

**Comment by donmccurdy** [comment]
Sorry, I don't think I know how to reproduce the problem you're seeing. I don't know very much about Electron, I've just been using it to publish the pre-built packages here: https://github.com/donmccurdy/three-gltf-viewer/releases/tag/v1.5.1.

> I only run manually because I just installed electron-packager globally and ran what is in the package.json to try troubleshooting the situation better. 

This might be part of the problem, since `package.json` specifies particular versions of Electron and a global install might use something else. 

> PS.: My goal is to change your app to be able to show models when provided by command line parameters and such

Do you necessarily want to launch an interactive Electron app, or just take a screenshot? Something like [electroshot](https://github.com/mixu/electroshot) might be easier for screenshots. Filament also has a native glTF viewer that can be launched from a CLI. Or Blender can be launched from the commandline.

**Comment by prenex** [comment]
I figured leaving out the "asar" thing just works. Also I dropped the idea of using the "portable" executables that package everything into a single exe because it adds further seconds to the app startup time.

I know various gltf viewers or can write my to start from the terminal, but part of why I did it this way is because this is a 3dsmax plugin with gltf (and other propriately formats) I/O and I want two things:

- A realy wysiwyg gltf preview - including bugs in threejs, like not caring the gltf says which channel the albedo is and wanting channel 0 always. Also we are usually are affected by bugs of our models having different channels with different tiling/repeat settings not always picked up by threejs default importer on the web app side. Also because the whole thing goes through the bowels of max instead of just being a command line conversion I have a pretty amount of bugs from that too and like here and there our own code bugs too. Considering all the pipeline we need to test, this is "the most wysiwyg" way except if we would upload to servers and our own app would do the same...
- A bulk testing / conversion. Where we convert previous models into new format by bulk and getting statistics how many models are affected from which bug and see if we need to create more complex solutions. Currently I always fix and work around subtle bugs but do not know how many models are affected in real life.

The reason why I use your viewer is because it uses threejs and our app uses that too for which the models are, but your viewer is much smaller than our big web app so easier to put into electron and this is much faster than trying to replicate the threejs shaders from c++ plugin code just because it would feel "more professional" - also maintaining this will be easier likely :-) 

Btw now both the build and screenshots work. Also I added command line parameter handling when built as electron app so one can provide if they want screenshot, validation in csv, autoclose and of course the local file to open.

Thanks for your suggestions, I am answering mostly so that anyone else who ever face the issue knows that turning off the asar thingy always fixed it for me.

PS.: I would never launch blender from a max plugin as max people would go crazy haha. I love Blender, but some of them hate haha

**Comment by donmccurdy** [comment]
I see! Another option I use sometimes is `<model-viewer>` (https://modelviewer.dev/), which also renders with three.js. This snippet loads a list of models from a JSON file and displays _all_ of them, before/after, on the same page. It takes a bit to load but is nice for testing pipeline changes. :) 

https://github.com/donmccurdy/glTF-Transform/blob/c0f5e0e9983dfa3bda71dd3687d762422b71ac17/test/index.html#L34-L57

<img width="740" alt="Screen Shot 2021-01-04 at 11 33 06 AM" src="https://user-images.githubusercontent.com/1848368/103562392-deb9ff80-4e6f-11eb-8ffb-22fba1b25714.png">
