### ISSUE TITLE
Animation show error.

### ISSUE THREAD

**Issue by neciszhang** [donmccurdy/three-gltf-viewer#235]
Hello
Thank you to provide the tool by show gltf file. 
I use this tool, but show error.Animation is deformation.
This is the gltf file.Could you help me to look this question?Thanks a lot.
[9.gltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/5763571/9.gltf.zip)

**Comment by neciszhang** [comment]
I use this website [https://gltf.insimo.com/](url) to view this gltf. It's correct. Oh. =.= This website use your source code.

**Comment by donmccurdy** [comment]
What deformation do you see? The difference I see is that the stars are rotated about 90º. I'm seeing the same results in:

- https://gltf-viewer.donmccurdy.com/
- https://sandbox.babylonjs.com/
- https://playcanvas.com/viewer
- Blender

It's likely that https://gltf.insimo.com/ is incorrect, and that the model is not exported correctly from C4D. If C4D gives an option of baking keyframes that might also help.

**Comment by neciszhang** [comment]
@donmccurdy Thank you very much! The animator re-exported the model to me, and it showed it well.
[star_Draco.gltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/5769539/star_Draco.gltf.zip)
