### ISSUE TITLE
Bad animation loop

### ISSUE THREAD

**Issue by mrdoob** [donmccurdy/three-gltf-viewer#24]
I've modified locally the viewer to get the animations play 10x slower by doing:

```js
const dt = (time - this.prevTime) / 1000 / 10; 
```

Here's how the flamingo from https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/48 looks like:

https://drive.google.com/file/d/0B6qxNbhuunW8X1hRSXdqb1haN28/view

[flamingo.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1163564/flamingo.zip)

**Comment by donmccurdy** [comment]
I'm seeing something different when viewing that model. 🙁

[flamingo.mov.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1163675/flamingo.mov.zip)

It looks like the morph targets are all inverted along one axis, compared to the non-morphed positions? But in your clip I just see some snags in the animation, and no inversion...

**Comment by mrdoob** [comment]
Actually, it may be an exporter issue... https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/48#issuecomment-316845946

**Comment by mrdoob** [comment]
It was an exporter issue.
