### ISSUE TITLE
Mac trackpad zooming

### ISSUE THREAD

**Issue by crclwcca** [donmccurdy/three-gltf-viewer#240]
My customer is using a Mac trackpad. She can rotate the model in the donmccurdy viewer - But how can she zoom?
Great online viewer by the way.

**Comment by donmccurdy** [comment]
Hi! Zooming works by scrolling — on my (2012 Macbook Pro) mac trackpad that requires moving two fingers vertically up or down the trackpad. Hope this helps. :)
