### ISSUE TITLE
my file does not work properly on your viewer 

### ISSUE THREAD

**Issue by ramifara** [donmccurdy/three-gltf-viewer#247]
for some reason, this file from the link below shows up incredibly massive, and I can not pan or zoom out to see it properly. 

https://1drv.ms/u/s!Ak3PsW6mXj90mb065EHoi0dPhTQQjA?e=ubgvOt

**Comment by donmccurdy** [comment]
I think this is the same issue as https://github.com/donmccurdy/three-gltf-viewer/issues/147 – the file is OK, but by viewer cannot compute a bounding box for it correctly because of the large skinning transform. This happens sometimes, particularly with models converted from FBX -> glTF somehow.
