### ISSUE TITLE
Shaders not loading in web based viewers

### ISSUE THREAD

**Issue by parassrivastav** [donmccurdy/three-gltf-viewer#251]
I had a fbx which I converted into glb using fbx2gltf npm package then compressed it using

_gltf-pipeline -i model.glb -o modelDraco.glb -d_

The file appears in blender with shaders etc like following
![image](https://user-images.githubusercontent.com/43533372/112601534-94c23380-8e38-11eb-92a2-7630d0d7d03c.png)
 but not in https://gltf-viewer.donmccurdy.com/ or https://sandbox.babylonjs.com/ where it appears as following, without shaders n all.
![image](https://user-images.githubusercontent.com/43533372/112601710-c6d39580-8e38-11eb-856e-f0fa59d7ef31.png)

Here's the glb file
https://drive.google.com/file/d/1E9Y7DbZCxoWiFJlhjlx8WDm2nbNhJRHT/view?usp=sharing

**Comment by donmccurdy** [comment]
Are you using the ` --khr-materials-unlit` flag with FBX2GLTF? The result you're seeing in the second image is correct, given this GLB, because the entire model is specified as "unlit". This means shading is disallowed.

**Comment by donmccurdy** [comment]
Continuing in chat: https://chat.stackoverflow.com/rooms/230422/discussion-between-paras-and-mugen87.

**Comment by parassrivastav** [comment]
Removing --khr-materials-unlit flag has made it better but the glasses are still not transparent.
![image](https://user-images.githubusercontent.com/43533372/112714367-02856280-8f00-11eb-89f0-7d6b271ab7d8.png)

**Comment by donmccurdy** [comment]
The glTF viewers are displaying the GLB correctly, based on what's in the GLB. 

Since this is a problem with what the FBX2glTF exporter as written into the GLB file, you will need to share the original FBX file to get help with this, or work with a 3D artist to edit the file in modeling software.

**Comment by parassrivastav** [comment]
I shared the original fbx, can you help ?

**Comment by donmccurdy** [comment]
Loading this FBX file in Autodesk FBX Review, I see:

![Screen Shot 2021-03-29 at 10 12 12 AM](https://user-images.githubusercontent.com/1848368/112874212-82820880-9077-11eb-917d-bd19145b12b6.png)

Importing the FBX file directly to Blender, I see:

![Screen Shot 2021-03-29 at 10 13 39 AM](https://user-images.githubusercontent.com/1848368/112874248-8b72da00-9077-11eb-8522-5998f75282b4.png)

In neither case are the windows transparent, so I think it's safe to say this FBX file has some problems. You'll need to fix those manually in Blender (or other software) and set **Blend Mode** -> **Alpha Blend** on the windows' material:

![Screen Shot 2021-03-29 at 10 15 19 AM](https://user-images.githubusercontent.com/1848368/112874646-05a35e80-9078-11eb-9278-6228d9e8ce57.png)

With that done, and then exporting to GLB, you can view it in three.js correctly. You may want to adjust the **Alpha** slider a bit.

![Screen Shot 2021-03-29 at 10 16 28 AM](https://user-images.githubusercontent.com/1848368/112874685-1522a780-9078-11eb-8eef-3168d3c96512.png)
