### ISSUE TITLE
how to make product so that it can view in your gltf viewer 

### ISSUE THREAD

**Issue by sumsrk** [donmccurdy/three-gltf-viewer#253]
please please help me out how to prepare a model so that it can view in gltf viewer .... I have made the model in 3ds max ....

**Comment by donmccurdy** [comment]
Hi, sorry I am not a 3DS Max expert at all. You will need to export your model to the glTF (`.gltf` or `.glb`) format. A plugin is available to export from 3DS Max, described here:

https://doc.babylonjs.com/extensions/Exporters/3DSMax_to_glTF

If that isn't working for you, bringing the model into Blender (https://www.blender.org/) and then exporting to glTF is also a very popular choice.
