### ISSUE TITLE
Using Instances / Static Batching

### ISSUE THREAD

**Issue by LorenzWieseke** [donmccurdy/three-gltf-viewer#254]
Would it be possible to make use of instances to optimize performance ? Having a lot of similar assets would result in loading the vertices only once and instance them multiple times. In those scnes we would get a big performance boost.

Another perfomance question, would it be usefull to merge static geometry to save drawcalls ?

I had a look at these descussions and tried to implement my own (using BufferGeometry Utils) but wasn't able to remap materials to the joined mesh afterwards.

[](https://discourse.threejs.org/t/how-can-i-increase-fps-after-loading-this-glb-model/9237/4)

[](https://discourse.threejs.org/t/tesseract-open-world-planetary-engine/1473/9)

**Comment by donmccurdy** [comment]
If you're building an experience using three.js (which this viewer is based on) then this thread will have some suggestions on how to optimize things:

https://discourse.threejs.org/t/three-scene-optimization-texture-size-calculation-in-gpu-compression-merge-meshes-what-the-limits/23972

This viewer loads files with THREE.GLTFLoader and does not do any further processing. Some optimizations can be made "offline" to your glTF files, others might need to be implemented in three.js code.

**Comment by donmccurdy** [comment]
Hm i guess that thread focuses more on texture optimization than draw calls, but there are other threads about instancing and/or merging meshes in the forums as well. gltfpack is a good tool to start with here.
