### ISSUE TITLE
Threejs GLTF file problem

### ISSUE THREAD

**Issue by GabrielAnkar** [donmccurdy/three-gltf-viewer#258]
I have a custom blend file exported to GLTF format. The file doesnt show up when i load it in GLTFLoader in Vscode. I tried some other files and they worked fine. Is my file too large or are there too many vertices? currently at 14690608 vertices and about 500mb big.
Please help!

**Comment by donmccurdy** [comment]
This repository is just the code and issue tracker for the website https://gltf-viewer.donmccurdy.com/, but it sounds like you're having trouble with VSCode? If your model does not load in several other viewers ...

- https://gltf-viewer.donmccurdy.com/
- https://sandbox.babylonjs.com/

... then it's probably too large or complex for your machine, especially on a web-based viewer. Number of vertices, and number and size of textures, can both cause this issue. 500MB is certainly a lot for the web, you may want to decimate the mesh in Blender and/or reduce texture resolution to at most 4K, preferably <=2K.

If the issue is _only_ occurring in VSCode, you may ant to report the problem here: https://github.com/AnalyticalGraphicsInc/gltf-vscode

**Comment by GabrielAnkar** [comment]
Thank you very much!

________________________________
Från: Don McCurdy ***@***.***>
Skickat: den 30 juni 2021 19:58
Till: donmccurdy/three-gltf-viewer ***@***.***>
Kopia: GabrielAnkar ***@***.***>; Author ***@***.***>
Ämne: Re: [donmccurdy/three-gltf-viewer] Threejs GLTF file problem (#258)


This repository is just the code and issue tracker for the website https://gltf-viewer.donmccurdy.com/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgltf-viewer.donmccurdy.com%2F&data=04%7C01%7C%7C159fbd9397144285457308d93bf0a986%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637606727100960411%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ipVDbyV5pxqupjPDYdmx5%2BiyHuZuXKKsKA3ZiVmCf88%3D&reserved=0>, but it sounds like you're having trouble with VSCode? If your model does not load in several other viewers ...

  *   https://gltf-viewer.donmccurdy.com/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgltf-viewer.donmccurdy.com%2F&data=04%7C01%7C%7C159fbd9397144285457308d93bf0a986%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637606727100970406%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=mXOUVkEAKF7AwBnyYO0RoabbUPlywyE6XPCf%2BWAUkGM%3D&reserved=0>
  *   https://sandbox.babylonjs.com/<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsandbox.babylonjs.com%2F&data=04%7C01%7C%7C159fbd9397144285457308d93bf0a986%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637606727100980395%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u0bmQOZdIiW7vBzaVjg7vZrfo8NaMdS0p1ynuBJq9RE%3D&reserved=0>

... then it's probably too large or complex for your machine, especially on a web-based viewer. Number of vertices, and number and size of textures, can both cause this issue. 500MB is certainly a lot for the web, you may want to decimate the mesh in Blender and/or reduce texture resolution to at most 4K, preferably <=2K.

If the issue is only occurring in VSCode, you may ant to report the problem here: https://github.com/AnalyticalGraphicsInc/gltf-vscode<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticalGraphicsInc%2Fgltf-vscode&data=04%7C01%7C%7C159fbd9397144285457308d93bf0a986%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637606727100990391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eXXGTA5Oud3h4z5TxWs7Kb2%2FhaCcWVWQEn%2Fpvgqkoy4%3D&reserved=0>
