### ISSUE TITLE
Apply Modifier Disables Morph Target GLTF

### ISSUE THREAD

**Issue by mirrormefashion** [donmccurdy/three-gltf-viewer#259]
I created an animation in Blender (v 2.9) that uses a mirror modifier. On export of that image as a GLTF I selected apply modifiers so that the mirrored half of my object shows up. However, doing this caused me to lose my morph targets. See the attached two images. They are the same image, the only difference is that one file has 'apply modifier' selected. This is a major issue for me since I require the mirrored half of my image. Hope this is helpful info. 
![w_modifier](https://user-images.githubusercontent.com/46505853/125841677-58cfa41d-b835-40a3-9105-2c309c0ad7e7.png)
![wo_modifier](https://user-images.githubusercontent.com/46505853/125841678-2eaa6d50-058d-4247-91af-2437499a06cc.png)

**Comment by donmccurdy** [comment]
Could you check whether the same issue occurs when viewing this model in https://sandbox.babylonjs.com/? If so, it is likely a problem in the model itself, and asking on Blender's Stack Exchange may be the way to go. I see https://blender.stackexchange.com/questions/230695/morph-targets-w-modifiers-gltf-file, that is your question too? Posting a `.blend` there might also help people to debug it.

If it seems to be a bug in the Blender exporter, filing an issue at https://github.com/KhronosGroup/glTF-Blender-IO may also help.

**Comment by mirrormefashion** [comment]
No, this issue does not show up in Sandbox. Yes, that was my post on
StackExchange. I'll try to create another model that I can share as a blend
file.
As a fix - I wasn't able to get an answer - I'm redoing my model without
the modifier. I'll check back for a solution later. Thanks for your reply
and best wishes moving forward! ~Bella

**Comment by donmccurdy** [comment]
I don't think I'm able to help advise on this one without a `.blend` to debug sorry, not sure how to guess whether the problem is in Blender, the animation setup, or three.js. Best of luck, and happy to take a closer look at the file if that's helpful.

**Comment by mirrormefashion** [comment]
Give me til Monday and I'll send you the file. I'm swamped and can't move
any quicker. I resolved the issue myself by re-doing my model without the
mirror modifier but since other people seem to have similar issues I'll
send my file to help...hopefully. Have a great weekend, until later. ~Bella
