### ISSUE TITLE
Drag folders into web page doesn't work as expected

### ISSUE THREAD

**Issue by samwei12** [donmccurdy/three-gltf-viewer#26]
![](https://user-images.githubusercontent.com/12758352/28497518-f304cc80-6f4e-11e7-89dc-7658cb6365fb.png)

see [https://github.com/mrdoob/three.js/issues/11812#issuecomment-317265648](https://github.com/mrdoob/three.js/issues/11812#issuecomment-317265648)

**Comment by donmccurdy** [comment]
Thanks @samwei12  - what OS and browser are you using?

**Comment by samwei12** [comment]
1. Mac 
2. 10.13 beta3
3. Chrome 59

**Comment by donmccurdy** [comment]
Hm I'm using Chrome 59 too, except not the macOS beta... Do you see any errors in the JS console, when the page loads (before you drop in the folder)?

**Comment by samwei12** [comment]
No, but after I copy your code into a blank web project, it works well

**Comment by donmccurdy** [comment]
Any better now? I still can't reproduce the problem on my machine, but have added support for .ZIP archives too.

**Comment by samwei12** [comment]
1. No, 
2. After I upload a zip file, nothing happens.

**Comment by donmccurdy** [comment]
Unfortunately I can't reproduce this problem. If you're still having the same problem, could you share the model you're trying to view? You can drag .ZIP files into GitHub comments.
