### ISSUE TITLE
gltf-viewer on localhost

### ISSUE THREAD

**Issue by faridehgalexi** [donmccurdy/three-gltf-viewer#266]
I have a .gltf model which I want to access its blendshapes for motion capture; therefore, I wanted to know whether there is a way to locally use the code to access the blendshapes on my computer and build on top of the code?
I tried to zip download the file and open run it using VScode, however, there is no link to three.js, and when I change the directories to local models I receive many errors.

**Comment by donmccurdy** [comment]
You can run this locally with the quickstart instructions here:

https://github.com/donmccurdy/three-gltf-viewer#quickstart
