### ISSUE TITLE
Greetings from a fellow Blender Artist

### ISSUE THREAD

**Issue by Calpgrmr** [donmccurdy/three-gltf-viewer#267]
This viewer is so useful!!

This is Lee. I created him in MakeHuman. He has face shapes/drivers, so he can talk.

Your viewer shows them - and they work. 

How do you do that in the code?

Thanks. Cal

![howGet](https://user-images.githubusercontent.com/90064737/132957143-a1c30710-4326-4012-ba8e-251944081be2.jpg)

**Comment by donmccurdy** [comment]
Thanks @Calpgrmr! 

This viewer is written with [three.js](https://threejs.org/), and the UI uses [dat.gui](https://github.com/dataarts/dat.gui). You can find a nicely simplified example of the same thing in the three.js website's examples section, with self-contained source code (click the source button in the bottom right) —

https://threejs.org/examples/?q=skin#webgl_animation_skinning_morph

**Comment by Calpgrmr** [comment]
So,... I "borrowed some of your code and GOT THE MORPH CONTROLS WORKING on a page of mine!!!

Fantastic!!
