### ISSUE TITLE
Nice, and a suggestion on alpha cutouts

### ISSUE THREAD

**Issue by erich666** [donmccurdy/three-gltf-viewer#268]
This viewer works fairly well. It does have a problem with cutout images, evidently turning off the z-buffer when these are rendered. I recommend a "clamp" shader that draws to the z-buffer when the alpha test is greater than say 0.01. See https://stackoverflow.com/questions/24302152/opengl-alpha-test-how-to-replace-alphafunc-deprecated/24312267 for example.

Here's what it looks like in the viewer:
![image](https://user-images.githubusercontent.com/803995/134987591-db05239a-fc1c-43fb-a97d-b22ef62e7210.png)

Here's what's expected:

![image](https://user-images.githubusercontent.com/803995/134988055-e79fe146-1cc4-4b14-a126-c03f7af536e1.png)

Here's the test file set:
[azalea_test.zip](https://github.com/donmccurdy/three-gltf-viewer/files/7239413/azalea_test.zip)

Model downloaded from here: https://skfb.ly/o7xsS

Best of luck figuring out a solution and keep up the nice work!

**Comment by donmccurdy** [comment]
Hi Eric! glTF identifies alpha cutout and alpha blending as two distinct "modes", and in this case the material itself selects alpha blending. The z-buffer is turned off only in that case, and won't be disabled where alpha cutout is indicated. 

I guess that's probably an issue in the Sketchfab download, but a quick way to diagnose and fix would be:

1. Open model on https://gltf.report/
2. Check material settings:
![Screen Shot 2021-09-27 at 2 43 03 PM](https://user-images.githubusercontent.com/1848368/134989906-5f952c36-0097-4694-9b6f-f08f7cdf7e56.png)
3. Convert to "MASK" mode in script panel:
```js
for (const mat of document.getRoot().listMaterials()) {
	if (mat.getAlphaMode() === 'BLEND') {
		mat.setAlphaMode('MASK')
		   .setAlphaCutoff(0.01);
	}
}
```

Result:
![Screen Shot 2021-09-27 at 2 47 19 PM](https://user-images.githubusercontent.com/1848368/134989966-a7c40168-45fb-4760-a643-64b8053b6ae5.png)

**Comment by erich666** [comment]
Ah, thanks, sounds like a Sketchfab bug, or one where I (I maintain Mineways) need to hint them more as to whether the texture is applied as a cutout or as opacity - I'll try reporting it to them.

Yeah, if it's opacity, you then have to deal with the usual z-buffer limitation that rasterization has. Some decade we'll all be ray tracing everything and it won't then matter. :)

**Comment by donmccurdy** [comment]
I'm almost positive I have seen a model from Sketchfab that did use alpha cutout, so I do think there's a way... no idea what that would be though sorry!
