### ISSUE TITLE
Exposure parameter seems to do nothing

### ISSUE THREAD

**Issue by j-conrad** [donmccurdy/three-gltf-viewer#269]
Just noticed that the 'exposure' slider has no effect on the model or background. I remember this working at some point so I'm not sure when it stopped.

![image](https://user-images.githubusercontent.com/31968496/136454174-0ef9b1b1-0af3-4079-8dc0-951857d578c4.png)

OS: Windows 10
Browser: Firefox 93.0 64-bit

**Comment by GFialho** [comment]
Hey, I think that we need to set a toneMapping for the exposure to work, try adding this code after toneMappingExposure:

   ` this.renderer.toneMapping = LinearToneMapping`

and import LinearToneMapping from three

**Comment by donmccurdy** [comment]
Thanks, fixed in f656ab26920ebc0109b9b50d218caea89bde0522 !
