### ISSUE TITLE
can we get a recording or GIF exporter?

### ISSUE THREAD

**Issue by vznjpeg** [donmccurdy/three-gltf-viewer#274]
would be helpful when uploading 3D previews

**Comment by donmccurdy** [comment]
Hi! It's certainly a useful idea, but beyond the scope I have plans of supporting in this viewer.

If someone were interested in building something like this, I might suggest starting with [Model Viewer](https://modelviewer.dev/). It has [methods to export screenshots](https://modelviewer.dev/docs/#entrydocs-loading-methods-toBlob) that could be called repeatedly and then assembled into a GIF or video. Some work already exists to use Model Viewer for generating screenshots from a CLI, as well: https://github.com/Shopify/screenshot-glb.
