### ISSUE TITLE
option to display black wireframe on main model

### ISSUE THREAD

**Issue by jlp1528** [donmccurdy/three-gltf-viewer#277]
I am working on a project dealing with various polyhedra. In this particular application, the wireframe option could be used to make edges more clear on complex shapes, but currently checking wireframe turns off display of the main model. Is it possible to display a completely black wireframe with the main model to serve as edges for clarity?

**Comment by donmccurdy** [comment]
Hi, thanks for opening this issue. I don't think additional display modes (like an overlay wireframe) would be within the scope I want to support on this viewer. I'd like to keep the viewer pretty simple, both to keep it an easy-to-understand example of using three.js, and also to have time to work on other things. You can certainly set up an overlay wireframe in a custom viewer though using three.js though.
