### ISSUE TITLE
exporting the mixamo character with armature without any animation as glb file.

### ISSUE THREAD

**Issue by streak17** [donmccurdy/three-gltf-viewer#280]
I was trying to export a mixamo character as glb file to use in three.js for a project. but I am unable to do it.
I can't see the skeleton after enabling the skeleton in gltf viewer and also the scale is changed of the character.

below are the image of blender 

![blender](https://user-images.githubusercontent.com/75874364/148341378-1afc3e5d-5a0b-4737-a8ce-5777fe78a7c3.JPG)
[g](url)

the viewer
![viewer](https://user-images.githubusercontent.com/75874364/148341487-bd5b72bf-4339-492e-b887-6da818645499.JPG)
:

and the errors showing in validator.
![errors](https://user-images.githubusercontent.com/75874364/148341579-06cbb97b-d1fa-4353-a456-3828b2bff2c2.JPG)

and please any one can send me some link or something so I can do this(tutorial).

thank you, please help.

Note: I just want skeleton (bones) for rigging , not animations.

**Comment by donmccurdy** [comment]
The reason the model appears so large is https://github.com/donmccurdy/three-gltf-viewer/issues/147 – that's a viewer bug, not a problem with the model itself. I can't tell from these screenshots whether the armature/skeleton is correctly exported or not, it might be OK even though you don't see it in the viewer.

The warnings about non-normalized weights are floating point errors. That's a minor bug in whatever software exported the model, but shouldn't affect rendering. Finally, note that the model uses 8 weights per vertex. Most implementations support only four, and the difference may or may not be noticeable when you begin to animate the model. Blender has an export option to include only the highest four weights.

**Comment by MoppyDev** [comment]
I'm still confused on how to fix this issue? Is there any workarounds to get the model viewed appropriately?
