### ISSUE TITLE
lol wild rift models 

### ISSUE THREAD

**Issue by kraulok** [donmccurdy/three-gltf-viewer#281]
yo i tried to change models with online converter to gltf some1 has a rar that has models from wild rift  it works but noot good tho is ther any way to search it ?

**Comment by donmccurdy** [comment]
Hi! Sorry, this isn't the right place for technical support. If you're looking for converters from a particular format (which format? RAR is a ZIP-like wrapper around other files), asking on the glTF Slack channel might be a better option: https://www.khronos.org/news/permalink/new-gltf-slack-channel

Some other tools listed at https://github.khronos.org/glTF-Project-Explorer/
