### ISSUE TITLE
Z-index issue

### ISSUE THREAD

**Issue by Obarda** [donmccurdy/three-gltf-viewer#285]
Hi,

For some reason the attached GLB file display wrong z-index in the viewer.

Example with the same camera angle view:
![image](https://user-images.githubusercontent.com/73034911/151385921-c34e465a-c7ca-4bbf-a30d-327894f8e179.png)

[Curve_gRIS.zip](https://github.com/donmccurdy/three-gltf-viewer/files/7951404/Curve_gRIS.zip)

**Comment by Obarda** [comment]
So why when I load it in [khronos](https://github.khronos.org/glTF-Sample-Viewer-Release/) I don't get 'flipped surfaced' like I get in Donmccurdy viewer?
![image](https://user-images.githubusercontent.com/73034911/151581860-6ee6cd5b-1e71-439f-9114-aa1c6e82d33b.png)

**Comment by donmccurdy** [comment]
There are different ways to sort transparent objects, none of which are perfect. If the Khronos Group viewer sorts in the same way as three.js (it may not) then it may still get a different result because sorting two objects occupying the same space may yield inconsistent results. 

Because these materials are not _actually_ transparent, they should not be using alpha blending as they are. This issue will not occur with opaque materials.

**Comment by Obarda** [comment]
Thank you. So how I can decide which method to use, when I want to display a semi transparent mesh?

**Comment by donmccurdy** [comment]
If the material is semi-transparent, use alpha blending. If not, it should be opaque. The rest is mostly up to the engine to decide. If two meshes occupy the same space, or are embedded in one another, transparency is likely to have problems.

**Comment by Obarda** [comment]
So what cause the problem in the file I've sent. Is it a case where two meshes occupy the same space ? Or embedded in one another?

**Comment by donmccurdy** [comment]
I can't tell which it is in this case sorry.

**Comment by Obarda** [comment]
What info is missing in order for you to tell which case is this? I mean you have the file.

**Comment by donmccurdy** [comment]
You would need to compare individual triangle data from each mesh to tell the difference, to see if they are the same mesh. Perhaps this could be done in Blender or another tool as well. It doesn't really matter anyway - the mesh doesn't use semi-transparency, so it shouldn't have alpha blending enabled. I do not plan to study this model further myself, as I have limited time to spend responding to questions.
