### ISSUE TITLE
Support KHR_materials_specular

### ISSUE THREAD

**Issue by PROCW** [donmccurdy/three-gltf-viewer#287]
Hi, Environment is displayed differently for the same glb model (ex: SpecularTest.glb). Do you know the cause?
https://gltf-viewer.donmccurdy.com/
https://github.khronos.org/glTF-Sample-Viewer-Release/
You can download the model from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecularTest.
Looks like Don's viewer doesn't support KHR_materials_specular. Load the model in glTF Sample Viewer, go to the Advanced Controls, and disable KHR_materials_specular... same result.
Can you tell me about supporting KHR_materials?

**Comment by donmccurdy** [comment]
three.js and this viewer do support KHR_materials_specular, that support was added in https://github.com/mrdoob/three.js/pull/22156.

You can see the effects of the specular extension in this screenshot:

<img width="952" alt="Screen Shot 2022-01-29 at 6 32 02 PM" src="https://user-images.githubusercontent.com/1848368/151678220-34f5cd16-71ed-4ecf-bbe9-60e7078f26e1.png">

If you're seeing something different, could share a screenshot of what you see vs. what you expect?
