### ISSUE TITLE
increasing transparency of a model.

### ISSUE THREAD

**Issue by i3roly** [donmccurdy/three-gltf-viewer#288]
hello again don,

since i already emailed you, i figured this would probably be more appropriate as others may have the same question. i apologise in advance for the overlap.

the creator of an R package (rgl) dr duncan murdoch (@dmurdoch), has updated it to export gltf files.

for myself, a huge beneficiary of his package, this is a big deal.

my current webspace ( http://fluxions.dydx.ie:1338 ) loads webGL in an HTML.

as you can see the pages are large but the figure quality is high; however performance is merely ‘adequate’.

i came across your ‘fiddle’ https://jsfiddle.net/donmccurdy/6b5j9p3y/ and have inspected the existing gltf viewers.

just want to know if i can increase the transparency of the skeleton or possibly decrease the thickness of the edges in the wireframe.

this thing is gonna haul ass!
![e955cd3ef0b240b87cb91e207fc9c522](https://user-images.githubusercontent.com/36090395/152448848-dcf86c7a-ba38-4a40-af81-3a7457192f40.jpg)

<s>i am seeking a simple solution:

all i want to do is try and maintain my current layout with multiple GLTF files rendered side by side, each with some fixed resolution so that it can look like a ‘grid’.

your fiddle demo seems close to what i’d like, but what i’m not sure is if it’s literally that simple as copy+pasting the html code.

while i’m no javascript expert (or novice), i was hoping to get some quick direction on how to update my page with this cutting-edge GLTF viewer, which will take my audience’ experience to the maximum.

thanks in advance!
</s>

**Comment by i3roly** [comment]
this thing is the bomb, @donmccurdy 

i'm using your jsfiddle code with some tweaks and i wanted to ask you if there's any way to change the default settings.

for example i'd like to have wireframe mode enabled for each pane.

i tried running this viewer, along with the threejs directory source, using servez, but it wouldn't go into kiosk mode for some reason, instead asking me to load a file even though i was running the untouched jsfiddle code.

**Comment by i3roly** [comment]
@donmccurdy is there a reason the gltf-viewer snippets (lavadragon example) wouldn't work with a custom URL?

http://fluxions.dydx.ie:1338/mapsgl/neurocon/hmaps_d38/h_map_dim9.gltf resolves fine, but if i input it as the model to either code piece:

https://jsfiddle.net/donmccurdy/6b5j9p3y/ 
https://codepen.io/donmccurdy/pen/rwXBRr?css-preprocessor=stylus

it fails to get the file. found this strange.

**Comment by i3roly** [comment]
my bad donny @donmccurdy 
turns out it was me (why am i always the last one to figure this out?! ;D) 

it's like our headers and food have something in common: if it aint [COR](https://www.cor.ca/)(s), then it ain't workin!

i'm gonna retitle this issue though because i wanted to ask if there's a way to add more transparency to the model display.
![Screenshot 2022-02-03 at 3 43 46 PM](https://user-images.githubusercontent.com/36090395/152441995-c6416c1c-cbd6-4bcd-85bd-ed662d7f752b.png)

**Comment by i3roly** [comment]
fluxions.dydx.ie:1338

it's up donny baby @donmccurdy 

yo dr @dmurdoch, we live.

as i said in our correspondence: this is some next level shit

[![thephutureisall](https://img.youtube.com/vi/Swd0RmHQzvU/0.jpg)](https://www.youtube.com/watch?v=Swd0RmHQzvU)

**Comment by donmccurdy** [comment]
CORS can be a headache, but glad you got the issues solved and it's working. And great use case!
