### ISSUE TITLE
Lighting question

### ISSUE THREAD

**Issue by SachaVeldhoen** [donmccurdy/three-gltf-viewer#289]
When I put my gltf file on your the GLTF-viewer website is show the gltf object perfectly with the lighting being perfect. Im trying to put this gltf file on my own website but then the colors of it just look kinda weird. Im trying to get the good amount of light from THREE but I can't find it. When I import it on your website its perfect. Wich lights and what settings do you use for it? I can't find it in you files on wich ones are enabled. On your website I uncheck the "add lights" part because I don't need those. Just the standard lighting without the "add lights" option. Thanks!

**Comment by donmccurdy** [comment]
Hi @SachaVeldhoen! The highest-quality lighting for PBR materials is an environment map, set with `material.envMap` or `scene.environment`. That's all you're seeing here, when 'add lights' is disabled. The environment maps I'm using are in [this folder](https://github.com/donmccurdy/three-gltf-viewer/tree/main/assets/environment), or you can find more on sites like https://polyhaven.com/hdris. [This three.js example](https://threejs.org/examples/?q=gltf#webgl_loader_gltf) is a good demo of how to use the environment map in your code.

**Comment by SachaVeldhoen** [comment]
Hello @donmccurdy. Thanks for the fast responce! I will going to take a look at it. Thanks!
