### ISSUE TITLE
Hello, why after I click the "Upload" button, click "OK", the file is not loaded in, there is no reaction

### ISSUE THREAD

**Issue by song0603** [donmccurdy/three-gltf-viewer#290]
![@A}0}DH2G3P8{{M5{LFGPTW](https://user-images.githubusercontent.com/98399290/160134533-7c2b78b0-2913-49e3-94b9-e93b9baaea9c.png)

**Comment by donmccurdy** [comment]
I don't see any `.gltf` or `.glb` files in this directory, are you sure it's a glTF file? Does that last file just have its extension hidden? If you could share the .ZIP (you can upload to github comments) that may help.

**Comment by song0603** [comment]
Thank you very much for your timely reply. I have also tried other GLTF files, which can be viewed normally on your website, but not on min
![7LCI{CH(6%5`3I(A$IYT5](https://user-images.githubusercontent.com/98399290/160145408-546cd9d1-421e-42a1-b59f-bc4ca8230f5c.png)
[Uploading models.zip…]()

e

**Comment by song0603** [comment]
![SEB@9E 7`~6ROZ(1I)}%GQE](https://user-images.githubusercontent.com/98399290/160145740-5ecfafbb-d3c5-4eae-b60e-6e46a8677def.png)
And I also found that before I uploaded the file, there was a dot flashing all the time, but there was no dot in your website. I don't know if this is the problem

**Comment by donmccurdy** [comment]
@song0603 it looks like the .ZIP in your previous comment did not fully upload, you may need to wait before submitting the comment. :)

**Comment by song0603** [comment]
[models.zip](https://github.com/donmccurdy/three-gltf-viewer/files/8351868/models.zip)
I uploaded it again, but I think my problem may be that the environment is not configured properly, I'm using VS Code and Microsoft,as a novice who is not familiar with it

**Comment by donmccurdy** [comment]
Oh I see – you'll need to run some kind of local server, you can't run websites properly when opening them directly from disk. There may be other issues. The intended way to run this tool locally is:

```
npm install
npm run dev
```

**Comment by song0603** [comment]
Thank you again for your reply. As you said, I have tried these two commands, but the result is in the picture. I don't know how to solve it.
![8(1OPW8~L%07DK3LH@UZBSH](https://user-images.githubusercontent.com/98399290/160158435-45ae1536-65de-4a40-b52f-c8eab57a8209.png)

**Comment by donmccurdy** [comment]
What happens if you visit `http://localhost:49708` (from screenshot above) rather than the local disk path shown in your first screenshot?

**Comment by song0603** [comment]
After trying your suggestion, I succeeded. Thank you very much
