### ISSUE TITLE
drug and drop downloads files

### ISSUE THREAD

**Issue by mliris** [donmccurdy/three-gltf-viewer#292]
Hi, I really like your project and it is exactly what I need, but drug/drop by me just downloads files to my client instead of displaying it. What did I miss? I have linux server with appache

**Comment by donmccurdy** [comment]
It sounds like the JavaScript did not load, you'll need to make sure that is built and deployed correctly. My build steps are described in README.md and package.json, for example:

```js
# install dependencies

# local development
npm run dev

# production build
npm run build
```

Once you've built the files you can push them to whatever static server you need.
