### ISSUE TITLE
how to show certain file

### ISSUE THREAD

**Issue by mliris** [donmccurdy/three-gltf-viewer#293]
Hi, you project is amaizing, I have a set of glb files on server, how can I send link to show the certain file, already uploded?

**Comment by donmccurdy** [comment]
Hi! If your GLB files are hosted with the correct CORS headers, you can create links to them with the `?model=$URL` parameter:

https://gltf-viewer.donmccurdy.com/#model=https://raw.githack.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb
