### ISSUE TITLE
URL Option for Environment

### ISSUE THREAD

**Issue by effofexx** [donmccurdy/three-gltf-viewer#298]
Is there a URL parameter to define which environment is used upon loading the model?

Being able to pass the URL for a model is a great feature, but some models just don't look best in the Venice environment, so I'm wondering if I can set environment to "None" via a URL option.

**Comment by donmccurdy** [comment]
Hi! Not currently I'm afraid. There is a parameter, `preset=assetgenerator`, that opts into a different IBL. I could perhaps be open to another option like `preset=punctual` that disables IBL. You may find https://modelviewer.dev/ to be a more configurable choice for real customization here. :)

**Comment by effofexx** [comment]
Thank you for bringing `preset=assetgenerator` to my attention! This is actually just what I had in mind when I posed the question.

Also thank you for telling me about https://modelviewer.dev/. I somehow hadn't come across that before, and I'm sure it'll keep me busy for a good while :)
