### ISSUE TITLE
wordpress integration

### ISSUE THREAD

**Issue by sepehrmokhtari** [donmccurdy/three-gltf-viewer#299]
how could I use this viewer in WordPress?
and if there is not a straightforward way to do this, how can I load textures inside a folder? (Actually, a zip folder to load all gltf and bin and textures)

**Comment by donmccurdy** [comment]
Hi! This is source code for my viewer shared for use as an example / learning, but it's just deployed as static content here, and I've not made any plans to repackage it for off-the-shelf use in other projects. You might find https://modelviewer.dev/ to be a good solution for that type of use case, also based on three.js.

I would tend to recommend not using .zip archives as resources for viewing on the web. This type of compression is mostly redundant with the types of compression HTTP servers can often provide, and far slower to decompress in JavaScript. If you can 'pack' the files into a `.glb` (try https://gltf.report/ for this) that is a more efficient and portable option.
