### ISSUE TITLE
Display browser support messages.

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-gltf-viewer#3]

**Comment by cvan** [comment]
Just out of curiosity, what's the issue w/ Safari?

**Comment by donmccurdy** [comment]
I don't think it has the FileSystem APIs to recurse subfolders, but haven't spent much time on it yet.  Firefox does, even though caniuse says it does not: http://caniuse.com/#feat=filesystem

**Comment by donmccurdy** [comment]
Done.
