### ISSUE TITLE
Performance - Renderer info

### ISSUE THREAD

**Issue by tomorrowevening** [donmccurdy/three-gltf-viewer#314]
Display the WebGLRenderer's `info` to display draw calls, triangles, etc. This would help speedup debugging performance with 3D artists 👍

**Comment by tomorrowevening** [comment]
This is SUPER low priority considering clicking the "notes" button displays this 👍

**Comment by donmccurdy** [comment]
Thanks! I don't know if I'll add more debugging features to this site, but this type of thing might be added to https://gltf.report at some point.
