### ISSUE TITLE
Exported glTF file on Cinema4D, texture is not shown, Error: MESH_PRIMITIVE_TOO_FEW_TEXCOORDS

### ISSUE THREAD

**Issue by gregorjahner** [donmccurdy/three-gltf-viewer#318]
Hey,

I'm trying to upload a model with an image-based texture I build on Cinema4D as glTF on glTF-viewer. The texture's not shown and an Error appears: MESH_PRIMITIVE_TOO_FEW_TEXCOORDS. I think, that the image is not right linked in the file, so that the viewer is not able to represent it. But I have no idea how to embed the .jpg texture right. 

Maybe someone can help out.
<img width="784" alt="Bildschirmfoto 2022-11-02 um 10 53 15 PM" src="https://user-images.githubusercontent.com/62840028/199609930-8f6d7c76-0db7-4b82-a9df-5fd28161c440.png">
<img width="1547" alt="Bildschirmfoto 2022-11-02 um 3 46 31 PM" src="https://user-images.githubusercontent.com/62840028/199610134-fe800e38-631c-489a-834e-5a6a4ddb8d82.png">

**Comment by donmccurdy** [comment]
Hi! It sounds like Cinema 4D is not exporting a valid glTF file. If it's missing UV coordinates, as the error suggests, then that would need to be fixed, you can't use textures without UVs. 

If you're not sure how to create UVs in Cinema 4D, I would recommend asking on their help sites (I don't use C4D myself). Or if the model does have UVs, you may need to report a bug if the UVs aren't exported.
