### ISSUE TITLE
Transmission Export Arnold Standard Surface Maya

### ISSUE THREAD

**Issue by MetBlu** [donmccurdy/three-gltf-viewer#319]
Hi everyone, 
I'm trying to export an object with glass material using Arnold render in Maya as glTF file via Babylon.
When I open the file with glTF Viewer the object looks like full opaque and not transparent as before. 
Can someone help me please? 
![image](https://user-images.githubusercontent.com/119612052/205265179-f06fe3a2-f81e-4398-a2f2-e111e7360578.png)
![image](https://user-images.githubusercontent.com/119612052/205266578-716a13d6-da3e-4b90-8f16-70a98f788fd5.png)

**Comment by donmccurdy** [comment]
> ...using Arnold render in Maya as glTF file via Babylon

Hi! Sorry, I'm probably not the right person to ask about this set of software. I would probably start by filing an issue on the Babylon.js Maya->glTF exporter, if that's the plugin you're using. This viewer does support transmission if it's exported correctly into the glTF file.
