### ISSUE TITLE
Support "Open with" program (path argument)

### ISSUE THREAD

**Issue by twoco** [donmccurdy/three-gltf-viewer#322]
You cannot assign files like *.glb to this program e.g. by "Open with..." (always). Windows 11. The Program just opens without loading the model path from start  argument.

**Comment by donmccurdy** [comment]
Hi @twoco — at one point I had included an Electron desktop app in this repository, but it has been removed since then. There's only a web application (https://gltf-viewer.donmccurdy.com/) maintained here now.
