### ISSUE TITLE
Why is there a problem of enlargement when I import the human skeleton model to drive the painting

### ISSUE THREAD

**Issue by C852062** [donmccurdy/three-gltf-viewer#327]
Why is there a problem of enlargement w
<img width="773" alt="fc1610d966dd307cbca3e313df46aac" src="https://user-images.githubusercontent.com/77388141/222081720-3cd4dbaa-e702-45f2-9810-abef33f4ffa6.png">
hen I import the human skeleton model to drive the painting

**Comment by donmccurdy** [comment]
Hi! I think this is caused by https://github.com/donmccurdy/three-gltf-viewer/issues/147. The model is fine, this viewer just doesn't do a good job of choosing the camera viewpoint for some skinned meshes.
