### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by ryae3e** [donmccurdy/three-gltf-viewer#338]
When I run the viewer from on this repository id runs perfect and is exactly what i need. I'm spend 7 hours now trying to run it on my git hun (i am not as all a programer) . I get it to load no problem but when i upload the same fine file i uploaded her I nothing happens. My chrome consol reads 'Uncaught SyntaxError: Cannot use import statement outside a module
client.js:1     Failed to load resource: the server responded with a status of 404 (0

The google and the chatgtp can seem to help so Im here with my head hug in shame. Please help

**Comment by donmccurdy** [comment]
You will need to run `npm run build`. The compiled app is then found in the `dist/` folder, and the contents of that folder is all you should upload to your server.
