### ISSUE TITLE
 Initialization angle problem

### ISSUE THREAD

**Issue by hcxmj** [donmccurdy/three-gltf-viewer#340]
Hello author, when I load and render a gltf/glb model, I find that the initial angle problem is not the front one. It seems that the effect is more like the perspective viewed from the upper right corner. If you want to initialize it, you will see the front view. How to adjust the angle of view?
The following are comparison screenshots of the same model opened on the gltf-viewr website and other websites:
<img width="1355" alt="image" src="https://github.com/donmccurdy/three-gltf-viewer/assets/58494807/de35b6c2-ce11-480c-ba2d-df4e8f28afb1">
<img width="1433" alt="image" src="https://github.com/donmccurdy/three-gltf-viewer/assets/58494807/a4aef315-35e2-4844-8eda-0fb35abc975f">

**Comment by donmccurdy** [comment]
Hi @hcxmj! The initial viewing angle is a subjective choice. In some cases, viewing from an angle can be preferable for aesthetic or UX reasons. In particular,  flat model like a map tile might be completely _invisible_ from the front, and it'd be very difficult for my viewer to detect whether that's a concern.

If you're looking for more features here, I'd suggest trying my more advanced viewer at https://gltf.report/, which gives you buttons to jump to the front/back/... views:

<img width="1078" alt="Screenshot 2023-06-07 at 11 22 11 PM" src="https://github.com/donmccurdy/three-gltf-viewer/assets/1848368/29f048d9-a142-4771-97f1-1dfe6460ce66">


This viewer (https://gltf-viewer.donmccurdy.com/) is more of an example than a fully-featured tool, so I'm intentionally keeping it pretty simple.

**Comment by hcxmj** [comment]
> Hi @hcxmj! The initial viewing angle is a subjective choice. In some cases, viewing from an angle can be preferable for aesthetic or UX reasons. In particular, a flat model like a map tile might be completely _invisible_ from the front, and it'd be very difficult for my viewer to detect whether that's a concern.
> 
> If you're looking for more features here, I'd suggest trying my more advanced viewer at https://gltf.report/, which gives you buttons to jump to the front/back/... views:
> 
> <img alt="Screenshot 2023-06-07 at 11 22 11 PM" width="1078" src="https://user-images.githubusercontent.com/1848368/244255462-29f048d9-a142-4771-97f1-1dfe6460ce66.png">
> This viewer (https://gltf-viewer.donmccurdy.com/) is more of an example than a fully-featured tool, so I'm intentionally keeping it pretty simple.

Ok, thank you very much, I moved this set of code to the mobile terminal for use, and it needs to be set up according to the product requirements. When I change the position of the camera, I find that the effect is strange, so I ask here and hope to get a solution

**Comment by donmccurdy** [comment]
@hcxmj in case I misunderstood, are you asking about the position of the camera relative to the model? Or the camera's [field of view](https://en.wikipedia.org/wiki/Field_of_view_in_video_games), regardless of the viewing angle? Field of view affects the perspective and appearance of depth. If that's what you're looking for, neither of these viewers provide options to modify the field of view currently.  If you have specific requirements you may need to set up a viewer for that.

**Comment by hcxmj** [comment]
> @hcxmj in case I misunderstood, are you asking about the position of the camera relative to the model? Or the camera's [field of view](https://en.wikipedia.org/wiki/Field_of_view_in_video_games), regardless of the viewing angle? Field of view affects the perspective and appearance of depth. If that's what you're looking for, neither of these viewers provide options to modify the field of view currently. If you have specific requirements you may need to set up a viewer for that.

Thank you very much for the ideas you provided earlier. I changed the camera’s fov=75 and position=(0,0,5) in the code to meet my needs.
