### ISSUE TITLE
InterpolatorComparison superimposes cubes on top of each other

### ISSUE THREAD

**Issue by andreasplesch** [donmccurdy/three-gltf-viewer#344]
[InterpolationComparison.zip](https://github.com/donmccurdy/three-gltf-viewer/files/12073082/InterpolationComparison.zip)

from https://github.com/mrdoob/three.js/pull/12907

looks incorrect:

![image](https://github.com/donmccurdy/three-gltf-viewer/assets/6171115/f56a143b-a61e-4c0c-ad49-3ab708051657)

but correct in https://github.khronos.org/glTF-Sample-Viewer-Release/

![image](https://github.com/donmccurdy/three-gltf-viewer/assets/6171115/3d9c6606-da66-4964-9ff6-8583b47c3f04)

No validation errors but still may be a problem with the glTF.

**Comment by andreasplesch** [comment]
Also works in https://gltf.report/:

![image](https://github.com/donmccurdy/three-gltf-viewer/assets/6171115/db96a6e3-0626-44db-99e5-ce371a4ba529)

(could not see a way to play the animation).

**Comment by donmccurdy** [comment]
Possibly related:

- https://github.com/mrdoob/three.js/issues/26470

**Comment by Mugen87** [comment]
Does it work if the changes from https://github.com/mrdoob/three.js/pull/26126 are reverted?

**Comment by Mugen87** [comment]
Should be fixed via https://github.com/mrdoob/three.js/pull/26476.

**Comment by donmccurdy** [comment]
Thanks @Mugen87! Will pull in the fix with the next three.js release.
