### ISSUE TITLE
Love your tool

### ISSUE THREAD

**Issue by PAGESVFX** [donmccurdy/three-gltf-viewer#345]
Hi, I have been enjoying a lot your tool loading glb files. I was wondering if the tool can be installed on any website, and if so do you have any instructions on how to go about it?

Thank you in advance for your help.

**Comment by donmccurdy** [comment]
Hi @PAGESVFX! This code is open source and you're welcome to copy the parts you need. The rendering engine is three.js (https://threejs.org/), and I use Vite (https://vitejs.dev/) to compile and build the code. If you're looking for the easiest possible way to get a viewer into your site, I would consider something like https://modelviewer.dev/ instead.

**Comment by PAGESVFX** [comment]
Thank you very much for your reply Don, I will look into it. Hopefully I can integrate it on my website. 

Thanks for your time.
