### ISSUE TITLE
Glass Material

### ISSUE THREAD

**Issue by ibibikerdo** [donmccurdy/three-gltf-viewer#348]
hello my friend. A customer of mine uses the "gltf viever" on the website you posted. The object he asked me for, made of glass material, does not appear transparent due to the white background. Any chance of helping?

**Comment by donmccurdy** [comment]
Hi @ibibikerdo - I think I'll need more details about the issue, and what you're trying to change. This viewer (https://gltf-viewer.donmccurdy.com/) doesn't use a white background by default, and the background color can be changed in the upper-right-hand settings panel.
