### ISSUE TITLE
How to host this gltf viewer in Wordpress?

### ISSUE THREAD

**Issue by kmnewazbillah** [donmccurdy/three-gltf-viewer#349]
I want to host this viewer in my Wordpress. Can you help me to do this?

**Comment by donmccurdy** [comment]
Hi @kmnewazbillah – the code for this repository is shared as a public resource, but I can't help you with integrating it into your own projects. 

If you're new to three.js, the  three.js forums might be a better place to visit if you are running into more specific problems: https://discourse.threejs.org/

Alternatively, consider using https://modelviewer.dev/ — it's a great tool, and often easier to add to existing websites.
