### ISSUE TITLE
White screen when viewing a model

### ISSUE THREAD

**Issue by xx4lph4xx** [donmccurdy/three-gltf-viewer#351]
i wanted to view my low-poly model with animations and textures (standard resolution), but when i put it on the viewer i get this white screen. could you please tell me what's the problem? thank you

**Comment by donmccurdy** [comment]
Sorry, I'm not sure what you mean or what you're seeing. 

Please share enough detail that I can reproduce the problem, ideally with the model. If you see any errors in the JS console, that's also helpful to know.

You may also want to run the model through a validator: https://github.khronos.org/glTF-Validator/

**Comment by xx4lph4xx** [comment]
![image](https://github.com/donmccurdy/three-gltf-viewer/assets/148410094/62fed3f7-1a31-4f0c-843c-8595d5f4733d)

**Comment by xx4lph4xx** [comment]
the model says it's valid, i've recently checked it using the validator, but on the viewer it goes to this white screen.

**Comment by donmccurdy** [comment]
Hm, it looks like the tab may have crashed. I haven't seen that result before. Do you see any particular warnings on these pages?

- https://get.webgl.org/
- https://webglreport.com/

And, does the model work in any of these viewers?

- https://gltf.report/
- https://sandbox.babylonjs.com/
- https://playcanvas.com/viewer

**Comment by xx4lph4xx** [comment]
alright

I tried the links you gave me, and they all had the same outcome - they load the model, show the meshes, and then suddenly the whole tab goes white again

where can i send the file by the way?

**Comment by xx4lph4xx** [comment]
i tested again on the viewer, clicked inspect and found these errors when i boot up, saying that the shaders are invalid. 
![image](https://github.com/donmccurdy/three-gltf-viewer/assets/148410094/0b953a25-9003-48f4-bb39-447913a96cd4)

**Comment by donmccurdy** [comment]
Hm, that's a very large texture! I wouldn't be surprised if using one or more >16K textures would cause issues, though I don't know if that's directly the cause here.

You can either put the model on a file-sharing site like Google Drive and share a link here, or email me – my email address is on my website: https://www.donmccurdy.com/
