### ISSUE TITLE
CSS3DRenderer      Adding tags, ineffective, I am very desperate

### ISSUE THREAD

**Issue by jinmaotowne** [donmccurdy/three-gltf-viewer#356]
Thank you for your reply！
Viewer.js
![300](https://github.com/donmccurdy/three-gltf-viewer/assets/17421156/1007f638-6a85-4bfb-a21b-4a4c27aa8ed5)
![3345](https://github.com/donmccurdy/three-gltf-viewer/assets/17421156/1d03f524-34ff-402d-a6a1-0941bc22ccaa)

![3444](https://github.com/donmccurdy/three-gltf-viewer/assets/17421156/56f830f2-31e2-4471-bd69-576c95cb25bf)

					const scene = gltf.scene || gltf.scenes[0];
					const clips = gltf.animations || [];

					if (!scene) {
						// Valid, but not supported by this viewer.
						throw new Error(
							'This model contains no scene, and cannot be viewed here. However,' +
								' it may contain individual 3D resources.',
						);
					}			
				scene.traverse(child => {

							if (child.type === 'Mesh' ) {

								console.log("===================");
								//添加标签文字
								  var element = document.createElement('div');
									element.className = 'tag';
									element.innerHTML = '============================';
									var object = new CSS3DObject(element);
									object.visible = true;
									//缩放比例
									object.scale.set(0.2, 0.2, 0.2);
									//指定摆放位置
									object.position.copy(child.position);
									scene.add(object);//添加到指定的场景里
							}

						});
				

						  this.d3renderer.setSize(window.offsetWidth, window.offsetHeight);
						  this.d3renderer.domElement.style.position = 'absolute';
						  this.d3renderer.domElement.style.top = '10px';
						  this.d3renderer.domElement.style.left = '10px';
						  this.d3renderer.domElement.style.pointerEvents = 'none';
						  document.body.appendChild(this.d3renderer.domElement);

					this.setContent(scene, clips);

**Comment by jinmaotowne** [comment]
the CSS3DRenderer  version is  r158

**Comment by donmccurdy** [comment]
Sorry @jinmaotowne — as mentioned in https://github.com/donmccurdy/three-gltf-viewer/issues/355#issuecomment-1845506678 I do not provide 1:1 support. Please use the three.js support channels (in link) rather than contacting me personally.
