### ISSUE TITLE
Materials are not loading properly

### ISSUE THREAD

**Issue by princeku07** [donmccurdy/three-gltf-viewer#357]
![Screenshot from 2024-01-02 17-48-48](https://github.com/donmccurdy/three-gltf-viewer/assets/50265671/fb92899f-62e4-45f2-9119-be4977efd97b)

but there is one more gltf-viewer which also uses three js 
![Screenshot from 2024-01-02 18-18-33](https://github.com/donmccurdy/three-gltf-viewer/assets/50265671/d59caef3-2a96-4451-b8a4-458d333645ce)

**Comment by donmccurdy** [comment]
I can't say for sure without more information, but perhaps your model uses the deprecated glTF extension, KHR_materials_pbrSpecularGlossiness? Support has been removed in recent three.js versions, if so. To upgrade your model to the metal/rough PBR workflow, see:

https://www.donmccurdy.com/2022/11/28/converting-gltf-pbr-materials-from-specgloss-to-metalrough/.
