### ISSUE TITLE
Passing S3 presigned URL to model?

### ISSUE THREAD

**Issue by munsanje** [donmccurdy/three-gltf-viewer#360]
I see you can pass a link to a web resource via `#model=`. This works for public resources, including those on S3. However, it fails for private resources passed via a presigned URL with the response `400: Bad Request`. Any workarounds here?

**Comment by donmccurdy** [comment]
If you aren't already, you'll probably want to use self-contained files (like `.glb`) with presigned URLs. If you use a `.gltf` with external `.bin` and texture resources, requests for those external resources will not be presigned unless the resource URLs embedded in the `.gltf` file are also presigned.

This viewer doesn't have any special-case handling for S3, I believe `#model=<presigned-url>.glb` should just work, unless there are other restrictions (HTTP Referrer maybe?) on the URL.
