### ISSUE TITLE
What is the 'punctualLights'? How can I make a same options in Three.js?

### ISSUE THREAD

**Issue by idyun93** [donmccurdy/three-gltf-viewer#361]
https://gltf-viewer.donmccurdy.com/

I uploaded a file(.glb), I checked 'punctualLights' but my test website looks not same.
Anyone know about punctualLights?

**Comment by donmccurdy** [comment]
Hi @idyun93  — see:

https://github.com/donmccurdy/three-gltf-viewer/blob/4fa0d14e7989b9edafb32328c67863dff090bf9e/src/viewer.js#L388-L395

**Comment by idyun93** [comment]
Thank you @donmccurdy !
