### ISSUE TITLE
How to use a fixed model file for gltf-viewer

### ISSUE THREAD

**Issue by joylix** [donmccurdy/three-gltf-viewer#370]
I want to use a fixed model file for gltf-viewer (to say my model file is "model/model_1.zip"),  and automatically skip the file selection step,  how should I do it?

**Comment by donmccurdy** [comment]
Hi! See the `#model` parameter mentioned here:

- https://github.com/donmccurdy/three-gltf-viewer/issues/293#issuecomment-1127688648
