### ISSUE TITLE
Project doesn't show 3d models

### ISSUE THREAD

**Issue by PeterBan11** [donmccurdy/three-gltf-viewer#371]
Greetings!
I'm beginner in Three JS.

I've tried to launch this project, but, unfortunately, it can't display my 3d models. It just upload a copy of STL file to my download directory.

And it seems doesn't support STP. It just opens it like text file.

Can you, please, help me out somehow?

**Comment by donmccurdy** [comment]
Hi @PeterBan11 —

This is a viewer for glTF models. It does not currently support other formats, and customization is left as "self service". If you need help getting started in this or other three.js projects, the three.js forums (https://discourse.threejs.org/) might be the best place to start.
