### ISSUE TITLE
Passing iframe information before file loading completes.

### ISSUE THREAD

**Issue by i3roly** [donmccurdy/three-gltf-viewer#380]
Hi @donmccurdy 

Quick question. I'm using the viewer in a very simple way, where I have a bunch of gltf viewers (one per image) for each row, with the possibility of multiple rows. 

My page has now evolved to put all of these into a content iframe that i dynamically resize. 

What I've noticed is that the viewer must complete the loading of all images for the size of the iframe to be calculated correctly, where the default size will be used until this loading completes. 

Is there a way for the viewer to pass the size information before loading completes? You can check my website at http://g-a.ca to see what I mean.

It's not a huge problem but i thought there should be a way to pass the size earlier as the viewer does seem to have it when it shows the monochrome outline of the target image before loading completes. 

It's also likely and possible im just doing something wrong haha.

**Comment by donmccurdy** [comment]
Hi! Sorry I'm not fully sure I understand what you're asking, but I think the parent page layout would work the same way regardless of what page is inside the iframe. The size of the iframe shouldn't be dependent on the dimensions of the 3D model. Your parent page can assign the width/eight of the iframe if you wish.

**Comment by i3roly** [comment]
my bad @donmccurdy i think this isn't an issue with the viewer, since i noticed the 'old' (webgl 1.0) version does it as well.

i guess i need to find a better way to get a responsive iframe that is able to resize without waiting for all of the content to get downloaded.

right now i rely heavily on the width and height tags of the 'content iframe' (that contains the gltf images) to be set in percentages, as i'm too stupid to calculate it otherwise.

i then use one of those 'onload' tricks to resize the iframe accordingly:

https://stackoverflow.com/questions/9975810/make-iframe-automatically-adjust-height-according-to-the-contents-without-using

but this requires that all of the content loads first, or at least it seems to.

i'll close this because it's not fair to the repo to have this as an issue, but i was hoping maybe you had some ideas on what i could do.

**Comment by donmccurdy** [comment]
You may find something like https://modelviewer.dev/ is easier to use in this case — it works as a custom element (not an iframe) and may be more predictable for layout with CSS Grid, Flex, or tables. It will also be much more efficient if you're planning to have more than 3 viewers on the page.

**Comment by i3roly** [comment]
interesting. but i think your viewer is better since i need skeleton mode, and i am relying on dr @dmurdoch’s rGL package to convert the MRI volumes to gltf.

but i will look at it. i am sure the consumers can wait a few seconds for the frame to resize properly, but i figured i’d ask someone who knows a thing or two about web stuff in case i missed an obvious approach to dynamic resizing according to the content.

Thanks,
Gagan
