### ISSUE TITLE
Sample skinned animation model not working.

### ISSUE THREAD

**Issue by calrk** [donmccurdy/three-gltf-viewer#39]
When working with the sample models from the GLTF sample models repo, I found this mesh outputs unexpectedly.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/WalkingLady

Expected result:
![image](https://user-images.githubusercontent.com/2245579/30016649-5f92d60a-9199-11e7-93f5-eeb5591125f6.png)

Actual result:
![image](https://user-images.githubusercontent.com/2245579/30016612-330928f0-9199-11e7-9443-d4ec06de4e9b.png)

I am looking into the solution, just wanted to check if this is something you were aware of or could point me in the right direction with fixing it.

Thanks,
Clark

**Comment by donmccurdy** [comment]
Hi @calrk — I'm not really sure what's going on with this one, but it's tracked at https://github.com/KhronosGroup/glTF-Sample-Models/issues/83. We think it is probably a bug in the model itself (coming from the converter/exporters).

**Comment by calrk** [comment]
Oh thanks, I'll track it over there then if I find anything.
I was having similar issues with a model created via the unity to gltf format, so will be investigating as part of that.

Thanks
