### ISSUE TITLE
Should file import be case sensitive?

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-gltf-viewer#40]
e.g. `tree.GLTF` does not work, says "no .gltf asset found".

If a buffer references "foo.bin" but the file is actually "foo.BIN", that's also unsupported, but less surprising.

**Comment by donmccurdy** [comment]
not seeing files like this, so meh.

**Comment by javagl** [comment]
I just saw one - a `GLB` instead of `glb`. It took a while until I figured out what was wrong.
<sup>And ... some swearing was involved here...</sup>

Is there any reason to *not* accept `GLB` files?

**Comment by donmccurdy** [comment]
Ok, yeah that seems fair. I do think I'll keep it case-sensitive for any resources referenced inside the glTF file though.

**Comment by javagl** [comment]
That's an interesting point. At least on \*nix OSes, `url: "IMAGE.png"` and `url: "image.png"` will refer to different files - even though they could not be distinguished on Windows, and thus, the glTF would not be "platform independent" if it contained both. (From the tip of my head, I cannot say whether the spec says anything here...)

**Comment by donmccurdy** [comment]
The spec refers to RFC 3986, which defines URIs as case-sensitive.
