### ISSUE TITLE
Minecraft textures not showing up

### ISSUE THREAD

**Issue by emackey** [donmccurdy/three-gltf-viewer#42]
So I tried exporting a thing from Minecraft.

[One of Al's houses.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1327960/One.of.Al.s.houses.zip)

The textures don't show up at all.  I haven't looked inside the glb yet to know whether this is just a non-compliant export or there's actually a bug here.

FWIW, the textures do show up in [Babylon Sandbox](http://sandbox.babylonjs.com/).  But if this turns out to be a glTF "dialect" or something not in spec, we should pester the Minecraft folks to fix.

**Comment by donmccurdy** [comment]
Fixed at https://github.com/donmccurdy/three-gltf-viewer/commit/3d8701923206aa5385894ad4273a24d31d4f0666

Thanks!
