### ISSUE TITLE
Update to GLTF2Loader?

### ISSUE THREAD

**Issue by pjcozzi** [donmccurdy/three-gltf-viewer#46]
@donmccurdy is this using the latest glTF loader in three.js?

Should this load all sample models in https://github.com/KhronosGroup/glTF-Sample-Models/?

**Comment by donmccurdy** [comment]
Replied offline, but for anyone curious:

- The viewer is usually quite up to date. Currently 3 commits behind three.js `dev`, and ahead of the latest stable release (r87). Exact version of GLTFLoader is [linked on the header](https://gltf-viewer.donmccurdy.com/), although there may be some caching of JS resources i need to sort out.
- All sample models should be supported, with the exception of WalkingLady SmilingFace (both invalid) and Polly (https://github.com/mrdoob/three.js/issues/12364).
