### ISSUE TITLE
Skinning with default material

### ISSUE THREAD

**Issue by javagl** [donmccurdy/three-gltf-viewer#50]
An object with the "default" material does not support vertex skinning. For example, the "SimpleSkin" model at https://github.com/javagl/gltfTutorialModels/tree/2.0/SimpleSkin right now passes validation and should show the animation that is shown in the screenshot.

This is likely due to the default vertex shader not having the joint matrix uniforms. 

(It's a bit unfortunate that there can be no "universal" default material/shader. It's probably necessary to create an own shader, at runtime, for each number of joints. At least, that's what I did [in JglTF](https://github.com/javagl/JglTF/blob/master/jgltf-model/src/main/resources/pbr.vert#L18). Maybe uniform buffer objects could solve this, but I'm not an expert here).

**Comment by donmccurdy** [comment]
> This is likely due to the default vertex shader not having the joint matrix uniforms.

Hm I think it's simpler than that, the material is right but the animation and skeleton aren't getting set up right. Will look into this.

Do you know if this model has worked in three.js before?

**Comment by javagl** [comment]
I hadn't tried this model with three.js before. Note that it's basically "hand-crafted" for the tutorial, so this might be a case that rarely appears in practice. But after playing around and doing some tests (actually with babylon, which fails to load the model entirely), I noticed that when adding
```
  "nodes" : [ {
    "skin" : 0,
    "mesh" : 0,
    "children": [1]  // <----------------------------- This line
  }, {
    "children" : [ 2 ],
    "translation" : [ 0.0, 1.0, 0.0 ]
  }, {
    "rotation" : [ 0.0, 0.0, 0.0, 1.0 ]
  } ],
```

it works properly. It seems that it is necessary (in three.js and babylon) to have the skeleton hierarchy be part of the "main" node hierarchy. 

The structure of this sample is actually equivalent to the [snippet about skins in the spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#instantiation). And although I did not find this being mentioned *explicitly* in the spec, @lexaknyazev mentioned in https://github.com/KhronosGroup/glTF/issues/723#issuecomment-254674004 that

> top-level skeleton node must be top-level glTF node;

which for me means that the `children` entry in the root node should not be necessary. 

(In fact, it might even (have to) be disallowed? The validator currently accepts both versions, maybe this could be made more strict at this point)

**Comment by donmccurdy** [comment]
Ok, yes that's the issue. It also works correctly if you make the root of the skeleton a child of the scene, rather than a child of the mesh.

If having the skeleton be disjoint from the glTF node hierarchy is allowed, I think we would still have to append it to the scene in three.js to support it at all, since the skeleton must have world/local position calculated somehow. Ideally better to disallow that.

![simple skin preview](https://user-images.githubusercontent.com/1848368/31696039-4aaec35c-b363-11e7-8ea6-5524119ff19d.gif)

**Comment by javagl** [comment]
Whether or not the root of the joint nodes is contained in the `scene.nodes` could actually be considered as a syntactical detail, but it would be better to clearly say something about this in the spec. 
 
(There are some issues that are roughly related, at least, e.g. https://github.com/KhronosGroup/glTF/issues/1108 . I still have to wrap my head around the role of the `skin.skeleton` in this regard - i.e. construct two examples/test models where the effect of the `skin.skeleton` is visible and relevant)

**Comment by donmccurdy** [comment]
Going to close this as discussion of skinned mesh transformations is ongoing within the spec.
