### ISSUE TITLE
Reportedly darker w/ r87

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-gltf-viewer#51]
Vs r86, same model

http://games.clarklavery.com/gltf-sample/index.html

Reported by calrk in slack

**Comment by calrk** [comment]
The example is now showing from left to right, r86 - r87 - dev

R86 and R87 are working fine, but the dev version is much darker

Uploaded the sample if it helps.
http://games.clarklavery.com/gltf-sample/sample.zip

**Comment by donmccurdy** [comment]
In r86 and r87 the loader was treating the textures as if they used linear encoding for color and emissives. In dev, it was [fixed to use sRGB](https://github.com/mrdoob/three.js/commit/dc78b9f988c03f8f3cc03bcdf3a46355ac49f5ee#diff-43f9265a3da0d9ebbf235517b2541578) instead. The new behavior is correct — all glTF diffuse textures are sRGB, but that is why this looks darker. In general with more colorful models, things were looking a bit washed-out before, and that's why the black in the model appears more grey-ish in r86-r87.

**Comment by calrk** [comment]
Thanks for the explanation.
