### ISSUE TITLE
BoxAnimated.gltf doesn't animate correctly 

### ISSUE THREAD

**Issue by sakrist** [donmccurdy/three-gltf-viewer#52]
Here is model:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxAnimated

**Comment by donmccurdy** [comment]
Previewing the model at this URL:

https://gltf-viewer.donmccurdy.com/#model=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BoxAnimated/glTF/BoxAnimated.gltf

... if you press the "Animation -> playAll" button, it will play both animations together, correctly. By default the viewer plays only the first animation — it is an error in the sample models that [they contain many animation clips meant to be treated as one](https://github.com/KhronosGroup/glTF-Sample-Models/issues/108).

**Comment by sakrist** [comment]
Oh my ... (read issue you pointed at)....

If I press play all animations, they still play incorrectly.

**Comment by donmccurdy** [comment]
Incorrectly in what way?

**Comment by sakrist** [comment]
they play independently, and then don't match same timeline. 
Or it's feature?

**Comment by donmccurdy** [comment]
Hm you're right. The movement and rotation of the purple box _shouldn't_ be two separate clips, per the issue above, but they are and unfortunately the lengths of those two tracks are different:

![screen shot 2017-10-27 at 8 32 23 am](https://user-images.githubusercontent.com/1848368/32112178-6714a4cc-baf1-11e7-8125-dc98f221043e.png)

So, it's probably a further bug in the model itself. Maybe even in the COLLADA file this glTF was created from, but I suspect just the glTF conversion. The playback is also broken in BabylonJS's viewer, in the same way: http://sandbox.babylonjs.com/

I've filed an issue on the sample models repo, here: https://github.com/KhronosGroup/glTF-Sample-Models/issues/126
