### ISSUE TITLE
Error message when importing file with morph targets

### ISSUE THREAD

**Issue by Kupoman** [donmccurdy/three-gltf-viewer#56]
I am trying to add support for morph targets in [blendergltf](https://github.com/Kupoman/blendergltf). I have generated a file that is passing validation, but I get a message saying "dependencies.accessors[target.POSITION].clone is not a function" when I try to load that file in the viewer. I am not sure if the problem is with the exporting, my version of the validator, or with the viewer.

Here is the file I am trying upload:
[simple_shape_key.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1490075/simple_shape_key.zip)

**Comment by donmccurdy** [comment]
I think it's a bug in the viewer when interleaved buffers and morph targets are combined. I'll see what can be done about fixing that, but in the meantime if you don't interleave the buffers it should bypass this.

(Or, if it's not intentional that this be interleaved, perhaps byteStride is incorrect?)

**Comment by Kupoman** [comment]
You were right, it was the interleaved morph target data. When I disabled the interleaving, the error went away. The mesh did not display right, but I am pretty sure that is from bad morph target data.

**Comment by donmccurdy** [comment]
Does this look correct? Having a go at supporting interleaved morph target data (although on the three.js end we have to de-interleave it).

![d09f05be-04ac-48d2-9258-8db6f7659f19-99703-00025d0562d1554d](https://user-images.githubusercontent.com/1848368/33520731-787784d2-d775-11e7-8bf2-4282e9e04c1a.gif)

**Comment by donmccurdy** [comment]
Fixed via https://github.com/mrdoob/three.js/pull/12800, will be updated in the viewer after next three.js release. Thanks!
