### ISSUE TITLE
camera ends up far from model orbit

### ISSUE THREAD

**Issue by zellski** [donmccurdy/three-gltf-viewer#57]
I use this viewer constantly, and I've noticed that at some point something changed whereby now I will sometimes find the object of my desire far in the distance; no amount of camera orbiting brings it close enough to view. I've done a few half-hearted attempts at debugging the bounding box code, and of course I worry that it's my models that contain spurious vertices that are throwing the calculations off, but I thought I would at least post the issue in case someone else has noticed the same thing.

I'm including a troll.glb and a troll-4.glb; these are exports of the same .fbx at slightly different stages of development and exported with slightly different versions of my FBX2glTF converter -- so the .gltf portion is fairly different. Still, it's fundamentally the same model, yet troll.glb shows up nice and centered, whereas troll-4.glb is tragically distant.

Grateful for any insight! I am happy to dig in further if you find yourself flummoxed.

[troll.glb.gz](https://github.com/donmccurdy/three-gltf-viewer/files/1519639/troll.glb.gz)
[troll-4.glb.gz](https://github.com/donmccurdy/three-gltf-viewer/files/1519654/troll-4.glb.gz)

**Comment by donmccurdy** [comment]
That is indeed tragic 😅 ..Enabling the "grid" option shows that troll-4.glb is not centered, while troll.glb, but that could also be the viewer's re-centering logic getting something wrong...  Will investigate further soon.

<img width="994" alt="screen shot 2017-11-30 at 4 54 40 pm" src="https://user-images.githubusercontent.com/1848368/33462887-2ee5ecaa-d5ef-11e7-886b-66d8e75990cd.png">

**Comment by zellski** [comment]
Interesting, I had somehow not spotted that option. Also, for what it's worth: the babylon viewer always, invariably, centres the model.

**Comment by donmccurdy** [comment]
Ok so, if we add a BoxHelper (you can run this JS in the console of the viewer, `content` is global)

```js
let bbox = new THREE.BoxHelper(content, 0xff0000);
content.parent.add(bbox);
```

as far as three.js is concerned, the mesh is large, about 200x200x200.

<img width="738" alt="screen shot 2017-12-02 at 11 04 15 am" src="https://user-images.githubusercontent.com/1848368/33518832-98f3710a-d750-11e7-825d-8afcb6cd77b5.png">

I think what's happening is that there's a transform on the root of the troll's skeleton:

```
{x: 0.00999999977648258, y: 0.00999999977648258, z: 0.00999999977648258}
```

It's not very well-defined what _should_ happen when the skeleton has a world transform, either in threejs or glTF... there's an internal thread discussing it for glTF. For three.js I think we'd like to work toward having that be ignored, such that skeletons could be shared by multiple meshes. But for the present that is not the case, it's a larger threejs-level change, and anyway this transform seems likely to be a bug in the model.

**Comment by zellski** [comment]
Aha. This makes sense. It's [not the first time](https://github.com/facebookincubator/FBX2glTF/issues/29) something related to this annoying scale transform comes up.

Although, from what you say, isn't the apparent contradiction a result of the scaling **being** ignored, rather than not yet being ignored? For the mesh itself, clearly, visually, the scaling is used. Large values (given in centimetres in the FBX) are correctly scaled down by 100. But something else (and the skeleton seems a likely culprit) is **not** being scaled down, so those large centimetre values are taken literally as glTF metre units?

In any case, I think what I should do is detect when the FBX SDK introduces this 0.01 scaling (which it does as part of unit translation) and, since it's a simple uniform scaling, take the liberty of changing it to 1 and instead literally multiply it into every vertex position in the model instead.

I'll take a peek later using BoxHelper and try to work out why troll.gltf does not trigger the same scale issue. Thanks for looking into it!

**Comment by donmccurdy** [comment]
> Although, from what you say, isn't the apparent contradiction a result of the scaling being ignored, rather than not yet being ignored? For the mesh itself, clearly, visually, the scaling is used. Large values (given in centimetres in the FBX) are correctly scaled down by 100. But something else (and the skeleton seems a likely culprit) is not being scaled down, so those large centimetre values are taken literally as glTF metre units?

I think the issue is that THREE.BoxHelper and `Box3.setFromObject` are determining bounding boxes based on the geometry and world transforms of the mesh, and aren't smart enough to apply skinning transformations to the mesh before doing so (the skinning would normally be applied in the vertex shader, not the CPU, anyway). So, the bounding box simply doesn't match the rendered size. If I had to guess, BabylonJS just ignores the transform of the skeleton (the choice is subjective here, given that glTF has not specified yet), and can get the centering right as a result.

**Comment by zellski** [comment]
One way or another, getting rid of the 0.000999etc transform definitely fixed it:

<img width="511" alt="screenshot 2017-12-02 16 41 00" src="https://user-images.githubusercontent.com/714167/33521186-bf99c29e-d77f-11e7-9e77-77cbfd56625e.png">

This was a hack, though. Now follows the inevitable struggle figuring out what is the most proper way to do things, pragmatic considerations regardless, and whether or not it's still useful to do the most pragmatic thing, and if it's helpful or damaging to add another layer of magic to the converter, and how to do so best without breaking all the existing layers of magic that everything in the FBX chain have applied over the years. :)
