### ISSUE TITLE
Model with not unique nodes names is not animated correctly

### ISSUE THREAD

**Issue by AurL** [donmccurdy/three-gltf-viewer#58]
Hi, 

The glTF loader seems to have animation linking issues when nodes have the same name.
For example, this model has it's back wheels not animated correctly: 

https://sketchfab.com/models/b0301ec0c52f4e8cbef0acae03beb33e

It has two nodes names `WheelsThird` and the animation channel seems to animate the wrong one.
I tested by renaming the duplicate to `WheelsThird2` and it fixes the issue. Names are not required to be unique, so it's valid to have this case, and I think it's easy to fix.

**Comment by donmccurdy** [comment]
Merging this issue with https://github.com/mrdoob/three.js/issues/15087.
