### ISSUE TITLE
Interleaved mesh accessors without byteOffset specified don't render

### ISSUE THREAD

**Issue by mhurliman** [donmccurdy/three-gltf-viewer#60]
Adding an extension to a tool that outputs meshes in multiple different formats. One such format is interleaved mesh data. Such as:

|Pos0|Norm0|UV0|...|Pos1|Norm1|UV1|....|PosN|NormN|UVN|...|

The accessors for the vertex attributes each specify a byteOffset from the start of the vertex, except Position, since its byteOffset is zero. The standard states that byteOffset should be defaultly zero, so it shouldn't be necessary to explicitly write "byteOffset": 0 for the accessor. However, manually adding "byteOffset": 0 to the file for the Position accessor allows it to render properly.

I don't have control of the serialization code, so I can't even hack it in, and adding it manually to large model files is quite a nuisance.

**Comment by donmccurdy** [comment]
Are you able to share an example reproducing the problem? Tried a quick test and it seemed to go OK.

**Comment by mhurliman** [comment]
[Primitives.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1604807/Primitives.zip)

**Comment by donmccurdy** [comment]
This change fixes the errors: https://github.com/mrdoob/three.js/pull/13043

Although in both models I see an extra triangle connecting the two primitives:

<img width="269" alt="screen shot 2018-01-04 at 4 41 01 pm" src="https://user-images.githubusercontent.com/1848368/34590936-d2c4aeac-f16e-11e7-92c1-8649e3b4b4b4.png">

Any idea if that's related to your authoring tool?

**Comment by mhurliman** [comment]
Suh-weeeeeeeeeeet! Figured it was probably a loader issue. Nah, it was modeled that way - was messing around with materials in Blender to generate a mesh that had two primitives. Thought it might try to do something fancy if the two vertex groups weren't connected.
