### ISSUE TITLE
Viewer cannot load the non-glb version of this glb file.

### ISSUE THREAD

**Issue by chipweinberger** [donmccurdy/three-gltf-viewer#61]
I have my exporter make both a glb and non-glb version of this file, but only the glb version can load in your viewer. It's possible there is a bug in the exporter, too., but it is strange. It only happens with this file. 20 others I've tested do not have this issue. 

 I can "fix" this issue by telling my exporter concat everything into a single buffer, Glb or not. There are ~450 buffers in the gltf folder, otherwise.

[AdamGltfGlb.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1605389/AdamGltfGlb.zip)
[AdamGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1605390/AdamGltf.zip)

**Comment by donmccurdy** [comment]
There's something invalid in the `.gltf` version at least: take `2138.verts.bin` for an example, the buffer list displays `byteLength: 2340`, but the actual file itself is only 204 bytes.

May also want to write the `arrayIndex` markers as `"extras": {"arrayIndex": 123}`, as this will silence the errors from glTF-Validator.

**Comment by chipweinberger** [comment]
Thanks don. Both great suggestions.

**Comment by chipweinberger** [comment]
The error ended up being in my exporter. I had name collisions in the buffer names =)

Sorry for the spam. Thank you for helping me find it though. Super helpful.
