### ISSUE TITLE
"RENDER WARNING: there is no texture bound to the unit 1" with this file

### ISSUE THREAD

**Issue by chipweinberger** [donmccurdy/three-gltf-viewer#63]
[PANGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1623878/PANGltf.zip)

No textures show for this file.

This file uses PNG textures. They load and show correctly with the Qtek (now called Clay) viewer https://github.com/pissang/clay-viewer

**Comment by donmccurdy** [comment]
Interesting... the warning is just a warning (the image is being applied) but this model _also_ contains (all-black) vertex colors. I think that's multiplying against the texture and rendering it black.

Looks like the [qtek viewer doesn't support vertex colors](https://github.com/pissang/clay-viewer/issues/14)? That would explain why the model looks OK there.

**Comment by donmccurdy** [comment]
Looks good after vertex colors are removed:
<img width="782" alt="screen shot 2018-01-11 at 11 44 16 am" src="https://user-images.githubusercontent.com/1848368/34844097-32d8ec6c-f6c5-11e7-92dc-93b5e869a417.png">

**Comment by chipweinberger** [comment]
Hmm I imagine you're doing the reasonable thing here?

These files are coming from my Fbx to Gltf converter and it look like the all black vertex colors are in the original Fbx file oddly enough.

My intuition was that textures should take precedent and replace vertex colors. But I could be wrong about that.

**Comment by donmccurdy** [comment]
My loader is just passing all of it through to three.js, which multiplies everything (factor, textures, vertex colors) together. That could be helpful for things like animation, where morph targets on vertex colors could (in some future version of glTF) be used to animate color and transparency of specific vertices against a base texture.

But currently I can’t find anything in the glTF spec to say what’s expected, so that could be clarified...

**Comment by chipweinberger** [comment]
I also see vertex colors as a something to show when you can't or don't want to show the textures or are waiting for them to load.

A simple Gltf::material enum choice for these two options would be nice to have.

**Comment by zellski** [comment]
There is a sentence at the end of a paragraph in the spec: "In addition to the material properties, if a primitive specifies a vertex color using the attribute semantic property COLOR_0, then this value acts as an additional linear multiplier to baseColor."

**Comment by chipweinberger** [comment]
That does seem to suggest it would also act as a linear multiplier for texture colors too. Seems like a reasonable assumption.
