### ISSUE TITLE
Occlusion culling 

### ISSUE THREAD

**Issue by ProFive** [donmccurdy/three-gltf-viewer#67]
Hi Guys, 

Do you have apply Occlusion culling  this project ?

**Comment by donmccurdy** [comment]
Hi,

This uses mostly default three.js settings, so frustum culling and a form of occlusion culling involving front to back rendering are used. More details here: https://stackoverflow.com/a/36324563/1314762

**Comment by ProFive** [comment]
Thanks, Don!
AFAIK, there is currently no official example for occlusion culling with three.js.
 https://discourse.threejs.org/t/occlusion-culling/1646/4
