### ISSUE TITLE
Add KHR_draco_mesh_compression support.

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-gltf-viewer#70]
See https://github.com/mrdoob/three.js/pull/13194

**Comment by zellski** [comment]
Oh I’ve been waiting for this. Do you intend to update your “public web tool” with the relevant code?

**Comment by donmccurdy** [comment]
Staged an experimental version:

* Demo: https://gltf-viewer-experimental.donmccurdy.com/
* Code: https://github.com/donmccurdy/three-gltf-viewer/tree/feat-draco

Currently it only works for the first Draco model imported per pageview, and throws an error for the next. Not sure yet whether that's a bug in my implementation or the decoder module.

**Comment by zellski** [comment]
It's so great to be able to FBX2glTF --draco --binary again, and just pull the (much-shrunken) result right into this viewer.

**Comment by cx20** [comment]
I tried `glTF-Draco` format file using experimental demo site.
https://gltf-viewer-experimental.donmccurdy.com/

- [Duck.gltf](https://github.com/donmccurdy/three-gltf-viewer/files/1734770/Duck.zip) Draco format model of the [glTF-Sample-Models](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Duck/glTF-Draco) repository could be displayed.
- [Duck.gltf](https://github.com/donmccurdy/three-gltf-viewer/files/1734772/Duck.zip) Draco format model outputted with the latest [COLLADA2GLTF](https://ci.appveyor.com/project/Khronoswebmaster/collada2gltf/build/2.0.165/job/a1x6q87nxspgbn9v/artifacts) could *not* be displayed.

When loading failed, the following error was output to the console.
```
bundle.js?v=r90:223 
  THREE.DRACOLoader: Decoding failed: Failed to decode geometry data.
  convertDracoGeometryTo3JS @ bundle.js?v=r90:223
```

The arguments used for the conversion are as follows.
```
COLLADA2GLTF-bin.exe -i Duck.dae -o Duck.gltf -v 2.0 -d -s
```
I could not judge whether it is a converter issue or a viewer problem.

**Comment by donmccurdy** [comment]
Thanks @cx20 — the COLLADA2GLTF file looks ok in Babylon and gltf.insimo.com (slightly different implementation in three.js) so i believe this a bug in my viewer or THREE.GLTFLoader. Will look into that soon.

**Comment by donmccurdy** [comment]
Released draco support. The COLLADA2GLTF issue isn't limited to my viewer, it happens in plain three.js as well, so I've opened https://github.com/mrdoob/three.js/issues/13870.

**Comment by EtagiBI** [comment]
Hmm... Is it a validator problem then?
![image](https://user-images.githubusercontent.com/20855725/48536186-a0e47080-e8cf-11e8-86ac-1bb8ea183103.png)

**Comment by lexaknyazev** [comment]
Yes. It means that the validator doesn't support that extension. The message will be refined in the next release.
