### ISSUE TITLE
rotating model 

### ISSUE THREAD

**Issue by vadnart1** [donmccurdy/three-gltf-viewer#71]
Hi, 

I'm having difficulties rotating that model around the axis such that i can spin around front to back. Currently the model only seems to rotate around the "top" surface and underside.

1.  the image "glfviewer-sample1" is what the model looks like when it's first loaded.
<img width="373" alt="gltfviewer-sample1" src="https://user-images.githubusercontent.com/26193375/36331801-0306d06c-1335-11e8-8db0-d43e31e4a143.png">

2. when i try to rotate, the model only seems to want to rotate around "vertical" axis  as shown in "gltfviewer-verticalrorate".  thus i can only rotate the model around to see the top and underside.  However I can not seem to rotate the model around to see the back (the "back" being the section with all the white and green palettes).

<img width="368" alt="gltfviewer-verticalrotate" src="https://user-images.githubusercontent.com/26193375/36332185-d0f02a5e-1336-11e8-97cd-0b8e52082005.png">

Underside of the model:
<img width="375" alt="gltfviewer-rotate-underside" src="https://user-images.githubusercontent.com/26193375/36332229-06b008e4-1337-11e8-8568-cadd144b3b6e.png">

I hope that makes sense.  I can share the .glb file (50MB) if anyone would like to help.

Thanks again, David

**Comment by donmccurdy** [comment]
Hi! When the model first loads, is the "top" of the model correctly oriented? Or is the model 90º sideways?

The rotation limits are part of `THREE.OrbitControls`, used to avoid getting into weird orientations, so I sort of have to do the "generally best thing" for most models.

Aside, the glTF format specifies that models should be authored +Y up, +Z forward, and that import/export tools should plan accordingly. So if your tooling is doing something different, it could be worth filing a bug there as well.

**Comment by vadnart1** [comment]
Hi Don !   the top of the model does appear to be 90º "sideways"  .  but it looks really good.

the OBJ+materials were generated by Pix4D (images captured from drone), then converted to .glb using the obj2gltf conversion tool.

is there a way to set the controls to have model spin around "front" to "back" ?

**Comment by donmccurdy** [comment]
Hm, I don't see any good way to adjust the viewer to handle this automatically (e.g. you'll see Sketchfab puts similar limits on rotation) and I don't think I want to add options specially to view models that are not oriented correctly for import into other workflows, sorry. It's just that a lot of people used this to debug glTF stuff, and adding the option is liable to give the impression that other orientations are valid (which has historically been a mess with other formats). It looks like obj2gltf used to have an option for converting the axis, then removed it while planning to add it into [another tool](https://github.com/AnalyticalGraphicsInc/gltf-pipeline), but then re-adding it hasn't actually happened yet. 😕 Perhaps they would consider bringing that back in..

**Comment by vadnart1** [comment]
Hi Don,

First, thankyou for all the help so far.

I definitely understand why you don’t plan to add orientation options.

Can I ask a favor, if we were to add this option for our own use where would you suggest best place in the code to implement ?

Regards,
David

**Comment by donmccurdy** [comment]
Hi @vadnart1 — I don't include orientation options because glTF is very specific about the correct way to orient models. If third-party tools are creating models in another orientation, that is a bug. If I add options here, it gives the impression that all orientations are valid, and that more tools should have these options. And then we end up with lots of inconsistent tools and models.

If you need something like this for your reasons, you could put a fixed rotation on the model in `setContent`, or add some GUI options in that file:

https://github.com/donmccurdy/three-gltf-viewer/blob/master/src/viewer.js#L189-L211

**Comment by javagl** [comment]
Jut out of curiosity: Would it be much effort to offer the option to switch from the `OrbitControls` to other control types? 

This may not be "important", usually (the main use-case of the viewer for me is to see whether a glTF model can properly be displayed - if someone wants finer control, he can fork the repo and do this kind of things on his own). But if it was only something that could be done with a few lines of code, it could be a "nice to have"...

**Comment by donmccurdy** [comment]
There's an option to disable `screenSpacePanning` in the *Display* options, which might help with large flat models like terrain. But I'd rather not add new control types beyond that.

**Comment by javagl** [comment]
The main point (or reason for asking) was that due to the constraints that are imposed by the `OrbitControls`, it sometimes is plainly not possible to rotate/orient a model so ~"that it looks nice". But of course, the limit case is that each and every setting is routed through the UI, deviating from the goal of creating a quick, simple, lean drag+drop-viewer. So this is fine for me.
