### ISSUE TITLE
Issues about mesh

### ISSUE THREAD

**Issue by CuongAnimator** [donmccurdy/three-gltf-viewer#77]
Hi Guys

I try import all into https://gltf-viewer.donmccurdy.com/ but it don't have a mesh ,only have skeleton and animation.
I export from Blender into gltf.
Please help me.
Thanks so much

**Comment by donmccurdy** [comment]
Hi @CuongAnimator — Please include enough detail for me to reproduce this problem. Can you attach the `.gltf` file and (ideally) original `.blend` file? It may or may not be possible to import an animated skeleton without including some sort of mesh, but I'm glad to take a look.

**Comment by donmccurdy** [comment]
Also, welcome to GitHub! 🙂

Note that you can drop .ZIP files into GitHub comments if needed.

**Comment by CuongAnimator** [comment]
Hi Don McCurdy.
Nice to meet you.

We completed a model with animation in maya and export to fbx file.
Then we import the fbx file into the Blender to export to glTF file.
We've attached the Maya and Fbx file.
Please check it and tell me about our problem.
We just want to export the model that have an animation from the Maya to
glTF file
Hope you help us.
I look forward to hearing from you.


*Thanks and Best Regards*Cuong.
[image: photo]

<http://sketchfab.com/goart>  <http://www.facebook.com/cgavn/>
Pham Quoc Cuong

COO
CgArt Creation Joint Stock Company

(+84)  <(+84)%204%2035766083>
2866574427
(+84) 977180749
(+84) 4 35765504
cuongpq@cgart.com

Skype: +84977180749
http://cgart.com

http://sunnet.vn

74/14B, Nui Thanh Street,  Ward 13, Tan Binh District, Ho Chi Minh City




2018-03-23 22:00 GMT+07:00 Don McCurdy <notifications@github.com>:

**Comment by donmccurdy** [comment]
File attachments don't come through via email on GitHub issues — you'll need to add them as ZIP files through the comment box on the website.

**Comment by CuongAnimator** [comment]
[sample_01.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1844029/sample_01.zip)
I've attached a .Zip file
Please help me to check it.
Thanks

**Comment by donmccurdy** [comment]
It is working correctly for me, including animation:

<img width="470" alt="screen shot 2018-03-24 at 12 02 16 pm" src="https://user-images.githubusercontent.com/1848368/37867873-f5f0eeec-2f5b-11e8-9757-0ffac36aacf6.png">

Have you tried the most recent version of KhronosGroup/glTF-Blender-Exporter? Or are you using a different exporter?

**Comment by CuongAnimator** [comment]
Yeah!! Awesome
How do you do?
We use this file to export in the Blender.
[blendergltf-master.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1845029/blendergltf-master.zip)
Please tell me know a way that you complete the export to glTF.
Thanks so much

**Comment by donmccurdy** [comment]
I'm using a different glTF Blender exporter, here: https://github.com/khronosgroup/gltf-blender-exporter

You can only have one glTF exporter enabled at a time, so you'll need to disable your current one to install this.

**Comment by CuongAnimator** [comment]
Thanks
I will test it.

**Comment by CuongAnimator** [comment]
Hi
I installed it.
But I also have a problem with the mesh.
When I import fbx file and export to glTF file
Do you have nay notices to me?

**Comment by donmccurdy** [comment]
The same problem with the mesh? Make sure that you have disabled or deleted the other blender exporter, before installing the new one.

**Comment by CuongAnimator** [comment]
Do you can use teamview to check it help me?
Please!!!

**Comment by donmccurdy** [comment]
Sorry I'm not on teamview, but here is a screen recording and the resulting .gltf file:

https://drive.google.com/open?id=12gudJ16_I4d96Pu4YGOWmu5TygaOqitN

**Comment by CuongAnimator** [comment]
Hi
[Untitled Project.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1845312/Untitled.Project.zip)
Please check it and help me

**Comment by donmccurdy** [comment]
I don't know why the export is working for me and not for you, sorry. Your screen recording looks the same as what I'm doing. 😞

Could you try:

1. Download the `.gltf` and `.png` files I put in [google drive](https://drive.google.com/open?id=12gudJ16_I4d96Pu4YGOWmu5TygaOqitN) and try dragging them into the viewer, to make sure it appears correctly for you. If not, perhaps the same model is working on my machine and not yours, in which case it may be a three.js bug.
2. If my copy of the model looks correct to you, please [file a bug ](https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/new) on the Blender exporter, including the screen capture, FBX file, and a link to this conversation.
