### ISSUE TITLE
Multiple channels do not animate

### ISSUE THREAD

**Issue by CentaurMare** [donmccurdy/three-gltf-viewer#79]
three-gltf-viewer only animates animation channel 0 of the following model...
[https://sketchfab.com/models/dae8762d6a8843a790a9fb4c386b6fc8]

With my C# viewer, the other channels are messed up (cloth is in wrong position), so I now suspect an export issue from sketchfab.com (there was definitely an export issue with the materials), however what is stopping the other channels from animating in three-gltf-viewer?

**Comment by donmccurdy** [comment]
The main thing I see is that this model has several meshes with 150 morph targets. glTF does not set a limit, but only requires the client to implement support for 8 due to WebGL uniform limits. threejs supports only 8 influences.

**Comment by CentaurMare** [comment]
Thanks Don, can you please clarify what you mean in terms of WebGL uniform limits?
By 8 influences, I think you mean a combination of position/normal/tangent morphs, from spec, correct?

>Implementation note: The number of morph targets is not limited in glTF. A conformant client implementation must support at least eight morphed attributes. This means that it has to support at least eight morph targets that contain a POSITION attribute, or four morph targets that contain a POSITION and a NORMAL attribute, or two morph targets that contain POSITION, NORMAL and TANGENT attributes. For assets that contain a higher number of morphed attributes, renderers may choose to either fully support them (for example, by performing the morph computations in software), or to only use the eight attributes of the morph targets with the highest weights.<

Which kind of threw me when I was writing my vertex shader, but I ignored it and eventually managed to support unlimited morph targets with position, normal and tangent in my C# viewer.

Is the issue with WebGL related to the OpenGL version?

**Comment by donmccurdy** [comment]
I had it backward, the limit is not 128-1024 uniforms but [16 vertex attributes](https://webglstats.com/webgl/parameter/MAX_VERTEX_ATTRIBS). Not strictly WebGL (some devices support more) but three.js reserves 8 vertex attributes for morph targets. I think WebGL2 shares the same limit, but there may be other ways to implement morph targets in different graphics APIs.

**Comment by CentaurMare** [comment]
I originally attempted to use vertex attributes and did hit the limit of 16 on my laptop, but in the end I  used three SSBOs (one for each of position, normal and tangent), each one needed to be a vec4 or there were alignment issues. Each SSBO stored all the targets, so 150 x 2 in the case of the my test model.

Can three.js not use SSBOs?
