### ISSUE TITLE
Visualizing glb file on Cesium

### ISSUE THREAD

**Issue by NitishJaiswal** [donmccurdy/three-gltf-viewer#81]
I am working on a project where I need to upload 3D files on cesium. I have used SketchUp Collada files to obtain 3d object image using COLLADA2GLTF converter but the files are showing some errors. How can I fix this?
![screenshot 18](https://user-images.githubusercontent.com/37929801/38310789-155d37bc-383b-11e8-9ea9-584734b42d8a.png)
![screenshot 19](https://user-images.githubusercontent.com/37929801/38310815-2687b738-383b-11e8-86eb-abc5a8926272.png)

**Comment by donmccurdy** [comment]
This has been fixed on the latest version of COLLADA2GLTF.

**Comment by donmccurdy** [comment]
thanks for reporting the problem!
