### ISSUE TITLE
Skinned models from BabylonJS Max exporter don't render properly

### ISSUE THREAD

**Issue by bghgary** [donmccurdy/three-gltf-viewer#82]
We're seeing some inconsistent behavior between BabylonJS sandbox and three.js with models being exported from the BabylonJS Max exporter.

Here is an example:
[Yeti.zip](https://github.com/donmccurdy/three-gltf-viewer/files/1878237/Yeti.zip)

It looks fine in BabylonJS sandbox:
![image](https://user-images.githubusercontent.com/19158740/38341591-2bff3ed2-382e-11e8-96df-df6b0f7d51b6.png)

But looks broken in this viewer:
![image](https://user-images.githubusercontent.com/19158740/38341613-4fa0bd5c-382e-11e8-811b-85f00adba529.png)

I can confirm that this model at least also works when uploaded to Sketchfab (though no materials):
![image](https://user-images.githubusercontent.com/19158740/38341681-a9bba16c-382e-11e8-8a27-78f5d7cc9afe.png)

Any ideas?

**Comment by bghgary** [comment]
Aah, good to know. 😁 That explains what I was seeing when trying to narrow it down. Thanks for investigating!

**Comment by donmccurdy** [comment]
I think other tools will also struggle with this case (the Blender exporter definitely makes assumptions about uniqueness of node names), so if the BabylonJS Max exporter needs to duplicate nodes for some reason, it might be good for it to append numbers too them. Would be good for us to fix it in three.js too I think, but it's a longstanding issue.

**Comment by bghgary** [comment]
Yeah, I had a similar thought and just made the suggestion to the team to export unique names.

**Comment by donmccurdy** [comment]
Closing this issue, also tracked in https://github.com/donmccurdy/three-gltf-viewer/issues/58 though

**Comment by noalak** [comment]
BabylonJS Max exporter now exports unique node names, adding a suffix to the name " (1)", " (2)"... if necessary (see [issue](https://github.com/BabylonJS/Exporters/issues/135)). Check is not recurssive though.

**Comment by donmccurdy** [comment]
Awesome, thanks!

**Comment by donmccurdy** [comment]
(also, I like this Yeti model a lot 😁)
