### ISSUE TITLE
Group common code/pointer pairs

### ISSUE THREAD

**Issue by donmccurdy** [donmccurdy/three-gltf-viewer#84]
entries like this should generate at most N errors:
`ACCESSOR_NON_UNIT` + `accessors/<N>`

^ideally don't lose message list...

**Comment by lexaknyazev** [comment]
There was an idea to do that on the validation side. See https://github.com/KhronosGroup/glTF-Validator/issues/29.

**Comment by donmccurdy** [comment]
I'd be happy for this to occur validation-side, yes. Can implement here if not.

**Comment by lexaknyazev** [comment]
VS Code workflow could benefit from this as well so implementing this in the validator seems reasonable.
The open question is [how the validation report should look like](https://github.com/KhronosGroup/glTF-Validator/issues/29#issuecomment-379342583) since processing issues list is trivial.
