### ISSUE TITLE
.glb file isn't getting rendered properly on Ubuntu 14

### ISSUE THREAD

**Issue by kishorck12** [donmccurdy/three-gltf-viewer#85]
I am using a .glb file and when I try to render it using gltf-viewer, file is rendered but on zoom in I get  this error "Rats! webGL hit a snag" and nothing works later.

This happens with only ubuntu not with Linux.

**Comment by donmccurdy** [comment]
Is this in Chrome? Could you try going to `chrome://gpu/` and pasting the details there into a new pastebin or attachment? Do [other three.js glTF examples](https://threejs.org/examples/?q=glt#webgl_loader_gltf) work for you?
