### ISSUE TITLE
Interesting feature: Walk navigation

### ISSUE THREAD

**Issue by MiguelAlgaba** [donmccurdy/three-gltf-viewer#89]
Hi, I think one interesting feature could be to have a way to navigate the scene with a 'Walk Navigation'. Maybe the WASD keys to move forwards, left, right, backwards. Or maybe having a toggle to use the arrow keys to walk and mouse to change viewing direction.

Thanks for the great work!

**Comment by donmccurdy** [comment]
With the latest update, the viewer will pan horizontally rather than vertically when you use the right mouse button to drag. This should make it much easier to get around large scenes. But I think full WASD controls are probably out of scope for this viewer. Thanks for the suggestion. :)
