### ISSUE TITLE
Metallic and roughness

### ISSUE THREAD

**Issue by emackey** [donmccurdy/three-gltf-viewer#9]
Hi!  I tried drag-and-drop of the [Metal-Rough Spheres](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MetalRoughSpheres) sample model in Chrome 57, and I got a result that doesn't look like the metal/rough channels are in use.

![threejs_metalrough_notright](https://cloud.githubusercontent.com/assets/1235080/25784150/9a482d48-3336-11e7-9422-9857ea19235e.png)

Is this a known issue?  I would expect the model to behave [more like this](https://emackey.github.io/BabylonJS-glTFLoader/?model=MetalRoughSpheres).

![metalRoughScreenshot](https://github.com/KhronosGroup/glTF-Sample-Models/blob/31066c55f337fbab0b5b993a7b0b525670f8d186/2.0/MetalRoughSpheres/screenshot/screenshot.png?raw=true)

**Comment by donmccurdy** [comment]
@emackey thanks for this test model! i'd been thinking [other test models](https://github.com/mrdoob/three.js/issues/11268) looked plastic-ey, and this seems to confirm that pretty clearly.. the metal/rough texture is being sent to THREE.MeshStandardMaterial at least, but I'm not sure yet why it isn't applied correctly. Will look into this more.

**Comment by donmccurdy** [comment]
Looks like this issue has been fixed in recent updates to GLTF2Loader and/or three.js r85, I've updated the viewer.

![screen shot 2017-05-07 at 6 09 48 pm](https://cloud.githubusercontent.com/assets/1848368/25786868/791c0ba2-3350-11e7-9347-1b8fb2fd7080.png)

**Comment by emackey** [comment]
Wow Don that was fast!  But I have another coming your way in a minute... 😈 👼
