### ISSUE TITLE
GLTF Vertex Color / Texture discrepancy

### ISSUE THREAD

**Issue by Rayfoundry** [donmccurdy/three-gltf-viewer#90]
The rendering of meshes with color information stored in vertex colors or albedo textures is different. From my understanding, they should be the same?

To reproduce, load GLBs from [VertexColor](https://s3-eu-west-1.amazonaws.com/rayfoundry.de/viewer/obj/TestVertexColor/ARMOURDILLO_ASMB_2.0_v1_proxy.glb) and [Texture](https://s3-eu-west-1.amazonaws.com/rayfoundry.de/viewer/obj/TestTexture/ARMOURDILLO_ASMB_2.0_v1_proxy.glb) into your viewer.

There has been a lot of discussion about how to properly  apply gamma to threejs and it seems that setting `renderer.gammaoutput = true;` is the recommended path for GLTF. This seems to not work for non-textured GLTF models though. 

(The texture is created with Substance Designer Baker with the Color-From-Mesh option to bake vertex colors to a texture. The texture is sRGB.) -> [basecolor texture](https://s3-eu-west-1.amazonaws.com/rayfoundry.de/viewer/obj/TestTexture/ARMOURDILLO_ASMB_2.0_v1_proxy_mat_neutral_basecolor.jpg)

-> Something doesn't really add up with how gamma is handled. On a sidenote, setting `renderer.gammaInput = true;` for the textured version makes a visual difference and looks more correct (more contrast) - which it shouldn't because if everything would work correctly, the texture.encoding set to sRGB in the GLTFLoader would be enough?

**Comment by Rayfoundry** [comment]
#44

**Comment by Rayfoundry** [comment]
Thank you, this all makes sense.

Yes, I used the FBX2GLTF converter. The FBX is written from Houdini from SideFX.
I'm checking now if the vertex values are converted to sRGB on export.

The baking software we are using (Substance Designer) stores the vertex color values 1:1 into the texture. So if I have linear vertex color values in my model, I have to convert the baked texture to sRGB space because this is what is expected in a PBR workflow? What I try to say is that regardless of the input color values, if ThreeJS interprets them differently, I have to grade the texture?

**Comment by donmccurdy** [comment]
I thought SideFX stored linear colorspace, unlike Blender... whether they export that to FBX I don't know. If Substance Designer is converting vertex colors 1:1 into the texture, and if your input file had linear vertex colors, then yeah you'll get a washed out result. I'm not actually sure whether OBJ or FBX specify colorspace of vertex colors at all.

Interestingly Sketchfab gives a toggle to select which you have, and the default is sRGB.

/cc @zellski do you know whether FBX specifies colorspace anywhere?

**Comment by Rayfoundry** [comment]
Found some solution for my case: In my case I'm setting the vertex colors myself, parsing from RGB value strings like "127, 056, 50" in Houdini. To get the color I expect, I have to pow(color, 2.2) to linearize it. Then when it's baked with substance baker, I chain 3! linearToSRGB nodes doing pow(color, 0.4545). The result is now the same between vertex color display and texture display in ThreeJS - but I don't understand why to be honest. Anyway: Fixed for my pipeline.

**Comment by donmccurdy** [comment]
Yeah the Blender exporter was getting this wrong, proposed a fix here: https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/209

Also [filed an issue on FBX2glTF](https://github.com/facebookincubator/FBX2glTF/issues/100), although I don't know whether it's possible for the converter to detect the incoming vertex colors' colorspace.  Other than that I don't think there's more I can do in this viewer, since I have to assume the model shown is using linear vertex colors to spec.

**Comment by zellski** [comment]
Hey, sorry for missing this. I am unable to find anything, so far, about FBX being able to store metadata on how RGB tuples should be interpreted. I'm pessimistic but holding out hope that there's rhyme and reason here, and not just amorphous semi-consensus between different generators.

**Comment by donmccurdy** [comment]
Thanks! Yeah, I was afraid that might be the case.
