### ISSUE TITLE
Speckles on draco encoded models with normal map

### ISSUE THREAD

**Issue by Rayfoundry** [donmccurdy/three-gltf-viewer#92]
Some draco compressed GLTF files with a normal map apllied are displayed with "speckles" in the viewer. [Babylon.JS Sandbox](https://sandbox.babylonjs.com/) displays the same files correctly.

Note: Babylon.JS also shows very few artifacts, but the result is much better and could be considered "good enough".

 Model to test: [Link](https://s3-eu-west-1.amazonaws.com/rayfoundry-tmp/speckles.glb)

**Comment by donmccurdy** [comment]
Could you post screenshots of the speckles you mean? And are they present before Draco compression? I see a bit of this in both viewers:

![screen shot 2018-05-04 at 10 30 39 am](https://user-images.githubusercontent.com/1848368/39642352-5bfa6f98-4f86-11e8-8c80-02f360f31f98.png)

**Comment by Rayfoundry** [comment]
Sure. 

<img width="959" alt="capture" src="https://user-images.githubusercontent.com/20320596/39649060-c38ca744-4fe4-11e8-84b6-f1ef8e423869.PNG">

**Comment by Rayfoundry** [comment]
And here is the same file in the viewer without draco compression.

<img width="742" alt="capture2" src="https://user-images.githubusercontent.com/20320596/39650205-86d5db7e-4fe7-11e8-82b6-5012cc5408b8.PNG">

[Link to GLB](https://s3-eu-west-1.amazonaws.com/rayfoundry-tmp/nodraco.glb)

**Comment by Rayfoundry** [comment]
@donmccurdy Were you able to reproduce this? I see this behaviour on two different desktop devices with a low end and high-end graphics card.

**Comment by Rayfoundry** [comment]
@donmccurdy This seems to be a issue with FBX2GLTF. Using gltf-pipeline (2.0) the artifacts are gone. Posting the issue on FBX2GLTF now. 

P.S.: Doesn't explain why Babylon.JS shows the same file with less artifacts, but the root source is clearly not with GLTFViewer. Please close if you like.

**Comment by donmccurdy** [comment]
It looks fairly different on my machine:

<img width="765" alt="screen shot 2018-05-08 at 7 37 41 am" src="https://user-images.githubusercontent.com/1848368/39763720-c31d00b4-5292-11e8-938c-7127ceb3e10d.png">

But yes, I would guess perhaps it has to do with either the Draco compression settings used by FBX2glTF, or the version of the Draco encoder... not sure but the issue on FBX2glTF may get better answers. :)
