### ISSUE TITLE
Strange distortion of ROME models while playing animations

### ISSUE THREAD

**Issue by lexaknyazev** [donmccurdy/three-gltf-viewer#94]
Download `quadruped_horse` from [here](https://github.com/mrdoob/rome-gltf/blob/master/files/models/life_soup/quadruped_horse.gltf) and drop it into the viewer. Animation looks as if camera uses inverse perspective or something.

Viewers on [project's page](https://mrdoob.github.io/rome-gltf/) show no issues (maybe that's because they use 10 months old three.js build).

If the issue is with the models, could they be reexported?

**Comment by donmccurdy** [comment]
The project page is adding doubleSide at runtime, because the Blender exporter only writes doubleSide for models using the special glTF Cycles nodes rather than default Blender materials, which these models do not. Filed https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/230.
