### ISSUE TITLE
Exporting strokes/edges invisible

### ISSUE THREAD

**Issue by sinsedrix** [donmccurdy/three-gltf-viewer#95]
Hi,
When I export a model with strokes/edges on which I set a material, I can't see them on facebook import or in the glTF viewer.
I am missing something or isn't it implemented?
Thanks

**Comment by donmccurdy** [comment]
Exporting how? The glTF format supports lines, but I don't know which export tools support it. Can you provide an example model to determine whether the lines are in the glTF file? You can drag ZIP files into GitHub comments.
