### ISSUE TITLE
[Draco crash] Uncaught (in promise) Assertion failed: (normal.AbsSum()) <= (upper_bound)

### ISSUE THREAD

**Issue by chipweinberger** [donmccurdy/three-gltf-viewer#99]
Hey Don,

Hope you're doing well. This crash *may* not be the viewers fault, but I figured this was a decent place to start diagnosing this problem. Any Ideas on why the loader is complaining with this file?

`Uncaught (in promise) Assertion failed: (normal.AbsSum()) <= (upper_bound), at: /google/src/cloud/ostava/fix/google3/third_party/draco/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_area.h,95,ComputePredictedValue at Error
    at g (https://gltf-viewer.donmccurdy.com/lib/draco/draco_wasm_wrapper.js:14:469)
    at ___assert_fail (https://gltf-viewer.donmccurdy.com/lib/draco/draco_wasm_wrapper.js:51:143)
    at wasm-function[223]:832
    at wasm-function[288]:381
    at wasm-function[205]:616
    at wasm-function[270]:7
    at wasm-function[204]:338
    at wasm-function[182]:51
    at wasm-function[193]:88
    at wasm-function[191]:299`

The buffer was compressed with the most recent version of Draco (1.3.2)

I see that the draco extension says: "This extension specification is based on Draco bitstream version 2.2 (the entirety of this specification is normative and included in Scope)", but which version of Draco does that correspond to? Haven't been able to find that important detail.

[SimpleFishGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2082263/SimpleFishGltf.zip)

**Comment by chipweinberger** [comment]
Hold on... noticed the draco extension attributes aren't being written. The

**Comment by chipweinberger** [comment]
[SimpleFishGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2082282/SimpleFishGltf.zip)

Here's the updated file. Same issue.

**Comment by chipweinberger** [comment]
For reference, here are my draco encode options:

`		struct DracoSettings {
			/*  Sets the desired encoding and decoding speed for the given options. 
			 *  Read draco speed option docs for more details.
			 *   0 = slowest speed, but the best compression.
			 *  10 = fastest, but the worst compression.
			 *  -1 = undefined. */
			int encodeSpeed = 0; 
			int quantizationBits_positions = 20;
			int quantizationBits_texCoords = 12;
			int quantizationBits_colors = 14;
			int quantizationBits_normals = 13;
			int quantizationBits_generic = 20;
		};`

**Comment by chipweinberger** [comment]
Seems like I might need to normalize my normals. Going to try that!

**Comment by chipweinberger** [comment]
[SimpleFishGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2082324/SimpleFishGltf.zip)

Seems like might be the issue. I've removed both the NORMALS and TEXCOORDS in this example and now it loads. 

There seems to be a discrepency in how draco and Gltf use their "normalized" field. 

	draco::GeometryAttribute att;
	att.Init(
		dracoAttribType, //Type attribute_type, 
		0,							//DataBuffer *buffer, NULL means it will create one for us
		NumVecComponents(acc.vecType),    //int8_t num_components,
		toDracoDataType(acc.componentType),//DataType data_type, 
		acc.normalized.value(),		   //bool normalized, 
		0,							    //int64_t byte_stride,
		0								//int64_t byte_offset);
	);


Gltfs: Accesorr::normalized: Specifies whether integer data values should be normalized (`true`) to [0, 1] (for unsigned types) or [-1, 1](for signed types), or converted directly (`false`) when they are accessed. This property is defined onlyfor accessors that contain vertex attributes or animation output data. Default value of false.Only (u)byte and (u)short accessors can be normalized

Draco: undocumented AFAICT. Presumably is wants to know whether the input data is *already* lenght == normalized (0-1). 

Oddly, draco is looking ab normal.absSum(). Shouldn't it be looking at nomal.length()?

**Comment by chipweinberger** [comment]
[SimpleFishGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2082340/SimpleFishGltf.zip)

By removing normals (before compression) and telling draco that the texCoords are not normalized (the largest texcoord has a length of 1.10), I would have expected it to still load.

Instead im getting a WASM memory accessess out of bound error on draco decode. Odd. 


```
wasm-000dab66-243:598 Uncaught (in promise) RuntimeError: memory access out of bounds
    at wasm-function[243]:1140
    at wasm-function[242]:280
    at wasm-function[205]:616
    at wasm-function[270]:7
    at wasm-function[204]:338
    at wasm-function[182]:51
    at wasm-function[193]:88
    at wasm-function[191]:299
    at wasm-function[397]:67
    at wasm-function[396]:599
```

**Comment by donmccurdy** [comment]
Note that there is a glTF branch on the Draco repository, intended (as far as I know) to track the latest version compatible with the Draco glTF extension. I didn't think the master branch had diverged in a backward-compatible way, but perhaps it has...

About the errors on decoding, I'm afraid I don't know what might be happening. Hopefully the Draco folks will!

Also note that in your primitive:


```
"primitives": [
    {
        "attributes": {},
        "extensions": {
            "KHR_draco_mesh_compression": {
                "attributes": {
                    "NORMAL": 1,
                    "POSITION": 0
                },
                "bufferView": 5
            }
        },
        "material": 0,
        "mode": 4
    }
```

`primitive.attributes` should (still) be pointing to actual accessors defining count, min, max, and attribute types. Those accessors should simply not contain a `bufferView` property. But it sounds like that is probably not the root cause here.

**Comment by chipweinberger** [comment]
Ah, thanks for that clarification about primitive.attributes! I'll give that a shot and see if it makes any difference. I'll also check out that draco branch.

Thanks for the helpful suggestions, as always!

**Comment by chipweinberger** [comment]
So as initially suspected, it's likely a versioning issue. The draco guys are suggesting you update your draco libs.

https://github.com/google/draco/issues/419#issuecomment-395808539

**Comment by donmccurdy** [comment]
Should be fixed on next deployment, thanks!

**Comment by chipweinberger** [comment]
Works! Thanks Don!

[SimpleFishGltf.zip](https://github.com/donmccurdy/three-gltf-viewer/files/2091377/SimpleFishGltf.zip)
